dut_ecu: ["BGM"]
com_mock_ecu: []
gateway_ip: "169.254.19.1"
task_id: 11954

bus:
  eth_obd: "enp114s0"
  eth_vlan5: "eth0.5"
  eth_vlan9: "eth0.9"
  passivesafetycan: 'can4'

veh_type: 'mars1'
veh_gen: ''
bl_ver: 'v_2_0_0'

ecu_mock_cfg:
  ecu_name: "ALL"
  p_n_res: True
  nrc_code: 0x22
  diag_mode: "ALL"
  server_doip_id: 0x1002
  server_ip: "172.16.9.222"

sd_tester_cfg:
  diag_mode: "doip"
  is_via_gateway: True
  ecu_name: "RML"
  dig_bus: "passivesafetycan"
  server_ip: "169.254.19.1"
