#!/usr/bin/env python
# -*- coding: utf-8 -*-


import os
import sys
import time
import threading
import pytest
import allure

sys.path.append(os.getcwd())
sys.path.append(os.path.join(os.getcwd(), ".."))
sys.path.append(os.path.join(os.getcwd(), "../.."))
sys.path.append(os.path.join(os.getcwd(), "../../.."))
from xat_cases.legacy.abc_demo.case_helper.test_abc_base import TestABCBase
from xat_ecu.api.abc_interface import *
from xat_ecu.api.interface import *


@allure.feature("互联服务/远程控制/远控稳定性控制")
@allure.story("远控稳定性控制")
class TestRCRepeat(TestABCBase):
    def before_class(self, ecu):
        self.tsp.set_bench_config(self.tb_config["vid"], self.tb_config["tel"])
        self.soa.update(["VehicleModeService_client", "TailGateService_client", "VehicleSetStatusService_client"])
        self.soa.set_and_check_maintain_mode(status=False)
        time.sleep(5)
        self.sd_tester.write_ccp({181:0x02,189:0x02})
        # self.sd_tester.session_ctrl_and_check(TA.TCAM,SESSION.EXTENDED,'62f18603')
        # self.sd_tester.send_data_and_check(TA.TCAM,'1103','5103')
        # time.sleep(180)
        # 切换driving模式
        self.bus_comm.set_vehmtn()
        self.bus_comm.set_vehspd()
        self.bus_comm.set_singal(bus="backbonefr", msg="VddmBackBoneFr18", signal="TrsmParkLockdTrsmParkLockd", value=1)
        self.bus_comm.set_engine_sts(EngSt1WdStsEngSt1WdSts=EngSt1WdStsEngSt1WdSts.EngSt1_Awake)
        time.sleep(1)
        self.bus_comm.set_dtc_pre()
        self.soa.send_method_request( 'VehicleModeService_client','SetUsageModeDown',{"mode": 1})
        time.sleep(1)
        self.bus_comm.check_usage_mode_status(usage_mode=UsageMode.INACTIVE)
        self.mix.s2s_change_car_mode_and_check_result(car_mode=CarMode.NORMAL, car_mode_sub=0)
        self.mix.service_change_usage_mode_and_check_result(usagemode=UsageMode.ACTIVE)
        self.bus_comm.set_engine_sts(EngSt1WdStsEngSt1WdSts=EngSt1WdStsEngSt1WdSts.EngSt1_RunngRunng)
        time.sleep(1)
        self.bus_comm.check_usage_mode_status(UsageMode.DRIVING)
        time.sleep(30)
        self.bus_comm.set_engine_sts(EngSt1WdStsEngSt1WdSts=EngSt1WdStsEngSt1WdSts.EngSt1_Ini)
        time.sleep(2)
        self.mix.service_change_usage_mode_and_check_result(usagemode=UsageMode.INACTIVE)


    def before_each_func(self, ecu):
        # logger.info("检查时间同步状态： {0}".format(self.ssh.tcam_ssh.exec("date")))
        self.io.bgm_diag_line_up()
        self.io.tcam_kl15_up()
        self.mix.set_car_mode(CarMode.NORMAL)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr03', 'RemClimaActv_0_CcmBodySignalIPdu03', 'OnOff1_Off')
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecLe', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecLe', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecRi', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecRi', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatVentAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatVentnLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatVentAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatVentnLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentAvlStsRowSecLe', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentnLvlStsRowSecLe', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentAvlStsRowSecRi', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentnLvlStsRowSecRi', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan','CcmBodyFr11','ClimaDefrstSts', 'OnOff1_Off')
        self.bus_comm.set_singal('bodycan','CcmBodyFr31','RemClimaDefrstSts', 'OnOff1_Off')
        self.bus_comm.set_singal('bodycan','CcmBodyFr61', 'RemSteerWhlHeatgLvlReq_0_CcmBodySignalIPdu61', 'OnOff1_Off')
        self.bus_comm.set_singal('backbonefr', 'CemBackBoneFr19', 'SteerWhlHeatgLvlSts', 'SteerWhlHeatgOnCmdTyp_Off')
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr08', 'CmptmtTFrntQf', 3)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr08', 'CmptmtTFrntCmptmtTFrnt', 700)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr28', 'AmbTEstimdQf', 1)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr28', 'AmbTEstimdAmbTEstimd', 791)
        time.sleep(20)

    def after_each_func(self, ecu):
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr03', 'RemClimaActv_0_CcmBodySignalIPdu03', 'OnOff1_Off')
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecLe', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecLe', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecRi', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecRi', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatVentAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatVentnLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatVentAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatVentnLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentAvlStsRowSecLe', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentnLvlStsRowSecLe', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentAvlStsRowSecRi', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentnLvlStsRowSecRi', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan','CcmBodyFr11', 'ClimaDefrstSts', 'OnOff1_Off')
        self.bus_comm.set_singal('bodycan','CcmBodyFr61', 'RemSteerWhlHeatgLvlReq_0_CcmBodySignalIPdu61', 'OnOff1_Off')
        self.bus_comm.set_singal('backbonefr', 'CemBackBoneFr19', 'SteerWhlHeatgLvlSts', 'SteerWhlHeatgOnCmdTyp_Off')
        time.sleep(2)

    def after_class(self, ecu):
        pass

    @pytest.mark.repeat(100)
    @allure.title("远控空调-RVC_远控开启空调_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1981005(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")
        execid = self.tsp.rvc_ac_control(1,220)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmClimaReq', 'OnOffNoReq_On',timeout = 20)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr03', 'RemClimaActv_0_CcmBodySignalIPdu03', 'OnOff1_On')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启空调成功时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        time.sleep(180)
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)
        time.sleep(5)
        execid1 = self.tsp.rvc_ac_control(-1,220) 
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmClimaReq', 'OnOffNoReq_Off',timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr03', 'RemClimaActv_0_CcmBodySignalIPdu03', 'OnOff1_Off')  
        assert self.tsp.log_search_remote_vehicle_control(execid=execid1, keywords="Success")  

    @pytest.mark.repeat(3)
    @allure.title("远控除霜-RVC_远控开启除霜_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_defrost_control_caseid_1983860(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")                
        execid = self.tsp.rvc_defrost_control(1)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr92',"TelmDefrostReq","OnOffNoReq_On")
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr31',  'RemClimaDefrstSts', 'OnOff1_On')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启除霜时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        time.sleep(180)
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)            

    @pytest.mark.repeat(3)
    @allure.title("远控座椅加热-RVC_远控开启主驾座椅加热_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1980703(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")
        execid = self.tsp.rvc_driver_seat_heat(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr48', 'TelmSeatDrvHeatClimaLvl', 'TelmSeatClimaLvl_Lvl3', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgAvlSts', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgLvlSts', 'SeatClimaLvl_Lvl3')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启副驾座椅加热时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)
        time.sleep(20)
        self.tsp.rvc_driver_seat_heat(level=-1)
        self.bus_comm.check_singal('bodycan', 'CemBodyFr48', 'TelmSeatDrvHeatClimaLvl', 'TelmSeatClimaLvl_off', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgLvlSts', 'SeatClimaLvl_Off')
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")  

    @pytest.mark.repeat(3)
    @allure.title("远控座椅加热-RVC_远控开启副驾座椅加热_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1980873(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")
        execid = self.tsp.rvc_passenger_seat_heat(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr48', 'TelmSeatPassHeatClimaLvl', 'TelmSeatClimaLvl_Lvl3', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgAvlSts', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgLvlSts', 'SeatClimaLvl_Lvl3')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启副驾座椅加热时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        time.sleep(180)
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)   

    @pytest.mark.repeat(3)
    @allure.title("远控座椅加热-RVC_远控开启左后座椅加热_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1980871(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")
        execid = self.tsp.rvc_rearleft_seat_heat(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatSecLeHeatClimaLvl', 'TelmSeatClimaLvl_Lvl3', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecLe', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecLe', 'SeatClimaLvl_Lvl3')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启左后座椅加热时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)
        time.sleep(20)
        execid = self.tsp.rvc_rearleft_seat_heat(level=-1)
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatSecLeHeatClimaLvl', 'TelmSeatClimaLvl_off', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecLe', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecLe', 'SeatClimaLvl_Off')
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")  

    @pytest.mark.repeat(3)
    @allure.title("远控座椅加热-RVC_远控开启右后座椅加热_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1980872(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")
        execid = self.tsp.rvc_rearright_seat_heat(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatSecRiHeatClimaLvl', 'TelmSeatClimaLvl_Lvl3', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecRi', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecRi', 'SeatClimaLvl_Lvl3')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启右后座椅加热时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        time.sleep(180)
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)   

    # @pytest.mark.repeat(3)
    @allure.title("远控方向盘加热-RVC_远控开启方向盘加热_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1960471(self, ecu):
        # self.mix.network_sleep()
        # time.sleep(60)
        # logger.info("已休眠")              
        execid = self.tsp.rvc_steering_wheel_heat(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(2.5)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CEMBodyFr36', 'TelmSteerWhlHeatgReqLvl', 'TelmSeatClimaLvl_Lvl3',timeout = 20, do_assert = False)
        self.bus_comm.set_singal('backbonefr', 'CcmBodyFr61', 'RemSteerWhlHeatgLvlReq', 3)
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启方向盘加热时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        time.sleep(180)
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)            

    # @pytest.mark.repeat(3)
    # @allure.title("RVC_座舱预约执行_预约单次整流程")
    # @pytest.mark.stress_test
    # def test_cock_reserv_UM_aban_caseid_1982126(self):
    #     self.mix.network_sleep()
    #     time.sleep(60)
    #     logger.info("已休眠")
    #     with allure.step("下发远控预约"):
    #         task_time=self.tsp.rvc_taskCmd(appointment_minute=15)[1]
    #         assert self.tsp.log_SubscribeTaskResp_search(detail="cmdResp=execId", keywords="Success")
    #         self.bus_comm.check_PNC(BusName.connectivitycanfd, NMMsgId.x509, TCAMPNC.PNC30, NMSts.valid, timeout=20)
    #         self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
    #         self.bus_comm.check_PNC(BusName.connectivitycanfd, NMMsgId.x509, TCAMPNC.PNC26, NMSts.valid, timeout=20)
    #         self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
    #         time.sleep(2.5)
    #         self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
    #         self.bus_comm.check_singal('bodycan', 'CemBodyFr63', 'RemStrtExtnTiReq', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
    #         self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmClimaReq', 'OnOffNoReq_On',timeout = 20, do_assert = False)
    #         self.bus_comm.check_singal('bodycan', 'CemBodyFr48', 'TelmSeatDrvHeatClimaLvl', 'TelmSeatClimaLvl_Lvl1', timeout = 20, do_assert = False)
    #         self.bus_comm.check_singal('bodycan', 'CemBodyFr48', 'TelmSeatPassHeatClimaLvl', 'TelmSeatClimaLvl_Lvl1', timeout = 20, do_assert = False)
    #         self.bus_comm.check_singal('bodycan', 'CemBodyFr36', 'TelmSteerWhlHeatgReqlvl', 'TelmSeatClimaLvl_Lvl1', timeout = 20, do_assert = False)

    #         self.bus_comm.set_singal('bodycan', 'CcmBodyFr03', 'RemClimaActv_0_CcmBodySignalIPdu03', 'OnOff1_On') 
    #         self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgAvlSts', 'StsFd_On')
    #         self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgLvlSts', 'SeatClimaLvl_Lvl1')
    #         self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgAvlSts', 'StsFd_On')
    #         self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgLvlSts', 'SeatClimaLvl_Lvl1')
    #         self.bus_comm.set_singal('connectivitycanfd', 'VgmConnFr03', 'SteerWhlHeatgAvlSts', 'StsFd_On')
    #         self.bus_comm.set_singal('backbonefr', 'CemBackBoneFr19', 'SteerWhlHeatgLvlSts', 'SteerWhlHeatgOnCmdTyp_Lo')
    #         self.tsp.cancel_cock_reserv_task(task_time=task_time)
    #         assert self.tsp.log_SubscribeTaskResp_search(detail="cmdResp=execId", keywords="Success")

    @pytest.mark.repeat(3)
    @allure.title("远控座椅通风-RVC_远控开启主驾座椅通风_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1960469(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")                 
        execid = self.tsp.rvc_driver_seat_vent(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr48', 'TelmSeatDrvVentnClimaLvl', 'TelmSeatClimaLvl_Lvl3', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatVentgAvlSts', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatVentgLvlSts', 'SeatClimaLvl_Lvl3')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启主驾座椅通风时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN) 
        time.sleep(20)
        execid = self.tsp.rvc_driver_seat_vent(level=-1)
        self.bus_comm.check_singal('bodycan', 'CemBodyFr48', 'TelmSeatDrvVentnClimaLvl', 'TelmSeatClimaLvl_off', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatVentAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatVentnLvlSts', 'SeatClimaLvl_Off')
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")           

    @pytest.mark.repeat(3)
    @allure.title("远控座椅通风-RVC_远控开启副驾座椅通风_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1960470(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")                 
        execid = self.tsp.rvc_passenger_seat_vent(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatPassVentnClimaLvl', 'TelmSeatClimaLvl_Lvl3', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatVentAvlSts', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatVentnLvlSts', 'SeatClimaLvl_Lvl3')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启副驾座椅通风时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN) 
        time.sleep(20)
        execid = self.tsp.rvc_passenger_seat_vent(level=-1)
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatPassVentnClimaLvl', 'TelmSeatClimaLvl_off', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatVentAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatVentnLvlSts', 'SeatClimaLvl_Off')
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")           

    @pytest.mark.repeat(3)
    @allure.title("远控座椅通风-RVC_远控开启左后座椅通风_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1980702(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")                 
        execid = self.tsp.rvc_rear_left_seat_vent(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatSecLeVentnClimaLvl', 'TelmSeatClimaLvl_Lvl3', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentAvlStsRowSecLe', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentnLvlStsRowSecLe', 'SeatClimaLvl_Lvl3')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启左后座椅通风时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)
        time.sleep(20)
        execid = self.tsp.rvc_rear_left_seat_vent(level=-1)
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatSecLeVentnClimaLvl', 'TelmSeatClimaLvl_off', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentAvlStsRowSecLe', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentnLvlStsRowSecLe', 'SeatClimaLvl_Off')
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")

    @pytest.mark.repeat(3)
    @allure.title("远控座椅通风-RVC_远控开启右后座椅通风_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1980701(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")                 
        execid = self.tsp.rvc_rear_right_seat_vent(level=3)
        start_time = time.time()
        logger.info(f"1、{start_time}")
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)  
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatSecRiVentnClimaLvl', 'TelmSeatClimaLvl_Lvl3', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentAvlStsRowSecRi', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentnLvlStsRowSecRi', 'SeatClimaLvl_Lvl3')
        end_time = time.time()
        t = end_time - start_time
        logger.info("远控开启右后座椅通风时延{}s".format(t))
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)
        time.sleep(20)
        execid = self.tsp.rvc_rear_right_seat_vent(level=-1)
        self.bus_comm.check_singal('bodycan', 'CemBodyFr47', 'TelmSeatSecRiVentnClimaLvl', 'TelmSeatClimaLvl_off', timeout = 20, do_assert = False)
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentAvlStsRowSecRi', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr01', 'SeatVentnLvlStsRowSecRi', 'SeatClimaLvl_Off')
        assert self.tsp.log_search_remote_vehicle_control(execid=execid, keywords="Success")

    @pytest.mark.repeat(3)
    @allure.title("一键备车-RVC_一键备车_abandoned压测")
    @pytest.mark.stress_test
    def test_rvc_climate_control_caseid_1990927(self, ecu):
        self.mix.network_sleep()
        time.sleep(60)
        logger.info("已休眠")  
        self.tsp.rvc_one_click_smart_cockpit_3(selectedLoc = [1,2,3,4])
        execid0 = self.tsp.rvc_one_click_smart_cockpit_2()
        execid1 = execid0 + "&&&conditionalAcControl"
        execid2 = execid0 + "&&&driverSeatVent"
        execid3 = execid0 + "&&&passengerSeatVent"
        execid4 = execid0 + "&&&rearLeftSeatVent"
        execid5 = execid0 + "&&&rearRightSeatVent"
        execid6 = execid0 + "&&&driverSeatHeat"
        execid7 = execid0 + "&&&passengerSeatHeat"
        execid8 = execid0 + "&&&rearLeftSeatHeat"
        execid9 = execid0 + "&&&rearRightSeatHeat"
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC30,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr08', 'CmptmtTFrntQf', 3)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr08', 'CmptmtTFrntCmptmtTFrnt', 700)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr28', 'AmbTEstimdQf', 1)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr28', 'AmbTEstimdAmbTEstimd', 791)
        time.sleep(0.2)
        self.bus_comm.check_singal("connectivitycanfd","VgmConnFr01", "VehModMngtGlbSafe1UsgModSts",1,timeout = 20, do_assert = False)
        self.bus_comm.check_PNC(bus_name=BusName.connectivitycanfd,msg_id=NMMsgId.x509, pnc_name=TCAMPNC.PNC26,signal_value=NMSts.valid,timeout=30)
        self.bus_comm.check_singal('bodycan', 'CemBodyFr84', 'RemStrtHvCtrlReqErsCmd', 'ErsCmd_ErsCmdOn',timeout = 20, do_assert = False)
        time.sleep(0.8)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr22', 'RemClimaHvSts_0_CcmBodySignalIPdu22', 'OnOff1_On')
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr03', 'RemClimaActv_0_CcmBodySignalIPdu03', 'OnOff1_On')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgAvlSts', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgLvlSts', 'SeatClimaLvl_Lvl1')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgAvlSts', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgLvlSts', 'SeatClimaLvl_Lvl1')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecLe', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecLe', 'SeatClimaLvl_Lvl1')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecRi', 'StsFd_On')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecRi', 'SeatClimaLvl_Lvl1')
        with allure.step('校验一键备车执行结果'):         
            result1 = self.tsp.log_search_remote_vehicle_control(execid=execid1, keywords="Success")
            result2 = self.tsp.log_search_remote_vehicle_control(execid=execid2, keywords="Success")
            result3 = self.tsp.log_search_remote_vehicle_control(execid=execid3, keywords="Success")
            result4 = self.tsp.log_search_remote_vehicle_control(execid=execid4, keywords="Success")
            result5 = self.tsp.log_search_remote_vehicle_control(execid=execid5, keywords="Success")
            result6 = self.tsp.log_search_remote_vehicle_control(execid=execid6, keywords="Success")
            result7 = self.tsp.log_search_remote_vehicle_control(execid=execid7, keywords="Success")
            result8 = self.tsp.log_search_remote_vehicle_control(execid=execid8, keywords="Success")
            result9 = self.tsp.log_search_remote_vehicle_control(execid=execid9, keywords="Success")
        self.mix.network_wakeup(wakeup_reason=Wakeup_Reasons.WAKEUP_BY_BODYCAN)
        time.sleep(10)
        execidx = self.tsp.rvc_one_click_smart_cockpit_2(op=-1)
        execidX = execidx + "&&&conditionalAcControl"
        time.sleep(1)
        self.bus_comm.set_singal('bodycan', 'CcmBodyFr03', 'RemClimaActv_0_CcmBodySignalIPdu03', 'OnOff1_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmdBodyFr04', 'DrvrSeatHeatgLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgAvlSts', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmpBodyFr03', 'PassSeatHeatgLvlSts', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecLe', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecLe', 'SeatClimaLvl_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgAvlStsRowSecRi', 'StsFd_Off')
        self.bus_comm.set_singal('bodycan', 'SmbBodyFr00', 'SeatHeatgLvlStsRowSecRi', 'SeatClimaLvl_Off')
        assert self.tsp.log_search_remote_vehicle_control(execid=execidX, keywords="Success")
        assert result1&result2&result3&result4&result5&result6&result7&result8&result9
        time.sleep(300)