# -*- coding: utf-8 -*-
"""
@File         :partenr_const.py
@Time         :2023/05/25 13:27:00
@Author       :jiabin.zhu@jiduauto.com
@Description  :
"""

RESETSOAVONFIG_SERVICE_CLIENT = "ResetSOAConfigService_client"
LIGHT_SERVICE_CLIENT = "LightService_client"
ENTRY_SERVICE_CLIENT = "EntryService_client"
WTI_SERVICE_CLIENT = "WTIService_client"
CTD_SERVICE_CLIENT = "CTDService_client"
WIPER_SERVICE_CLIENT = "WiperService_client"
CENTRALLOCK_SERVICE_CLIENT = "CentralLockService_client"
VEHICLESETSTATUS_CLIENT = "VehicleSetStatusService_client"
CHASSIS_SERVICE_CLIENT = "ChassisService_client"
HIGHVOLTAGE_SERVICE_CLIENT = "HighVoltageService_client"
DOOR_SERVICE_CLIENT = "DoorService_client"
KEY_SERVICE_CLIENT = "KeyService_client"
WINDOW_SERVICE_CLIENT = "WindowService_client"
SEAT_SERVICE_CLIENT = "SeatService_client"
STEERWHEEL_SERVICE_CLIENT = "SteerWheelService_client"
CLIMATECONTROL_SERVICE_CLIENT = "ClimateControlService_client"
SHIELDWINDOW_SERVICE_CLIENT = "ShieldWindowService_client"
CHARGELID_SERVICE_CLIENT = "ChargeLidService_client"
OUTERREARVIEW_SERVICE_CLIENT = "OuterRearViewService_client"
INNERREARVIEW_SERVICE_CLIENT = "InnerRearViewService_client"
TAILGATE_SERVICE_CLIENT = "TailGateService_client"
VEHICLECONTROLFAULT_SERVICE_CLIENT = "VehicleControlFaultService_client"
TYRE_SERVICE_CLIENT = "TyreService_client"
AVP_SERVICE_SERVER = "AVPService_server"
ACC_SERVICE_SERVER = "ACCService_server"
INTERACTIVE_SERVICE_SERVER = "InteractiveService_server"
REMOTECTRL_SERVICE_SERVER = "RemoteCtrlService_server"
LCA_SERVICE_SERVER = "LCAService_server"
ANPWTI_SERVICE_SERVER = "ANPWTIService_server"
ANPMRC_SERVICE_SERVER = "ANPMRCService_server"
WTIAUTODRIVE_SERVICE_CLIENT = "WTIAutoDriveService_client"
RPAAPA_SERVICE_SERVER = "RPAAPAService_server"
BACU_SERVICE_SERVER = "BACUService_server"
FCTA_SERVICE_SERVER = "FCTAService_server"
RCW_SERVICE_SERVER = "RCWService_server"
AEBR_SERVICE_SERVER = "AEBRService_server"
RCTA_SERVICE_SERVER = "RCTAService_server"
DOW_SERVICE_SERVER = "DOWService_server"
LKA_SERVICE_SERVER = "LKAService_server"
TLA_SERVICE_SERVER = "TLAService_server"
IMU_SERVICE_SERVER = "IMUService_server"
SensorSelfClean_SERVICE_SERVER = "SensorSelfCleanService_server"
ACUFaultInfo_SERVICE_SERVER = "ACUFaultInfoService_server"
FrontBackupCamera_SERVICE_SERVER = "FrontBackupCamera_server"
CMSF_SERVICE_SERVER = "CMSFService_server"
SAS_SERVICE_SERVER = "SASService_server"
MARSPILOTMARSDRIVER_SERVICE_SERVER = "MarsPilotMarsDriverService_server"
AUTOHIGHBEAMCONTROL_SERVICE_SERVER = "AutoHighBeamControlService_server"
AUTOTURNLAMPCTRL_SERVICE_SERVER = "AutoTurnLampCtrlService_server"
AEB_SERVICE_SERVER = "AEBService_server"
FCW_SERVICE_SERVER = "FCWService_server"
AutoGearShift_SERVICE_SERVER = "AutoGearShiftService_server"
WIRELESScharging_CLIENT = "WirelessPhoneChargingService_client"
CONDITIONCHECK_SERVICE_CLIENT = "ConditionCheckService_client"
VEHICLEMODESERVICE_CLIENT = "VehicleModeService_client"
BOONET_SERVICE_CLIENT = "BonnetService_client"
RTCALARM_SERVICE_CLIENT = "RtcAlarmService_client"
WINDOWS_APP_SERVICE_CLIENT = "WindowAppService_client"
TAILWING_SERVICE_CLIENT = "TailWingService_client"
TWEETER_SERVICE_CLIENT = "TweeterService_client"
PEDAL_SERVICE_CLIENT = "PedalService_client"
CARCONFIG_SERVICE_CLIENT = "CarConfigService_client"
BLUETOOTH_SERVICE_CLIENT = "BlueToothService_client"
INTERCOMM_SERVICE_CLIENT = "InterCommService_client_BGM_InterCommService"
LOWVLORAGE_SERVICE_CLIENT = "LowVoltageService_client"
VEHICLETIME_SERVICE_CLIENT = "VehicleTimeService_client"
NETSTAT_SERVICE_CLIENT = "NetStatService_client"
NAVI_SERVICE_CLIENT = "NaviService_client"
ACCOUNT_SERVICE_CLIENT = "AccountService_client"
DRIVINGASSIST_SERVICE_CLIENT = "DrivingAssistService_client"
REMOTECTRL_SERVICE_CLIENT = "RemoteCtrlService_client"
RPAAPA_SERVICE_CLIENT = "RPAAPAService_client"
ACC_SERVICE_CLIENT = "ACCService_client"
PASSIVESAFETY_SERVICE_CLIENT = __import__("os").environ.get('XAT_CREDENTIAL_ECU__SOA_PARTNER_SRC_PARTNER_CONST_PY_PASSIVESAFETY_SERVICE_CLIENT', "")
ERGONOMICS_SERVICE_CLIENT = "ErgonomicsService_client"
GB32960_SERVICE_CLIENT = "GB32960Service_client"
CALL_SERVICE_CLIENT = "CallService_client"
VEHICLEBASELINE_SERVICE_CLIENT = "VehicleBaselineService_client"
OBTDIAG_SERVICE_CLIENT = "ObtDiagService_client"
LOGMASTER_SERVICE_CLIENT = "LogMasterService_client"
HORN_SERVICE_CLIENT = "HornService_client"
V2TROUTING_SERVICE_CLIENT = "V2TRoutingService_client"
FOTAMASTER_SERVICE_CLIENT = "FotaMasterService_client"
FOTAMASTER_SERVICE_SERVER = "FotaMasterService_server"
CCPMASTER_SERVICE_CLIENT = "CCPMasterService_client_CcpMasterService"
ANPMRC_SERVICE_CLIENT = "ANPMRCService_client"
AVP_SERVICE_CLIENT = "AVPService_client"
BLECTRL_SERVICE_CLIENT = "BLECtrlService_client"
RKECTRL_SERVICE_CLIENT = "RKECtrlService_client"
ELKSERVICE_SERVER = "ELKService_server"
GLOVEBOX_SERVICE_CLIENT = "GloveBoxService_client"
HIGHVOLTAGEAPP_SERVICE_CLIENT = "HighVoltageAppService_client"
SUSPENSION_SERVICE_CLIENT = "SuspensionService_client"



