dut_ecu: ["CCUMCUCD", "CCUSOCCD"]
com_mock_ecu: []
gateway_ip: "169.254.19.1"
task_id: 19160
soft_id: 6586
e2e_info: {}

veh_type: "jupiter"
bl_ver: "v_0_4_0"

ecu_mock_cfg:
  ecu_name: "ALL"
  p_n_res: True
  nrc_code: 0x22
  diag_mode: "ALL"
  server_doip_id: 0x1002
  server_ip: "172.20.9.222"

sd_tester_cfg:
  diag_mode: "doip"
  is_via_gateway: False
  ecu_name: "CCUMCUCD"
  dig_bus: "diagnosticcan"
  server_ip: "172.20.9.12"
