-- Generated by scripts/export_postgres_schema.py; do not edit by hand.
-- Fixed schema: ats. Expected ATS tables: 82. Fresh initialization only.
-- One atomic DO statement; no transaction BEGIN/COMMIT commands.
-- Safe inside an admin migration transaction or as one autocommit statement.
-- An existing ats schema raises duplicate_schema before creating any object.
-- No rows, roles, passwords, grants, extensions, or destructive DDL.
-- Python-side defaults remain application-side; only server defaults are DDL.
-- SERIAL/BIGSERIAL create owned sequences in the table's ats schema.

DO $ats_fresh_schema$
BEGIN
    PERFORM pg_catalog.set_config('search_path', 'pg_catalog', true);
    PERFORM pg_catalog.set_config('lock_timeout', '10s', true);

    CREATE SCHEMA ats;

    CREATE TABLE ats.agent_log_cursors (
        id VARCHAR(36) NOT NULL,
        environment_id VARCHAR(36) NOT NULL,
        stream_id VARCHAR(36) NOT NULL,
        through_sequence BIGINT NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.agent_task_logs (
        id VARCHAR(36) NOT NULL,
        environment_id VARCHAR(36) NOT NULL,
        task_id VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        timestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.ai_case_drafts (
        user_id VARCHAR(36) NOT NULL,
        project_id VARCHAR(36) NOT NULL,
        batch_id VARCHAR(36) NOT NULL,
        content JSON NOT NULL,
        source_prompt TEXT NOT NULL,
        status VARCHAR(20) NOT NULL,
        revision INTEGER NOT NULL,
        imported_case_id VARCHAR(36),
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.ai_conversations (
        user_id VARCHAR(36) NOT NULL,
        project_id VARCHAR(36) NOT NULL,
        title VARCHAR(200) NOT NULL,
        messages JSON NOT NULL,
        revision INTEGER NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.ai_model_configs (
        owner_key VARCHAR(50) NOT NULL,
        base_url VARCHAR(500) NOT NULL,
        model VARCHAR(200) NOT NULL,
        api_key_encrypted TEXT,
        timeout_seconds INTEGER NOT NULL,
        enabled BOOLEAN NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_attachments (
        id VARCHAR(36) NOT NULL,
        case_id VARCHAR(36) NOT NULL,
        file_name VARCHAR(255) NOT NULL,
        file_path VARCHAR(500) NOT NULL,
        file_size FLOAT,
        file_type VARCHAR(50),
        upload_time TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        uploaded_by VARCHAR(36),
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_automation_links (
        case_id VARCHAR(36) NOT NULL,
        category VARCHAR(20) NOT NULL,
        target_case_id VARCHAR(36),
        suite_id VARCHAR(36),
        external_ref VARCHAR(500),
        created_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_changes (
        project_id VARCHAR(36) NOT NULL,
        case_id VARCHAR(36) NOT NULL,
        actor_id VARCHAR(36) NOT NULL,
        action VARCHAR(60) NOT NULL,
        detail JSON NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_comments (
        case_id VARCHAR(36) NOT NULL,
        author_id VARCHAR(36) NOT NULL,
        content TEXT NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_follows (
        case_id VARCHAR(36) NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_issue_links (
        case_id VARCHAR(36) NOT NULL,
        issue_id VARCHAR(36) NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_issues (
        project_id VARCHAR(36) NOT NULL,
        kind VARCHAR(20) NOT NULL,
        title VARCHAR(300) NOT NULL,
        description TEXT NOT NULL,
        status VARCHAR(30) NOT NULL,
        external_ref VARCHAR(500),
        created_by VARCHAR(36) NOT NULL,
        updated_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_project_settings (
        project_id VARCHAR(36) NOT NULL,
        auto_resubmit BOOLEAN NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_relations (
        project_id VARCHAR(36) NOT NULL,
        source_case_id VARCHAR(36) NOT NULL,
        target_case_id VARCHAR(36) NOT NULL,
        kind VARCHAR(20) NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_review_comments (
        review_id VARCHAR(36) NOT NULL,
        item_id VARCHAR(36),
        author_id VARCHAR(36) NOT NULL,
        content TEXT NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_review_decisions (
        item_id VARCHAR(36) NOT NULL,
        reviewer_id VARCHAR(36) NOT NULL,
        decision VARCHAR(20) NOT NULL,
        comment TEXT NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_review_events (
        review_id VARCHAR(36) NOT NULL,
        item_id VARCHAR(36),
        actor_id VARCHAR(36) NOT NULL,
        action VARCHAR(40) NOT NULL,
        detail JSON NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_review_follows (
        review_id VARCHAR(36) NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_review_items (
        review_id VARCHAR(36) NOT NULL,
        case_id VARCHAR(36) NOT NULL,
        version_id VARCHAR(36) NOT NULL,
        status VARCHAR(30) NOT NULL,
        reviewer_ids JSON,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_reviews (
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        policy VARCHAR(20) NOT NULL,
        reviewer_ids JSON NOT NULL,
        status VARCHAR(30) NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        description TEXT NOT NULL,
        mode VARCHAR(20) NOT NULL,
        parent_review_id VARCHAR(36),
        start_date DATE,
        end_date DATE,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_saved_views (
        project_id VARCHAR(36) NOT NULL,
        owner_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        filters JSON NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_templates (
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(100) NOT NULL,
        fields JSON NOT NULL,
        defaults JSON NOT NULL,
        is_default BOOLEAN NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.case_versions (
        project_id VARCHAR(36) NOT NULL,
        case_id VARCHAR(36) NOT NULL,
        version INTEGER NOT NULL,
        snapshot JSON NOT NULL,
        reason VARCHAR(500) NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.environments (
        name VARCHAR(100) NOT NULL,
        tags VARCHAR(500),
        remote_work_dir VARCHAR(500),
        token VARCHAR(100),
        reconnect_delay VARCHAR(10) NOT NULL,
        created_by VARCHAR(36),
        updated_by VARCHAR(36),
        node_ip VARCHAR(50),
        os_type VARCHAR(100),
        os_version VARCHAR(100),
        disk_info JSON,
        memory_info JSON,
        cpu_info JSON,
        is_online BOOLEAN NOT NULL,
        last_heartbeat TIMESTAMP WITHOUT TIME ZONE,
        max_concurrent_tasks INTEGER NOT NULL,
        api_url VARCHAR(500),
        web_url VARCHAR(500),
        database_config JSON,
        env_variables JSON,
        description TEXT,
        status BOOLEAN NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.execution_attachments (
        id VARCHAR(36) NOT NULL,
        execution_id VARCHAR(36) NOT NULL,
        file_name VARCHAR(255) NOT NULL,
        file_path VARCHAR(500) NOT NULL,
        file_size FLOAT,
        file_type VARCHAR(50),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.filter_fields (
        project_id VARCHAR(36) NOT NULL,
        field_key VARCHAR(100) NOT NULL,
        field_label VARCHAR(100) NOT NULL,
        field_type VARCHAR(50) NOT NULL,
        operators JSON,
        options JSON,
        sort_order INTEGER,
        is_enabled BOOLEAN,
        is_default BOOLEAN,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.group_report_workspaces (
        run_id VARCHAR(36) NOT NULL,
        name VARCHAR(255),
        deleted BOOLEAN NOT NULL,
        updated_by VARCHAR(36) NOT NULL,
        PRIMARY KEY (run_id)
    );

    CREATE TABLE ats.modules (
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(100) NOT NULL,
        parent_id VARCHAR(36),
        level INTEGER NOT NULL,
        sort_order INTEGER NOT NULL,
        description TEXT,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.native_api_definitions (
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        protocol VARCHAR(50) NOT NULL,
        path VARCHAR(500) NOT NULL,
        module_id VARCHAR(36),
        state VARCHAR(30),
        tags JSON,
        created_by VARCHAR(36),
        parameters JSON NOT NULL,
        revision INTEGER NOT NULL,
        updated_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.native_api_environments (
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        address VARCHAR(500) NOT NULL,
        revision INTEGER NOT NULL,
        updated_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.native_case_configs (
        case_id VARCHAR(36) NOT NULL,
        state VARCHAR(30) NOT NULL,
        environment_id VARCHAR(36),
        api_definition_id VARCHAR(36),
        definition_fingerprint VARCHAR(64),
        parameters JSON NOT NULL,
        revision INTEGER NOT NULL,
        updated_by VARCHAR(36) NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (case_id)
    );

    CREATE TABLE ats.native_request_files (
        project_id VARCHAR(36) NOT NULL,
        file_name VARCHAR(255) NOT NULL,
        content_type VARCHAR(255) NOT NULL,
        byte_length INTEGER NOT NULL,
        sha256 VARCHAR(64) NOT NULL,
        content BYTEA NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        deleted_at TIMESTAMP WITHOUT TIME ZONE,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.notifications (
        id VARCHAR(36) NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        type VARCHAR(50) NOT NULL,
        title VARCHAR(255) NOT NULL,
        content TEXT,
        is_read BOOLEAN NOT NULL,
        related_id VARCHAR(36),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.permissions (
        code VARCHAR(100) NOT NULL,
        name VARCHAR(100) NOT NULL,
        resource VARCHAR(50) NOT NULL,
        action VARCHAR(50) NOT NULL,
        description TEXT,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_case_defects (
        plan_id VARCHAR(36) NOT NULL,
        association_key VARCHAR(120) NOT NULL,
        issue_id VARCHAR(36) NOT NULL,
        case_id VARCHAR(36),
        case_snapshot JSON NOT NULL,
        create_request_id VARCHAR(36),
        create_payload_hash VARCHAR(64),
        active BOOLEAN NOT NULL,
        created_by VARCHAR(36),
        updated_by VARCHAR(36),
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_case_executions (
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        plan_id VARCHAR(36) NOT NULL,
        association_key VARCHAR(120) NOT NULL,
        case_id VARCHAR(36),
        request_id VARCHAR(36) NOT NULL,
        payload_hash VARCHAR(64) NOT NULL,
        executor_id VARCHAR(36),
        executor_name VARCHAR(100) NOT NULL,
        result VARCHAR(20) NOT NULL,
        description TEXT NOT NULL,
        step_results JSON NOT NULL,
        case_snapshot JSON NOT NULL,
        id VARCHAR(36) NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_case_media (
        plan_id VARCHAR(36) NOT NULL,
        uploaded_by VARCHAR(36),
        file_name VARCHAR(255) NOT NULL,
        file_size INTEGER NOT NULL,
        mime_type VARCHAR(50) NOT NULL,
        content BYTEA NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_case_media_links (
        execution_id VARCHAR(36) NOT NULL,
        media_id VARCHAR(36) NOT NULL,
        PRIMARY KEY (execution_id, media_id)
    );

    CREATE TABLE ats.plan_case_relations (
        id VARCHAR(36) NOT NULL,
        plan_id VARCHAR(36) NOT NULL,
        case_id VARCHAR(36) NOT NULL,
        collection_id VARCHAR(36),
        assigned_to VARCHAR(36),
        execution_order INTEGER NOT NULL,
        execution_status VARCHAR(50),
        execution_updated_at TIMESTAMP WITH TIME ZONE,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_case_saved_views (
        project_id VARCHAR(36) NOT NULL,
        owner_id VARCHAR(36) NOT NULL,
        category VARCHAR(20) NOT NULL,
        name VARCHAR(255) NOT NULL,
        filters JSON NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_execution_configs (
        plan_id VARCHAR(36) NOT NULL,
        scope VARCHAR(80) NOT NULL,
        category VARCHAR(16) NOT NULL,
        node_id VARCHAR(36),
        config JSON NOT NULL,
        revision INTEGER NOT NULL,
        PRIMARY KEY (plan_id, scope)
    );

    CREATE TABLE ats.plan_follows (
        plan_id VARCHAR(36) NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_group_policies (
        group_id VARCHAR(36) NOT NULL,
        execution_mode VARCHAR(20) NOT NULL,
        stop_on_failure BOOLEAN NOT NULL,
        pass_threshold FLOAT NOT NULL,
        plan_order JSON NOT NULL,
        PRIMARY KEY (group_id)
    );

    CREATE TABLE ats.plan_group_run_children (
        run_id VARCHAR(36) NOT NULL,
        plan_run_id VARCHAR(36) NOT NULL,
        sequence INTEGER NOT NULL,
        PRIMARY KEY (run_id, plan_run_id)
    );

    CREATE TABLE ats.plan_group_runs (
        group_id VARCHAR(36) NOT NULL,
        active_group_id VARCHAR(36),
        project_id VARCHAR(36) NOT NULL,
        group_name VARCHAR(100) NOT NULL,
        executor_id VARCHAR(36) NOT NULL,
        idempotency_key VARCHAR(200),
        status VARCHAR(30) NOT NULL,
        config_snapshot JSON NOT NULL,
        report JSON,
        summary JSON,
        completed_at TIMESTAMP WITH TIME ZONE,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_group_shares (
        run_id VARCHAR(36) NOT NULL,
        token_hash VARCHAR(64) NOT NULL,
        expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        revoked BOOLEAN NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_group_workspaces (
        group_id VARCHAR(36) NOT NULL,
        module_id VARCHAR(36),
        tags JSON NOT NULL,
        archived BOOLEAN NOT NULL,
        PRIMARY KEY (group_id)
    );

    CREATE TABLE ats.plan_groups (
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(100) NOT NULL,
        description TEXT,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_modules (
        project_id VARCHAR(36) NOT NULL,
        parent_id VARCHAR(36),
        name VARCHAR(120) NOT NULL,
        position INTEGER NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_nodes (
        plan_id VARCHAR(36) NOT NULL,
        parent_id VARCHAR(36),
        name VARCHAR(255) NOT NULL,
        node_type VARCHAR(16) NOT NULL,
        category VARCHAR(16) NOT NULL,
        case_id VARCHAR(36),
        suite_id VARCHAR(36),
        assigned_to VARCHAR(36),
        linked_functional_id VARCHAR(36),
        position INTEGER NOT NULL,
        config JSON NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_report_shares (
        run_id VARCHAR(36) NOT NULL,
        token_hash VARCHAR(64) NOT NULL,
        expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        revoked BOOLEAN NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_report_summaries (
        run_id VARCHAR(36) NOT NULL,
        summary JSON NOT NULL,
        updated_by VARCHAR(36) NOT NULL,
        PRIMARY KEY (run_id)
    );

    CREATE TABLE ats.plan_report_workspaces (
        run_id VARCHAR(36) NOT NULL,
        name VARCHAR(255),
        deleted BOOLEAN NOT NULL,
        updated_by VARCHAR(36) NOT NULL,
        PRIMARY KEY (run_id)
    );

    CREATE TABLE ats.plan_resource_pools (
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        environment_ids JSON NOT NULL,
        revision INTEGER NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_run_attachments (
        run_id VARCHAR(36) NOT NULL,
        association_id VARCHAR(80) NOT NULL,
        author_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        mime_type VARCHAR(120) NOT NULL,
        content_base64 TEXT NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_run_comments (
        run_id VARCHAR(36) NOT NULL,
        association_id VARCHAR(80) NOT NULL,
        author_id VARCHAR(36) NOT NULL,
        content TEXT NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_run_items (
        run_id VARCHAR(36) NOT NULL,
        suite_id VARCHAR(36) NOT NULL,
        execution_id VARCHAR(36) NOT NULL,
        environment_id VARCHAR(36) NOT NULL,
        sequence INTEGER NOT NULL,
        status VARCHAR(20) NOT NULL,
        suite_snapshot JSON NOT NULL,
        error_message TEXT,
        delivery_state VARCHAR(30) NOT NULL,
        dispatch_attempted_at TIMESTAMP WITH TIME ZONE,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_runs (
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        plan_id VARCHAR(36) NOT NULL,
        executor_id VARCHAR(36) NOT NULL,
        idempotency_key VARCHAR(180),
        status VARCHAR(20) NOT NULL,
        plan_name VARCHAR(255) NOT NULL,
        config_snapshot JSON NOT NULL,
        case_snapshot JSON NOT NULL,
        manual_results JSON NOT NULL,
        manual_revision INTEGER NOT NULL,
        notes TEXT,
        report JSON,
        started_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        completed_at TIMESTAMP WITH TIME ZONE,
        id VARCHAR(36) NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.plan_settings (
        plan_id VARCHAR(36) NOT NULL,
        group_id VARCHAR(36),
        execution_mode VARCHAR(20) NOT NULL,
        stop_on_failure BOOLEAN NOT NULL,
        pass_threshold FLOAT NOT NULL,
        suite_order JSON NOT NULL,
        PRIMARY KEY (plan_id)
    );

    CREATE TABLE ats.plan_workspaces (
        plan_id VARCHAR(36) NOT NULL,
        module_id VARCHAR(36),
        tags JSON NOT NULL,
        archived BOOLEAN NOT NULL,
        uses_tree BOOLEAN NOT NULL,
        PRIMARY KEY (plan_id)
    );

    CREATE TABLE ats.project_members (
        id VARCHAR(36) NOT NULL,
        project_id VARCHAR(36) NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        role VARCHAR(50) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.project_permissions (
        id VARCHAR(36) NOT NULL,
        project_id VARCHAR(36) NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        permission_id VARCHAR(36) NOT NULL,
        granted_by VARCHAR(36),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.projects (
        name VARCHAR(255) NOT NULL,
        description TEXT,
        owner_id VARCHAR(36) NOT NULL,
        status VARCHAR(50) NOT NULL,
        created_by VARCHAR(36),
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.review_modules (
        project_id VARCHAR(36) NOT NULL,
        parent_id VARCHAR(36),
        name VARCHAR(100) NOT NULL,
        position INTEGER NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.review_workspaces (
        number SERIAL NOT NULL,
        review_id VARCHAR(36) NOT NULL,
        module_id VARCHAR(36),
        tags JSON NOT NULL,
        archived BOOLEAN NOT NULL,
        start_time TIMESTAMP WITHOUT TIME ZONE,
        end_time TIMESTAMP WITHOUT TIME ZONE,
        PRIMARY KEY (number)
    );

    CREATE TABLE ats.role_permissions (
        id VARCHAR(36) NOT NULL,
        role_id VARCHAR(36) NOT NULL,
        permission_id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.roles (
        name VARCHAR(50) NOT NULL,
        display_name VARCHAR(100) NOT NULL,
        description TEXT,
        is_system BOOLEAN NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.script_job_logs (
        id VARCHAR(36) NOT NULL,
        script_job_id VARCHAR(36) NOT NULL,
        execution_id VARCHAR(36) NOT NULL,
        message TEXT NOT NULL,
        timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.script_job_runs (
        execution_id VARCHAR(36) NOT NULL,
        job_id VARCHAR(36) NOT NULL,
        project_id VARCHAR(36) NOT NULL,
        environment_id VARCHAR(36) NOT NULL,
        executor_id VARCHAR(36) NOT NULL,
        request_id VARCHAR(80) NOT NULL,
        config_snapshot JSON NOT NULL,
        delivery_state VARCHAR(20) NOT NULL,
        dispatch_attempted_at TIMESTAMP WITHOUT TIME ZONE,
        dispatch_session_id VARCHAR(36),
        cancel_requested_at TIMESTAMP WITHOUT TIME ZONE,
        result VARCHAR(20),
        exit_code INTEGER,
        duration_seconds FLOAT,
        error_message TEXT,
        log_delivery JSON,
        closed_by VARCHAR(36),
        closed_at TIMESTAMP WITHOUT TIME ZONE,
        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        PRIMARY KEY (execution_id)
    );

    CREATE TABLE ats.script_jobs (
        id VARCHAR(36) NOT NULL,
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        environment_id VARCHAR(36) NOT NULL,
        config JSON NOT NULL,
        revision INTEGER NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        updated_by VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.task_queue (
        id VARCHAR(36) NOT NULL,
        environment_id VARCHAR(36) NOT NULL,
        kind VARCHAR(16) DEFAULT 'suite' NOT NULL,
        suite_id VARCHAR(36),
        script_job_id VARCHAR(36),
        execution_id VARCHAR(36) NOT NULL,
        executor_id VARCHAR(36) NOT NULL,
        status VARCHAR(50) NOT NULL,
        priority INTEGER NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        started_at TIMESTAMP WITH TIME ZONE,
        completed_at TIMESTAMP WITH TIME ZONE,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.task_schedule_runs (
        id VARCHAR(36) NOT NULL,
        schedule_id VARCHAR(36) NOT NULL,
        trigger_key VARCHAR(200) NOT NULL,
        trigger_type VARCHAR(16) NOT NULL,
        scheduled_for TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        executor_id VARCHAR(36) NOT NULL,
        execution_id VARCHAR(36),
        plan_run_id VARCHAR(36),
        group_run_id VARCHAR(36),
        status VARCHAR(20) NOT NULL,
        error_message TEXT,
        delivery_state VARCHAR(20) NOT NULL,
        dispatch_attempted_at TIMESTAMP WITHOUT TIME ZONE,
        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        completed_at TIMESTAMP WITHOUT TIME ZONE,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.task_schedules (
        id VARCHAR(36) NOT NULL,
        project_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        target_type VARCHAR(16) NOT NULL,
        target_id VARCHAR(36) NOT NULL,
        cron_expression VARCHAR(100),
        timezone VARCHAR(64) NOT NULL,
        enabled BOOLEAN NOT NULL,
        next_run_at TIMESTAMP WITHOUT TIME ZONE,
        last_run_at TIMESTAMP WITHOUT TIME ZONE,
        created_by VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.test_cases (
        project_id VARCHAR(36) NOT NULL,
        module_id VARCHAR(36),
        case_code VARCHAR(100) NOT NULL,
        name VARCHAR(500) NOT NULL,
        type VARCHAR(50) NOT NULL,
        priority VARCHAR(20) NOT NULL,
        precondition TEXT,
        case_edit_type VARCHAR(10) DEFAULT 'STEP' NOT NULL,
        text_description TEXT,
        expected_result TEXT,
        description TEXT,
        steps JSON NOT NULL,
        requirement_ref VARCHAR(255),
        module_path VARCHAR(500),
        level VARCHAR(20),
        executor_id VARCHAR(36),
        tags JSON,
        status VARCHAR(50) NOT NULL,
        is_automated BOOLEAN NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        updated_by VARCHAR(36),
        deleted_at TIMESTAMP WITH TIME ZONE,
        deleted_by VARCHAR(36),
        template_id VARCHAR(36),
        custom_fields JSON,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.test_executions (
        id VARCHAR(36) NOT NULL,
        plan_id VARCHAR(36),
        case_id VARCHAR(36) NOT NULL,
        executor_id VARCHAR(36) NOT NULL,
        environment_id VARCHAR(36),
        result VARCHAR(50) NOT NULL,
        duration FLOAT,
        notes TEXT,
        error_message TEXT,
        execution_log TEXT,
        executed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.test_plans (
        project_id VARCHAR(36) NOT NULL,
        plan_number VARCHAR(50) NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT,
        owner_id VARCHAR(36) NOT NULL,
        plan_type VARCHAR(50) NOT NULL,
        start_date DATE,
        end_date DATE,
        cron_expression VARCHAR(100),
        environment_config JSON,
        status VARCHAR(50) NOT NULL,
        environment_id VARCHAR(36),
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.test_reports (
        project_id VARCHAR(36),
        plan_id VARCHAR(36),
        report_type VARCHAR(50) NOT NULL,
        report_name VARCHAR(255) NOT NULL,
        start_date DATE,
        end_date DATE,
        report_data JSON,
        summary TEXT,
        created_by VARCHAR(36) NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.test_suite_executions (
        id VARCHAR(36) NOT NULL,
        suite_id VARCHAR(36) NOT NULL,
        case_id VARCHAR(36) NOT NULL,
        environment_id VARCHAR(36) NOT NULL,
        executor_id VARCHAR(36) NOT NULL,
        result VARCHAR(50) NOT NULL,
        duration VARCHAR(20),
        log_output TEXT,
        native_detail JSON,
        error_message TEXT,
        executed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.test_suite_logs (
        id VARCHAR(36) NOT NULL,
        suite_id VARCHAR(36) NOT NULL,
        execution_id VARCHAR(36),
        sequence_number INTEGER,
        message TEXT NOT NULL,
        duration VARCHAR(20),
        timestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.test_suites (
        plan_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT,
        git_enabled VARCHAR(10) NOT NULL,
        git_repo_url VARCHAR(500),
        git_branch VARCHAR(100),
        git_token TEXT,
        environment_id VARCHAR(36) NOT NULL,
        execution_command TEXT NOT NULL,
        case_ids JSON NOT NULL,
        status VARCHAR(50) NOT NULL,
        created_by VARCHAR(36) NOT NULL,
        updated_by VARCHAR(36),
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.user_roles (
        id VARCHAR(36) NOT NULL,
        user_id VARCHAR(36) NOT NULL,
        role_id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE ats.users (
        username VARCHAR(50) NOT NULL,
        email VARCHAR(100) NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        full_name VARCHAR(100),
        phone VARCHAR(20),
        department VARCHAR(100),
        status BOOLEAN NOT NULL,
        id VARCHAR(36) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        PRIMARY KEY (id)
    );

    ALTER TABLE ats.agent_log_cursors ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id) ON DELETE CASCADE;

    ALTER TABLE ats.agent_task_logs ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id) ON DELETE CASCADE;

    ALTER TABLE ats.ai_case_drafts ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id);

    ALTER TABLE ats.ai_case_drafts ADD FOREIGN KEY(user_id) REFERENCES ats.users (id);

    ALTER TABLE ats.ai_conversations ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id);

    ALTER TABLE ats.ai_conversations ADD FOREIGN KEY(user_id) REFERENCES ats.users (id);

    ALTER TABLE ats.ai_model_configs ADD UNIQUE (owner_key);

    ALTER TABLE ats.case_attachments ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_attachments ADD FOREIGN KEY(uploaded_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_automation_links ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_automation_links ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_automation_links ADD FOREIGN KEY(suite_id) REFERENCES ats.test_suites (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_automation_links ADD FOREIGN KEY(target_case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_changes ADD FOREIGN KEY(actor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.case_changes ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_comments ADD FOREIGN KEY(author_id) REFERENCES ats.users (id);

    ALTER TABLE ats.case_comments ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_follows ADD CONSTRAINT uq_case_follow UNIQUE (case_id, user_id);

    ALTER TABLE ats.case_follows ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_follows ADD FOREIGN KEY(user_id) REFERENCES ats.users (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_issue_links ADD CONSTRAINT uq_case_issue_link UNIQUE (case_id, issue_id);

    ALTER TABLE ats.case_issue_links ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_issue_links ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_issue_links ADD FOREIGN KEY(issue_id) REFERENCES ats.case_issues (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_issues ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_issues ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_issues ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_project_settings ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_project_settings ADD UNIQUE (project_id);

    ALTER TABLE ats.case_relations ADD CONSTRAINT uq_case_relation UNIQUE (source_case_id, target_case_id, kind);

    ALTER TABLE ats.case_relations ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_relations ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_relations ADD FOREIGN KEY(source_case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_relations ADD FOREIGN KEY(target_case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_review_comments ADD FOREIGN KEY(author_id) REFERENCES ats.users (id);

    ALTER TABLE ats.case_review_comments ADD FOREIGN KEY(item_id) REFERENCES ats.case_review_items (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_review_comments ADD FOREIGN KEY(review_id) REFERENCES ats.case_reviews (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_review_decisions ADD CONSTRAINT uq_review_vote UNIQUE (item_id, reviewer_id);

    ALTER TABLE ats.case_review_decisions ADD FOREIGN KEY(item_id) REFERENCES ats.case_review_items (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_review_decisions ADD FOREIGN KEY(reviewer_id) REFERENCES ats.users (id);

    ALTER TABLE ats.case_review_events ADD FOREIGN KEY(actor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.case_review_events ADD FOREIGN KEY(review_id) REFERENCES ats.case_reviews (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_review_follows ADD CONSTRAINT uq_review_follow UNIQUE (review_id, user_id);

    ALTER TABLE ats.case_review_follows ADD FOREIGN KEY(review_id) REFERENCES ats.case_reviews (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_review_follows ADD FOREIGN KEY(user_id) REFERENCES ats.users (id);

    ALTER TABLE ats.case_review_items ADD CONSTRAINT uq_review_case UNIQUE (review_id, case_id);

    ALTER TABLE ats.case_review_items ADD FOREIGN KEY(review_id) REFERENCES ats.case_reviews (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_review_items ADD FOREIGN KEY(version_id) REFERENCES ats.case_versions (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_reviews ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_reviews ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_saved_views ADD CONSTRAINT uq_case_saved_view UNIQUE (project_id, owner_id, name);

    ALTER TABLE ats.case_saved_views ADD FOREIGN KEY(owner_id) REFERENCES ats.users (id);

    ALTER TABLE ats.case_saved_views ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_templates ADD CONSTRAINT uq_case_template_name UNIQUE (project_id, name);

    ALTER TABLE ats.case_templates ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_templates ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.case_versions ADD CONSTRAINT uq_case_version UNIQUE (case_id, version);

    ALTER TABLE ats.case_versions ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.case_versions ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.environments ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.environments ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.execution_attachments ADD FOREIGN KEY(execution_id) REFERENCES ats.test_executions (id) ON DELETE CASCADE;

    ALTER TABLE ats.filter_fields ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.group_report_workspaces ADD FOREIGN KEY(run_id) REFERENCES ats.plan_group_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.group_report_workspaces ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.modules ADD FOREIGN KEY(parent_id) REFERENCES ats.modules (id);

    ALTER TABLE ats.modules ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.native_api_definitions ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.native_api_definitions ADD FOREIGN KEY(module_id) REFERENCES ats.modules (id) ON DELETE SET NULL;

    ALTER TABLE ats.native_api_definitions ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.native_api_definitions ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.native_api_environments ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.native_api_environments ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.native_case_configs ADD FOREIGN KEY(api_definition_id) REFERENCES ats.native_api_definitions (id);

    ALTER TABLE ats.native_case_configs ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.native_case_configs ADD FOREIGN KEY(environment_id) REFERENCES ats.native_api_environments (id);

    ALTER TABLE ats.native_case_configs ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.native_request_files ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.native_request_files ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.notifications ADD FOREIGN KEY(user_id) REFERENCES ats.users (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_defects ADD CONSTRAINT uq_plan_case_defect_binding UNIQUE (plan_id, association_key, issue_id);

    ALTER TABLE ats.plan_case_defects ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_case_defects ADD FOREIGN KEY(created_by) REFERENCES ats.users (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_case_defects ADD FOREIGN KEY(issue_id) REFERENCES ats.case_issues (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_defects ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_defects ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_case_executions ADD CONSTRAINT uq_plan_case_execution_request UNIQUE (plan_id, association_key, request_id);

    ALTER TABLE ats.plan_case_executions ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_case_executions ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_case_executions ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_media ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_media ADD FOREIGN KEY(uploaded_by) REFERENCES ats.users (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_case_media_links ADD FOREIGN KEY(execution_id) REFERENCES ats.plan_case_executions (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_media_links ADD FOREIGN KEY(media_id) REFERENCES ats.plan_case_media (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_relations ADD FOREIGN KEY(assigned_to) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_case_relations ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_relations ADD FOREIGN KEY(collection_id) REFERENCES ats.plan_nodes (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_case_relations ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_case_saved_views ADD CONSTRAINT uq_plan_case_view UNIQUE (project_id, owner_id, category, name);

    ALTER TABLE ats.plan_case_saved_views ADD FOREIGN KEY(owner_id) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_case_saved_views ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_execution_configs ADD FOREIGN KEY(node_id) REFERENCES ats.plan_nodes (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_execution_configs ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_follows ADD CONSTRAINT uq_plan_follow_user UNIQUE (plan_id, user_id);

    ALTER TABLE ats.plan_follows ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_follows ADD FOREIGN KEY(user_id) REFERENCES ats.users (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_group_policies ADD FOREIGN KEY(group_id) REFERENCES ats.plan_groups (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_group_run_children ADD FOREIGN KEY(plan_run_id) REFERENCES ats.plan_runs (id);

    ALTER TABLE ats.plan_group_run_children ADD FOREIGN KEY(run_id) REFERENCES ats.plan_group_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_group_runs ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_group_runs ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id);

    ALTER TABLE ats.plan_group_runs ADD UNIQUE (active_group_id);

    ALTER TABLE ats.plan_group_runs ADD UNIQUE (idempotency_key);

    ALTER TABLE ats.plan_group_shares ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_group_shares ADD FOREIGN KEY(run_id) REFERENCES ats.plan_group_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_group_shares ADD UNIQUE (token_hash);

    ALTER TABLE ats.plan_group_workspaces ADD FOREIGN KEY(group_id) REFERENCES ats.plan_groups (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_group_workspaces ADD FOREIGN KEY(module_id) REFERENCES ats.plan_modules (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_groups ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_modules ADD FOREIGN KEY(parent_id) REFERENCES ats.plan_modules (id) ON DELETE RESTRICT;

    ALTER TABLE ats.plan_modules ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_nodes ADD FOREIGN KEY(assigned_to) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_nodes ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE RESTRICT;

    ALTER TABLE ats.plan_nodes ADD FOREIGN KEY(linked_functional_id) REFERENCES ats.plan_nodes (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_nodes ADD FOREIGN KEY(parent_id) REFERENCES ats.plan_nodes (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_nodes ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_nodes ADD FOREIGN KEY(suite_id) REFERENCES ats.test_suites (id) ON DELETE RESTRICT;

    ALTER TABLE ats.plan_report_shares ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_report_shares ADD FOREIGN KEY(run_id) REFERENCES ats.plan_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_report_shares ADD UNIQUE (token_hash);

    ALTER TABLE ats.plan_report_summaries ADD FOREIGN KEY(run_id) REFERENCES ats.plan_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_report_summaries ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_report_workspaces ADD FOREIGN KEY(run_id) REFERENCES ats.plan_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_report_workspaces ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_resource_pools ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_run_attachments ADD FOREIGN KEY(author_id) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_run_attachments ADD FOREIGN KEY(run_id) REFERENCES ats.plan_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_run_comments ADD FOREIGN KEY(author_id) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_run_comments ADD FOREIGN KEY(run_id) REFERENCES ats.plan_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_run_items ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id);

    ALTER TABLE ats.plan_run_items ADD FOREIGN KEY(run_id) REFERENCES ats.plan_runs (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_run_items ADD FOREIGN KEY(suite_id) REFERENCES ats.test_suites (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_run_items ADD UNIQUE (execution_id);

    ALTER TABLE ats.plan_runs ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.plan_runs ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_runs ADD UNIQUE (idempotency_key);

    ALTER TABLE ats.plan_settings ADD FOREIGN KEY(group_id) REFERENCES ats.plan_groups (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_settings ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.plan_workspaces ADD FOREIGN KEY(module_id) REFERENCES ats.plan_modules (id) ON DELETE SET NULL;

    ALTER TABLE ats.plan_workspaces ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.project_members ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.project_members ADD FOREIGN KEY(user_id) REFERENCES ats.users (id) ON DELETE CASCADE;

    ALTER TABLE ats.project_permissions ADD FOREIGN KEY(granted_by) REFERENCES ats.users (id);

    ALTER TABLE ats.project_permissions ADD FOREIGN KEY(permission_id) REFERENCES ats.permissions (id) ON DELETE CASCADE;

    ALTER TABLE ats.project_permissions ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.project_permissions ADD FOREIGN KEY(user_id) REFERENCES ats.users (id) ON DELETE CASCADE;

    ALTER TABLE ats.projects ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.projects ADD FOREIGN KEY(owner_id) REFERENCES ats.users (id);

    ALTER TABLE ats.review_modules ADD CONSTRAINT uq_review_module_name UNIQUE (project_id, parent_id, name);

    ALTER TABLE ats.review_modules ADD FOREIGN KEY(parent_id) REFERENCES ats.review_modules (id) ON DELETE CASCADE;

    ALTER TABLE ats.review_modules ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.review_workspaces ADD FOREIGN KEY(module_id) REFERENCES ats.review_modules (id) ON DELETE RESTRICT;

    ALTER TABLE ats.review_workspaces ADD FOREIGN KEY(review_id) REFERENCES ats.case_reviews (id) ON DELETE CASCADE;

    ALTER TABLE ats.review_workspaces ADD UNIQUE (review_id);

    ALTER TABLE ats.role_permissions ADD FOREIGN KEY(permission_id) REFERENCES ats.permissions (id) ON DELETE CASCADE;

    ALTER TABLE ats.role_permissions ADD FOREIGN KEY(role_id) REFERENCES ats.roles (id) ON DELETE CASCADE;

    ALTER TABLE ats.script_job_logs ADD FOREIGN KEY(execution_id) REFERENCES ats.script_job_runs (execution_id);

    ALTER TABLE ats.script_job_logs ADD FOREIGN KEY(script_job_id) REFERENCES ats.script_jobs (id);

    ALTER TABLE ats.script_job_logs ADD UNIQUE (execution_id);

    ALTER TABLE ats.script_job_runs ADD FOREIGN KEY(closed_by) REFERENCES ats.users (id);

    ALTER TABLE ats.script_job_runs ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id);

    ALTER TABLE ats.script_job_runs ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.script_job_runs ADD FOREIGN KEY(job_id) REFERENCES ats.script_jobs (id);

    ALTER TABLE ats.script_job_runs ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id);

    ALTER TABLE ats.script_job_runs ADD UNIQUE (request_id);

    ALTER TABLE ats.script_jobs ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.script_jobs ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id);

    ALTER TABLE ats.script_jobs ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id);

    ALTER TABLE ats.script_jobs ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.task_queue ADD CONSTRAINT ck_task_queue_target CHECK ((kind = 'suite' AND suite_id IS NOT NULL AND script_job_id IS NULL) OR (kind = 'script' AND suite_id IS NULL AND script_job_id IS NOT NULL));

    ALTER TABLE ats.task_queue ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id) ON DELETE CASCADE;

    ALTER TABLE ats.task_queue ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.task_queue ADD FOREIGN KEY(script_job_id) REFERENCES ats.script_jobs (id);

    ALTER TABLE ats.task_queue ADD FOREIGN KEY(suite_id) REFERENCES ats.test_suites (id) ON DELETE CASCADE;

    ALTER TABLE ats.task_schedule_runs ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.task_schedule_runs ADD FOREIGN KEY(schedule_id) REFERENCES ats.task_schedules (id);

    ALTER TABLE ats.task_schedule_runs ADD UNIQUE (execution_id);

    ALTER TABLE ats.task_schedule_runs ADD UNIQUE (plan_run_id);

    ALTER TABLE ats.task_schedule_runs ADD UNIQUE (trigger_key);

    ALTER TABLE ats.task_schedules ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.task_schedules ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id);

    ALTER TABLE ats.test_cases ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.test_cases ADD FOREIGN KEY(deleted_by) REFERENCES ats.users (id);

    ALTER TABLE ats.test_cases ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.test_cases ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.test_cases ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.test_executions ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.test_executions ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id);

    ALTER TABLE ats.test_executions ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.test_executions ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id);

    ALTER TABLE ats.test_plans ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id);

    ALTER TABLE ats.test_plans ADD FOREIGN KEY(owner_id) REFERENCES ats.users (id);

    ALTER TABLE ats.test_plans ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id) ON DELETE CASCADE;

    ALTER TABLE ats.test_reports ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.test_reports ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id);

    ALTER TABLE ats.test_reports ADD FOREIGN KEY(project_id) REFERENCES ats.projects (id);

    ALTER TABLE ats.test_suite_executions ADD FOREIGN KEY(case_id) REFERENCES ats.test_cases (id) ON DELETE CASCADE;

    ALTER TABLE ats.test_suite_executions ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id);

    ALTER TABLE ats.test_suite_executions ADD FOREIGN KEY(executor_id) REFERENCES ats.users (id);

    ALTER TABLE ats.test_suite_executions ADD FOREIGN KEY(suite_id) REFERENCES ats.test_suites (id) ON DELETE CASCADE;

    ALTER TABLE ats.test_suite_logs ADD FOREIGN KEY(suite_id) REFERENCES ats.test_suites (id) ON DELETE CASCADE;

    ALTER TABLE ats.test_suites ADD FOREIGN KEY(created_by) REFERENCES ats.users (id);

    ALTER TABLE ats.test_suites ADD FOREIGN KEY(environment_id) REFERENCES ats.environments (id);

    ALTER TABLE ats.test_suites ADD FOREIGN KEY(plan_id) REFERENCES ats.test_plans (id) ON DELETE CASCADE;

    ALTER TABLE ats.test_suites ADD FOREIGN KEY(updated_by) REFERENCES ats.users (id);

    ALTER TABLE ats.user_roles ADD FOREIGN KEY(role_id) REFERENCES ats.roles (id) ON DELETE CASCADE;

    ALTER TABLE ats.user_roles ADD FOREIGN KEY(user_id) REFERENCES ats.users (id) ON DELETE CASCADE;

    CREATE INDEX ix_agent_log_cursors_environment_id ON ats.agent_log_cursors (environment_id);

    CREATE INDEX ix_agent_task_logs_environment_id ON ats.agent_task_logs (environment_id);

    CREATE INDEX ix_agent_task_logs_task_id ON ats.agent_task_logs (task_id);

    CREATE INDEX ix_ai_case_drafts_batch_id ON ats.ai_case_drafts (batch_id);

    CREATE INDEX ix_ai_case_drafts_id ON ats.ai_case_drafts (id);

    CREATE INDEX ix_ai_case_drafts_project_id ON ats.ai_case_drafts (project_id);

    CREATE INDEX ix_ai_case_drafts_user_id ON ats.ai_case_drafts (user_id);

    CREATE INDEX ix_ai_conversations_id ON ats.ai_conversations (id);

    CREATE INDEX ix_ai_conversations_project_id ON ats.ai_conversations (project_id);

    CREATE INDEX ix_ai_conversations_user_id ON ats.ai_conversations (user_id);

    CREATE INDEX ix_ai_model_configs_id ON ats.ai_model_configs (id);

    CREATE INDEX ix_case_attachments_case_id ON ats.case_attachments (case_id);

    CREATE INDEX ix_case_automation_links_case_id ON ats.case_automation_links (case_id);

    CREATE INDEX ix_case_automation_links_id ON ats.case_automation_links (id);

    CREATE INDEX ix_case_changes_case_id ON ats.case_changes (case_id);

    CREATE INDEX ix_case_changes_id ON ats.case_changes (id);

    CREATE INDEX ix_case_changes_project_id ON ats.case_changes (project_id);

    CREATE INDEX ix_case_comments_case_id ON ats.case_comments (case_id);

    CREATE INDEX ix_case_comments_id ON ats.case_comments (id);

    CREATE INDEX ix_case_follows_case_id ON ats.case_follows (case_id);

    CREATE INDEX ix_case_follows_id ON ats.case_follows (id);

    CREATE INDEX ix_case_follows_user_id ON ats.case_follows (user_id);

    CREATE INDEX ix_case_issue_links_case_id ON ats.case_issue_links (case_id);

    CREATE INDEX ix_case_issue_links_id ON ats.case_issue_links (id);

    CREATE INDEX ix_case_issue_links_issue_id ON ats.case_issue_links (issue_id);

    CREATE INDEX ix_case_issues_id ON ats.case_issues (id);

    CREATE INDEX ix_case_issues_kind ON ats.case_issues (kind);

    CREATE INDEX ix_case_issues_project_id ON ats.case_issues (project_id);

    CREATE INDEX ix_case_project_settings_id ON ats.case_project_settings (id);

    CREATE INDEX ix_case_relations_id ON ats.case_relations (id);

    CREATE INDEX ix_case_relations_project_id ON ats.case_relations (project_id);

    CREATE INDEX ix_case_relations_source_case_id ON ats.case_relations (source_case_id);

    CREATE INDEX ix_case_relations_target_case_id ON ats.case_relations (target_case_id);

    CREATE INDEX ix_case_review_comments_id ON ats.case_review_comments (id);

    CREATE INDEX ix_case_review_comments_review_id ON ats.case_review_comments (review_id);

    CREATE INDEX ix_case_review_decisions_id ON ats.case_review_decisions (id);

    CREATE INDEX ix_case_review_decisions_item_id ON ats.case_review_decisions (item_id);

    CREATE INDEX ix_case_review_events_id ON ats.case_review_events (id);

    CREATE INDEX ix_case_review_events_review_id ON ats.case_review_events (review_id);

    CREATE INDEX ix_case_review_follows_id ON ats.case_review_follows (id);

    CREATE INDEX ix_case_review_follows_review_id ON ats.case_review_follows (review_id);

    CREATE INDEX ix_case_review_follows_user_id ON ats.case_review_follows (user_id);

    CREATE INDEX ix_case_review_items_case_id ON ats.case_review_items (case_id);

    CREATE INDEX ix_case_review_items_id ON ats.case_review_items (id);

    CREATE INDEX ix_case_review_items_review_id ON ats.case_review_items (review_id);

    CREATE INDEX ix_case_reviews_id ON ats.case_reviews (id);

    CREATE INDEX ix_case_reviews_project_id ON ats.case_reviews (project_id);

    CREATE INDEX ix_case_saved_views_id ON ats.case_saved_views (id);

    CREATE INDEX ix_case_saved_views_owner_id ON ats.case_saved_views (owner_id);

    CREATE INDEX ix_case_saved_views_project_id ON ats.case_saved_views (project_id);

    CREATE INDEX ix_case_templates_id ON ats.case_templates (id);

    CREATE INDEX ix_case_templates_project_id ON ats.case_templates (project_id);

    CREATE INDEX ix_case_versions_case_id ON ats.case_versions (case_id);

    CREATE INDEX ix_case_versions_id ON ats.case_versions (id);

    CREATE INDEX ix_case_versions_project_id ON ats.case_versions (project_id);

    CREATE INDEX ix_environments_id ON ats.environments (id);

    CREATE INDEX ix_environments_is_online ON ats.environments (is_online);

    CREATE INDEX ix_environments_status ON ats.environments (status);

    CREATE INDEX ix_execution_attachments_execution_id ON ats.execution_attachments (execution_id);

    CREATE INDEX ix_filter_fields_id ON ats.filter_fields (id);

    CREATE INDEX ix_filter_fields_project_id ON ats.filter_fields (project_id);

    CREATE INDEX ix_modules_id ON ats.modules (id);

    CREATE INDEX ix_modules_parent_id ON ats.modules (parent_id);

    CREATE INDEX ix_modules_project_id ON ats.modules (project_id);

    CREATE INDEX ix_native_api_definitions_id ON ats.native_api_definitions (id);

    CREATE INDEX ix_native_api_definitions_module_id ON ats.native_api_definitions (module_id);

    CREATE INDEX ix_native_api_definitions_project_id ON ats.native_api_definitions (project_id);

    CREATE INDEX ix_native_api_environments_id ON ats.native_api_environments (id);

    CREATE INDEX ix_native_api_environments_project_id ON ats.native_api_environments (project_id);

    CREATE INDEX ix_native_request_files_deleted_at ON ats.native_request_files (deleted_at);

    CREATE INDEX ix_native_request_files_id ON ats.native_request_files (id);

    CREATE INDEX ix_native_request_files_project_id ON ats.native_request_files (project_id);

    CREATE INDEX ix_notifications_created_at ON ats.notifications (created_at);

    CREATE INDEX ix_notifications_is_read ON ats.notifications (is_read);

    CREATE INDEX ix_notifications_type ON ats.notifications (type);

    CREATE INDEX ix_notifications_user_id ON ats.notifications (user_id);

    CREATE INDEX ix_permissions_id ON ats.permissions (id);

    CREATE INDEX ix_permissions_resource ON ats.permissions (resource);

    CREATE INDEX ix_plan_case_defects_association_key ON ats.plan_case_defects (association_key);

    CREATE INDEX ix_plan_case_defects_create_request_id ON ats.plan_case_defects (create_request_id);

    CREATE INDEX ix_plan_case_defects_id ON ats.plan_case_defects (id);

    CREATE INDEX ix_plan_case_defects_issue_id ON ats.plan_case_defects (issue_id);

    CREATE INDEX ix_plan_case_defects_plan_id ON ats.plan_case_defects (plan_id);

    CREATE INDEX ix_plan_case_executions_association_key ON ats.plan_case_executions (association_key);

    CREATE INDEX ix_plan_case_executions_id ON ats.plan_case_executions (id);

    CREATE INDEX ix_plan_case_executions_plan_id ON ats.plan_case_executions (plan_id);

    CREATE INDEX ix_plan_case_executions_request_id ON ats.plan_case_executions (request_id);

    CREATE INDEX ix_plan_case_media_id ON ats.plan_case_media (id);

    CREATE INDEX ix_plan_case_media_links_media_id ON ats.plan_case_media_links (media_id);

    CREATE INDEX ix_plan_case_media_plan_id ON ats.plan_case_media (plan_id);

    CREATE INDEX ix_plan_case_media_uploaded_by ON ats.plan_case_media (uploaded_by);

    CREATE INDEX ix_plan_case_relations_assigned_to ON ats.plan_case_relations (assigned_to);

    CREATE INDEX ix_plan_case_relations_case_id ON ats.plan_case_relations (case_id);

    CREATE INDEX ix_plan_case_relations_collection_id ON ats.plan_case_relations (collection_id);

    CREATE INDEX ix_plan_case_relations_plan_id ON ats.plan_case_relations (plan_id);

    CREATE INDEX ix_plan_case_saved_views_id ON ats.plan_case_saved_views (id);

    CREATE INDEX ix_plan_case_saved_views_owner_id ON ats.plan_case_saved_views (owner_id);

    CREATE INDEX ix_plan_case_saved_views_project_id ON ats.plan_case_saved_views (project_id);

    CREATE INDEX ix_plan_follows_id ON ats.plan_follows (id);

    CREATE INDEX ix_plan_follows_plan_id ON ats.plan_follows (plan_id);

    CREATE INDEX ix_plan_group_runs_group_id ON ats.plan_group_runs (group_id);

    CREATE INDEX ix_plan_group_runs_id ON ats.plan_group_runs (id);

    CREATE INDEX ix_plan_group_runs_project_id ON ats.plan_group_runs (project_id);

    CREATE INDEX ix_plan_group_runs_status ON ats.plan_group_runs (status);

    CREATE INDEX ix_plan_group_shares_id ON ats.plan_group_shares (id);

    CREATE INDEX ix_plan_group_shares_run_id ON ats.plan_group_shares (run_id);

    CREATE INDEX ix_plan_groups_id ON ats.plan_groups (id);

    CREATE INDEX ix_plan_groups_project_id ON ats.plan_groups (project_id);

    CREATE INDEX ix_plan_modules_id ON ats.plan_modules (id);

    CREATE INDEX ix_plan_modules_project_id ON ats.plan_modules (project_id);

    CREATE INDEX ix_plan_nodes_id ON ats.plan_nodes (id);

    CREATE INDEX ix_plan_nodes_plan_id ON ats.plan_nodes (plan_id);

    CREATE INDEX ix_plan_report_shares_id ON ats.plan_report_shares (id);

    CREATE INDEX ix_plan_report_shares_run_id ON ats.plan_report_shares (run_id);

    CREATE INDEX ix_plan_resource_pools_id ON ats.plan_resource_pools (id);

    CREATE INDEX ix_plan_resource_pools_project_id ON ats.plan_resource_pools (project_id);

    CREATE INDEX ix_plan_run_attachments_id ON ats.plan_run_attachments (id);

    CREATE INDEX ix_plan_run_attachments_run_id ON ats.plan_run_attachments (run_id);

    CREATE INDEX ix_plan_run_comments_id ON ats.plan_run_comments (id);

    CREATE INDEX ix_plan_run_comments_run_id ON ats.plan_run_comments (run_id);

    CREATE INDEX ix_plan_run_items_id ON ats.plan_run_items (id);

    CREATE INDEX ix_plan_run_items_run_id ON ats.plan_run_items (run_id);

    CREATE INDEX ix_plan_run_items_status ON ats.plan_run_items (status);

    CREATE INDEX ix_plan_run_items_suite_id ON ats.plan_run_items (suite_id);

    CREATE INDEX ix_plan_runs_id ON ats.plan_runs (id);

    CREATE INDEX ix_plan_runs_plan_id ON ats.plan_runs (plan_id);

    CREATE INDEX ix_plan_runs_status ON ats.plan_runs (status);

    CREATE INDEX ix_project_members_project_id ON ats.project_members (project_id);

    CREATE INDEX ix_project_members_user_id ON ats.project_members (user_id);

    CREATE INDEX ix_project_permissions_permission_id ON ats.project_permissions (permission_id);

    CREATE INDEX ix_project_permissions_project_id ON ats.project_permissions (project_id);

    CREATE INDEX ix_project_permissions_user_id ON ats.project_permissions (user_id);

    CREATE INDEX ix_projects_id ON ats.projects (id);

    CREATE INDEX ix_projects_owner_id ON ats.projects (owner_id);

    CREATE INDEX ix_projects_status ON ats.projects (status);

    CREATE INDEX ix_review_modules_id ON ats.review_modules (id);

    CREATE INDEX ix_review_modules_project_id ON ats.review_modules (project_id);

    CREATE INDEX ix_review_workspaces_module_id ON ats.review_workspaces (module_id);

    CREATE INDEX ix_role_permissions_permission_id ON ats.role_permissions (permission_id);

    CREATE INDEX ix_role_permissions_role_id ON ats.role_permissions (role_id);

    CREATE INDEX ix_roles_id ON ats.roles (id);

    CREATE INDEX ix_script_job_logs_script_job_id ON ats.script_job_logs (script_job_id);

    CREATE INDEX ix_script_job_runs_job_id ON ats.script_job_runs (job_id);

    CREATE INDEX ix_script_jobs_project_id ON ats.script_jobs (project_id);

    CREATE INDEX ix_task_queue_created_at ON ats.task_queue (created_at);

    CREATE INDEX ix_task_queue_environment_id ON ats.task_queue (environment_id);

    CREATE INDEX ix_task_queue_execution_id ON ats.task_queue (execution_id);

    CREATE INDEX ix_task_queue_id ON ats.task_queue (id);

    CREATE INDEX ix_task_queue_script_job_id ON ats.task_queue (script_job_id);

    CREATE INDEX ix_task_queue_status ON ats.task_queue (status);

    CREATE INDEX ix_task_queue_suite_id ON ats.task_queue (suite_id);

    CREATE INDEX ix_task_schedule_runs_schedule_id ON ats.task_schedule_runs (schedule_id);

    CREATE INDEX ix_task_schedule_runs_status ON ats.task_schedule_runs (status);

    CREATE INDEX ix_task_schedules_due ON ats.task_schedules (enabled, next_run_at);

    CREATE INDEX ix_task_schedules_next_run_at ON ats.task_schedules (next_run_at);

    CREATE INDEX ix_task_schedules_project_id ON ats.task_schedules (project_id);

    CREATE INDEX ix_test_cases_deleted_at ON ats.test_cases (deleted_at);

    CREATE INDEX ix_test_cases_id ON ats.test_cases (id);

    CREATE INDEX ix_test_cases_module_id ON ats.test_cases (module_id);

    CREATE INDEX ix_test_cases_priority ON ats.test_cases (priority);

    CREATE INDEX ix_test_cases_project_id ON ats.test_cases (project_id);

    CREATE INDEX ix_test_cases_status ON ats.test_cases (status);

    CREATE INDEX ix_test_cases_template_id ON ats.test_cases (template_id);

    CREATE INDEX ix_test_cases_type ON ats.test_cases (type);

    CREATE INDEX ix_test_executions_case_id ON ats.test_executions (case_id);

    CREATE INDEX ix_test_executions_executor_id ON ats.test_executions (executor_id);

    CREATE INDEX ix_test_executions_id ON ats.test_executions (id);

    CREATE INDEX ix_test_executions_plan_id ON ats.test_executions (plan_id);

    CREATE INDEX ix_test_executions_result ON ats.test_executions (result);

    CREATE INDEX ix_test_plans_id ON ats.test_plans (id);

    CREATE INDEX ix_test_plans_owner_id ON ats.test_plans (owner_id);

    CREATE INDEX ix_test_plans_project_id ON ats.test_plans (project_id);

    CREATE INDEX ix_test_plans_status ON ats.test_plans (status);

    CREATE INDEX ix_test_reports_id ON ats.test_reports (id);

    CREATE INDEX ix_test_reports_plan_id ON ats.test_reports (plan_id);

    CREATE INDEX ix_test_reports_project_id ON ats.test_reports (project_id);

    CREATE INDEX ix_test_reports_report_type ON ats.test_reports (report_type);

    CREATE INDEX ix_test_suite_executions_case_id ON ats.test_suite_executions (case_id);

    CREATE INDEX ix_test_suite_executions_environment_id ON ats.test_suite_executions (environment_id);

    CREATE INDEX ix_test_suite_executions_executor_id ON ats.test_suite_executions (executor_id);

    CREATE INDEX ix_test_suite_executions_id ON ats.test_suite_executions (id);

    CREATE INDEX ix_test_suite_executions_result ON ats.test_suite_executions (result);

    CREATE INDEX ix_test_suite_executions_suite_id ON ats.test_suite_executions (suite_id);

    CREATE INDEX ix_test_suite_logs_execution_id ON ats.test_suite_logs (execution_id);

    CREATE INDEX ix_test_suite_logs_id ON ats.test_suite_logs (id);

    CREATE INDEX ix_test_suite_logs_sequence_number ON ats.test_suite_logs (sequence_number);

    CREATE INDEX ix_test_suite_logs_suite_id ON ats.test_suite_logs (suite_id);

    CREATE INDEX ix_test_suite_logs_timestamp ON ats.test_suite_logs (timestamp);

    CREATE INDEX ix_test_suites_environment_id ON ats.test_suites (environment_id);

    CREATE INDEX ix_test_suites_id ON ats.test_suites (id);

    CREATE INDEX ix_test_suites_plan_id ON ats.test_suites (plan_id);

    CREATE INDEX ix_test_suites_status ON ats.test_suites (status);

    CREATE INDEX ix_user_roles_role_id ON ats.user_roles (role_id);

    CREATE INDEX ix_user_roles_user_id ON ats.user_roles (user_id);

    CREATE INDEX ix_users_id ON ats.users (id);

    CREATE UNIQUE INDEX ix_environments_token ON ats.environments (token);

    CREATE UNIQUE INDEX ix_permissions_code ON ats.permissions (code);

    CREATE UNIQUE INDEX ix_roles_name ON ats.roles (name);

    CREATE UNIQUE INDEX ix_task_schedule_runs_group_run_id ON ats.task_schedule_runs (group_run_id);

    CREATE UNIQUE INDEX ix_test_cases_case_code ON ats.test_cases (case_code);

    CREATE UNIQUE INDEX ix_test_plans_plan_number ON ats.test_plans (plan_number);

    CREATE UNIQUE INDEX ix_users_email ON ats.users (email);

    CREATE UNIQUE INDEX ix_users_username ON ats.users (username);

    COMMENT ON COLUMN ats.environments.name IS '节点名称';

    COMMENT ON COLUMN ats.environments.tags IS '标签，多个标签用逗号分隔';

    COMMENT ON COLUMN ats.environments.remote_work_dir IS '远程工作目录';

    COMMENT ON COLUMN ats.environments.token IS 'Agent连接Token';

    COMMENT ON COLUMN ats.environments.reconnect_delay IS 'Agent重连延迟时间（秒），默认30秒';

    COMMENT ON COLUMN ats.environments.node_ip IS '节点IP地址';

    COMMENT ON COLUMN ats.environments.os_type IS '操作系统类型，如：Linux, Windows, macOS';

    COMMENT ON COLUMN ats.environments.os_version IS '操作系统版本';

    COMMENT ON COLUMN ats.environments.disk_info IS '磁盘信息，格式：{''total'': ''100GB'', ''used'': ''50GB'', ''free'': ''50GB''}';

    COMMENT ON COLUMN ats.environments.memory_info IS '内存信息，格式：{''total'': ''16GB'', ''used'': ''8GB'', ''free'': ''8GB''}';

    COMMENT ON COLUMN ats.environments.cpu_info IS 'CPU信息，格式：{''model'': ''Intel Core i7'', ''cores'': 8, ''frequency'': ''3.2GHz''}';

    COMMENT ON COLUMN ats.environments.is_online IS '是否在线';

    COMMENT ON COLUMN ats.environments.last_heartbeat IS '最后心跳时间';

    COMMENT ON COLUMN ats.environments.max_concurrent_tasks IS '最大并发任务数量，默认为1';

    COMMENT ON COLUMN ats.environments.status IS '是否启用';

    COMMENT ON COLUMN ats.filter_fields.field_key IS '字段键名，如：id, name, priority';

    COMMENT ON COLUMN ats.filter_fields.field_label IS '字段显示名称';

    COMMENT ON COLUMN ats.filter_fields.field_type IS '字段类型：text, select, number, date, tags, module';

    COMMENT ON COLUMN ats.filter_fields.operators IS '允许的操作符列表，为空则使用默认';

    COMMENT ON COLUMN ats.filter_fields.options IS '选项列表（用于select类型）';

    COMMENT ON COLUMN ats.filter_fields.sort_order IS '排序顺序';

    COMMENT ON COLUMN ats.filter_fields.is_enabled IS '是否启用';

    COMMENT ON COLUMN ats.filter_fields.is_default IS '是否为默认字段';

    COMMENT ON COLUMN ats.task_queue.environment_id IS '环境ID';

    COMMENT ON COLUMN ats.task_queue.suite_id IS '测试套ID';

    COMMENT ON COLUMN ats.task_queue.execution_id IS '执行ID';

    COMMENT ON COLUMN ats.task_queue.executor_id IS '执行人ID';

    COMMENT ON COLUMN ats.task_queue.status IS '状态: pending, running, completed, failed, cancelled';

    COMMENT ON COLUMN ats.task_queue.priority IS '优先级，数字越大优先级越高';

    COMMENT ON COLUMN ats.task_queue.created_at IS '创建时间';

    COMMENT ON COLUMN ats.task_queue.started_at IS '开始执行时间';

    COMMENT ON COLUMN ats.task_queue.completed_at IS '完成时间';

    COMMENT ON COLUMN ats.test_cases.is_automated IS '是否自动化';

    COMMENT ON COLUMN ats.test_suite_executions.result IS '执行结果: passed, failed, error, skipped';

    COMMENT ON COLUMN ats.test_suite_executions.duration IS '执行耗时';

    COMMENT ON COLUMN ats.test_suite_executions.log_output IS '执行日志输出';

    COMMENT ON COLUMN ats.test_suite_executions.native_detail IS '原生HTTP实际请求、响应和断言详情';

    COMMENT ON COLUMN ats.test_suite_executions.error_message IS '错误信息';

    COMMENT ON COLUMN ats.test_suite_logs.execution_id IS '执行ID，用于关联同一次执行的所有日志';

    COMMENT ON COLUMN ats.test_suite_logs.sequence_number IS '序号，从1开始自增';

    COMMENT ON COLUMN ats.test_suite_logs.message IS '日志消息（多行，用换行符分隔）';

    COMMENT ON COLUMN ats.test_suite_logs.duration IS '执行耗时';

    COMMENT ON COLUMN ats.test_suites.name IS '测试套名称';

    COMMENT ON COLUMN ats.test_suites.description IS '测试套描述';

    COMMENT ON COLUMN ats.test_suites.git_enabled IS 'Git配置是否启用: true/false';

    COMMENT ON COLUMN ats.test_suites.git_repo_url IS 'Git代码仓库地址（可选）';

    COMMENT ON COLUMN ats.test_suites.git_branch IS 'Git分支（可选）';

    COMMENT ON COLUMN ats.test_suites.git_token IS 'Git登录Token（可选）';

    COMMENT ON COLUMN ats.test_suites.environment_id IS '执行环境ID';

    COMMENT ON COLUMN ats.test_suites.execution_command IS '执行命令';

    COMMENT ON COLUMN ats.test_suites.case_ids IS '测试用例ID列表';

    COMMENT ON COLUMN ats.test_suites.status IS '状态: pending, running, completed, failed';
END
$ats_fresh_schema$;
