# -*- coding: utf-8 -*-
"""
@File        : can2lin_lin2can_routing_generator.py
@Description : Case generator for CAN-LIN and LIN-CAN routing
@Examples    :
                python can2lin_lin2can_routing_generator.py --project=BGM
                Make sure you have routing object and signal value JSON file ready before executing above command,
                otherwise you will get failed result.
"""
import os
import sys
import argparse
import inspect
import json
import importlib
from xat_ecu.legacy.sdk.dut.cgw.cgw_pcan import CgwPcan
from xat_ecu.legacy.sdk.dut.bgm.bgm_pcan import BgwPcan
from xat_ecu.legacy.sdk.can_lin.pcan_const import PcanConst


ES6_JSON_FILENAME = ""
ES8_JSON_FILENAME = ""

test_file_header = '''# -*- coding: utf-8 -*-

# Module for {vehicle_typeU} CAN/LIN Routing testing
# Based on {json_file_abs_path} files as input
# Generated by the tools/scripts_generator/can2lin_lin2can_routing_generator.py  DO NOT EDIT!

import os
import time
from xat_ecu import reporting as allure
from sdk.interface.pcan import *
from sdk.dut.cgw.cgw_app import CgwApp
from sdk.interface.pcan_const import PcanConst
from project.cgw_oncar.case_helper.test_base import TestBase
from project.cgw_oncar.fixture.oncar import *
from sdk.dut.bgm.bgm_app import BgwApp
from project.bgm.case_helper.test_base import TestBase
from project.bgm.fixture.bgm import *


app = {ecuC}App()
if os.getenv("VEH_TYPE").upper() == "{vehicle_typeU}":
    @pytest.mark.smoke
    @pytest.mark.full
    @pytest.mark.codecheck
    @pytest.mark.can_lin_routing
    class TestCanLinRouting(TestBase):
        def before_class(self, {ecuL}):
            super().before_class(self, {ecuL})
    
            global pcan
            pcan = self.app.pcan
    
            self.app.start_parked()
    
        def after_class(self, {ecuL}):
    
            self.app.vehstate(PcanConst.VehState.PARKED_COMFENA_COMFORT_ENABLED)
            super().after_class(self, {ecuL})
'''

test_def_template = \
    '''\n{indent}def test_from_{source_busL}_{source_sig_nameL}_to_{target_busL}_{target_sig_nameL}_{test_id}(self):
            """
            Source Bus: {source_bus}
            Target Bus: {target_bus}
            Source Message Name: {source_message_name}
            Target Message Name: {target_message_name}
            Source Message ID: {source_msg_id}
            Target Message ID: {target_msg_id}
            Source Signal Name: {source_sig_name}
            Target Signal Name: {target_sig_name}
            """
    '''

test_bodycan_pcan_set_fixed_template = \
    '''\n            # Set source signal value: {source_sig_valueV}
            pcan.{source_sig_nameL}_{source_sig_value}()
            time.sleep(.3)
    '''

test_bodycan_pcan_set_fixed_template_bgm = \
    '''\n            # Set source signal value: {source_sig_valueV}
            pcan.{sdk_name}()
            time.sleep(.3)
    '''

test_bodycan_pcan_set_value_template = \
    '''\n            # Set source signal value: {source_sig_value}   
            pcan.{source_sig_nameL}({source_sig_value})
            time.sleep(.3)
    '''

test_bodycan_pcan_set_value_template_bgm = \
    '''\n            # Set source signal value: {source_sig_value}   
            pcan.{sdk_name}({source_sig_value})
            time.sleep(.3)
    '''

test_bodycan_pcan_check_value_template = \
    '''        # Check target signal value: {target_sig_value}
            pcan.assert_{target_sig_nameL}_is({target_sig_value})
    '''

test_bodycan_pcan_check_value_template_bgm = \
    '''        # Check target signal value: {target_sig_value}
            pcan.{sdk_name}({target_sig_value})
    '''

test_bodycan_pcan_check_fixed_template = \
    '''        # Check target signal value: {target_sig_valueV}
            pcan.assert_{target_sig_nameL}_is_{target_sig_value}()
    '''

test_bodycan_pcan_check_fixed_template_bgm = \
    '''        # Check target signal value: {target_sig_valueV}
            pcan.{sdk_name}()
    '''

def_set_fixed_value_template = \
    '''\n    def {sdk_name}(self):
        """ Generated by script automatic.   DO NOT modify! """
        self.set(self.{dbc_or_ldf}.{source_bus_nameL}.{source_msg_name}, "{source_sig_name}", "{source_sig_value}")
    '''

def_set_unfixed_value_template = \
    '''\n    def {sdk_name}(self, value):
        """ Generated by script automatic.   DO NOT modify! """
        self.set(self.{dbc_or_ldf}.{source_bus_nameL}.{source_msg_name}, "{source_sig_name}", value)
    '''

def_check_fixed_value_template = \
    '''\n    def {sdk_name}(self):
        """ Generated by script automatic.   DO NOT modify! """
        self.check(self.{dbc_or_ldf}.{target_bus_nameL}.{target_msg_name}, "{target_sig_name}", "{target_sig_value}")
    '''
def_check_unfixed_value_template = \
    '''\n    def {sdk_name}(self, value):
        """ Generated by script automatic.   DO NOT modify! """
        self.check(self.{dbc_or_ldf}.{target_bus_nameL}.{target_msg_name}, "{target_sig_name}", value)
    '''

# define the vehicle types here
CGW_VEHICLE_TYPE = ['ES6', 'ES8']
BGM_VEHICLE_TYPE = ['FORCE']
sdk_list = []
sdk_name_list = []


def generate_can2lin_lin2can_case(json_file_dir=None):
    cgw_all_msg_dict = dict()
    bgm_all_msg_dict = dict()

    if json_file_dir:
        filename_list = os.listdir(json_file_dir)
        filename_list.sort()

        for filename in filename_list:
            with open(os.path.join(json_file_dir, filename), 'r') as load_f:
                load_content = json.load(load_f)

            if args.project == "CGW":
                for veh_type in CGW_VEHICLE_TYPE:
                    if filename.startswith(veh_type):
                        cgw_all_msg_dict = get_all_msg_dict(cgw_all_msg_dict, load_content, veh_type, filename)

            elif args.project == "BGM":
                for veh_type in BGM_VEHICLE_TYPE:
                    if filename.startswith(veh_type):
                        bgm_all_msg_dict = get_all_msg_dict(bgm_all_msg_dict, load_content, veh_type, filename)

        write_test_cases_to_file(all_msg=cgw_all_msg_dict)
        write_test_cases_to_file(all_msg=bgm_all_msg_dict)
        # print(cgw_all_msg_dict.get("ES6") == cgw_all_msg_dict.get("ES8"))
        # print("cgw_all_msg_dict ES8: {}".format(cgw_all_msg_dict.get("ES8")))

    else:
        raise Exception("JSON file directory is not specified")


def get_all_msg_dict(all_msg_dict, load_content, veh_type, filename):
    # create dict key if none
    if not all_msg_dict.get(veh_type):
        all_msg_dict[veh_type] = {}

    # judge routing table and signal value
    if 'SIG_VALUE' not in filename:
        if not all_msg_dict[veh_type].get('routing_object'):
            all_msg_dict[veh_type]['routing_object'] = load_content
        elif all_msg_dict[veh_type].get('routing_object'):
            all_msg_dict[veh_type]['routing_object'].extend(load_content)
    else:
        if not all_msg_dict[veh_type].get('signal_value'):
            all_msg_dict[veh_type]['signal_value'] = load_content
        elif all_msg_dict[veh_type].get('signal_value'):
            all_msg_dict[veh_type]['signal_value'] = dict(all_msg_dict[veh_type]['signal_value'], **load_content)

    return all_msg_dict


def write_test_cases_to_file(all_msg=None):
    if all_msg:
        pcan_func_list = None
        if args.project == 'CGW':
            test_file_dir = "{root}/project/cgw_oncar/test/can_lin_routing".format(
                root=os.getcwd().replace('/tools/scripts_generator', ''))
        elif args.project == 'BGM':
            test_file_dir = "{root}/project/bgm/test/diag_nm/can_lin_routing".format(
                root=os.getcwd().replace('/tools/scripts_generator', ''))

            handle_moudle = importlib.import_module("sdk.dut.bgm.bgm_pcan")
            pcan = handle_moudle.BgwPcan
            pcan_func_list = [func for func in dir(pcan) if not func.startswith('_')]
            pcan_path = str(handle_moudle).split("from")[-1].replace("'", "").replace(">", "").lstrip()

        create_test_file_dir_if_absent(test_file_dir)

        indent = " " * 8
        # create test file per vehicle type
        for veh_type in all_msg.keys():
            test_id = 1
            test_file_path = "{dir}/test_{vehicle_type}_can_lin_routing.py".format(dir=test_file_dir,
                                                                                   vehicle_type=veh_type.lower())
            print("Writing to: {}".format(test_file_path))

            with open(test_file_path, "w") as outfile:
                # print test case one by one
                outfile.write(test_file_header.format(
                    json_file_abs_path=dut_path,
                    vehicle_typeU=veh_type,
                    ecuC=args.project.capitalize(),
                    ecuL=args.project.lower().replace('cgw', 'oncar')))

                # Generate test cases for all messages in msg_dict
                # The value of 'routing_object' is a list
                signal_value_dict = all_msg[veh_type]['signal_value']
                # print("signal_value_dict: {}".format(signal_value_dict))

                for each_signal in all_msg[veh_type].get('routing_object'):
                    source_bus_info, target_bus_info = get_source_and_target_bus_info(each_signal)
                    # print("source_bus_info: {}".format(source_bus_info))
                    # print("target_bus_info: {}".format(target_bus_info))

                    for target_bus, target_signal_info in target_bus_info.items():
                        # create each definition part including doc string of test cases
                        outfile.write(test_def_template.format(
                            indent=indent,
                            test_id=str(test_id).zfill(3),
                            source_bus=source_bus_info.get('source_bus'),
                            source_busL=source_bus_info.get('source_bus').replace(' ', '_').lower(),
                            source_message_name=source_bus_info.get('source_msg_name'),
                            source_msg_id=source_bus_info.get('source_msg_id'),
                            source_sig_name=source_bus_info.get('source_sig_name'),
                            source_sig_nameL=source_bus_info.get('source_sig_name').lower(),
                            target_bus=target_bus,
                            target_busL=target_bus.replace(' ', '_').lower(),
                            target_message_name=target_signal_info.get('target_msg_name'),
                            target_msg_id=target_signal_info.get('target_msg_id'),
                            target_sig_name=target_signal_info.get('target_sig_name'),
                            target_sig_nameL=target_signal_info.get('target_sig_name').lower()
                            ))

                        print("test_from_{source_busL}_{source_sig_nameL}_to_{target_busL}_{target_sig_nameL}_{test_id}"
                              .format(source_busL=source_bus_info.get('source_bus').replace(' ', '_').lower(),
                                      source_sig_nameL=source_bus_info.get('source_sig_name').lower(),
                                      target_busL=target_bus.replace(' ', '_').lower(),
                                      target_sig_nameL=target_signal_info.get('target_sig_name').lower(),
                                      test_id=str(test_id).zfill(3)))

                        test_id += 1
                        # create test bodycan pcan set part
                        source_signal_name = source_bus_info.get('source_sig_name')

                        # LIN to CAN routing
                        if 'LIN' in source_bus_info.get('source_bus'):
                            for src_sig_name, sig_value_pair in signal_value_dict.items():
                                if src_sig_name == source_signal_name:
                                    # print("src_sig_name:{}, sig_value_pair:{}".format(src_sig_name, sig_value_pair))
                                    write_source_target_value_to_file(outfile, sig_value_pair, source_bus_info,
                                                                      target_signal_info, target_bus, pcan_func_list)

                        # CAN to LIN routing
                        elif 'CAN' in source_bus_info.get('source_bus'):
                            for src_sig_name, sig_bus_value in signal_value_dict.items():
                                if src_sig_name.upper() == source_signal_name.upper():
                                    # print("src_sig_name:{}, sig_bus_value:{}".format(src_sig_name, sig_bus_value))
                                    for lin_bus_name, sig_value_pair in sig_bus_value.items():
                                        if lin_bus_name.upper() in target_bus.upper():
                                            # print("lin_bus_name:{}".format(lin_bus_name))
                                            # print("sig_value_pair:{}".format(sig_value_pair))
                                            write_source_target_value_to_file(outfile, sig_value_pair, source_bus_info,
                                                                              target_signal_info, target_bus, pcan_func_list)

        if args.project == 'BGM':
            # print(len(list(set(sdk_list))))
            write_sdk_to_pcan_module(list(set(sdk_list)), pcan_path)


def write_source_target_value_to_file(outfile, sig_value_pair, source_bus_info, target_bus_info, target_bus, pcan_func_list):
    # print("target_bus_info: {}".format(target_bus_info))
    for source_sig_value, target_sig_value in sig_value_pair.items():
        # print("source_sig_value: {}".format(source_sig_value))
        # print("target_sig_value: {}".format(target_sig_value))
        if args.project == "CGW":
            if isinstance(source_sig_value, str) and source_sig_value.startswith('v_'):
                outfile.write(test_bodycan_pcan_set_fixed_template.format(
                    source_sig_nameL=source_bus_info.get('source_sig_name').lower(),
                    source_sig_value=source_sig_value.replace('v_', '').lower(),
                    source_sig_valueV=source_sig_value))
            elif isinstance(eval(source_sig_value), int):
                outfile.write(test_bodycan_pcan_set_value_template.format(
                    source_sig_nameL=source_bus_info.get('source_sig_name').lower(),
                    source_sig_value=source_sig_value))

            if isinstance(target_sig_value, str) and target_sig_value.startswith('v_'):
                outfile.write(test_bodycan_pcan_check_fixed_template.format(
                    target_sig_nameL=target_bus_info.get('target_sig_name').lower(),
                    target_sig_value=target_sig_value.replace('v_', '').lower(),
                    target_sig_valueV=target_sig_value))
            elif isinstance(target_sig_value, int):
                outfile.write(test_bodycan_pcan_check_value_template.format(
                    target_sig_nameL=target_bus_info.get('target_sig_name').lower(),
                    target_sig_value=target_sig_value))

        elif args.project == "BGM":
            # set
            if isinstance(source_sig_value, str) and source_sig_value.startswith('v_'):
                sdk_name_source = "{source_bus_nameL}_{source_msg_nameL}_{source_sig_nameL}_{source_sig_value}".format(
                    source_bus_nameL=source_bus_info.get('source_bus')[:-4].lower(),
                    source_msg_nameL=source_bus_info.get('source_msg_name').lower(),
                    source_sig_nameL=source_bus_info.get('source_sig_name').lower(),
                    source_sig_value=source_sig_value.replace('v_', '').lower())
                outfile.write(test_bodycan_pcan_set_fixed_template_bgm.format(
                    source_sig_valueV=source_sig_value,
                    sdk_name=sdk_name_source))
                sdk_func_source = def_set_fixed_value_template.format(
                    sdk_name=sdk_name_source,
                    dbc_or_ldf="dbc" if "CAN" in source_bus_info.get('source_bus') else "ldf",
                    source_bus_nameL=source_bus_info.get('source_bus')[:-4].lower(),
                    source_msg_name=source_bus_info.get('source_msg_name'),
                    source_sig_name=source_bus_info.get('source_sig_name'),
                    source_sig_value=source_sig_value)
            elif isinstance(eval(source_sig_value), int):
                sdk_name_source = "{source_bus_nameL}_{source_msg_nameL}_{source_sig_nameL}".format(
                    source_bus_nameL=source_bus_info.get('source_bus')[:-4].lower(),
                    source_msg_nameL=source_bus_info.get('source_msg_name').lower(),
                    source_sig_nameL=source_bus_info.get('source_sig_name').lower())
                outfile.write(test_bodycan_pcan_set_value_template_bgm.format(
                    source_sig_value=source_sig_value,
                    sdk_name=sdk_name_source))
                sdk_func_source = def_set_unfixed_value_template.format(
                    sdk_name=sdk_name_source,
                    dbc_or_ldf="dbc" if "CAN" in source_bus_info.get('source_bus') else "ldf",
                    source_bus_nameL=source_bus_info.get('source_bus')[:-4].lower(),
                    source_msg_name=source_bus_info.get('source_msg_name'),
                    source_sig_name=source_bus_info.get('source_sig_name'))
            if sdk_name_source not in pcan_func_list:
                sdk_list.append(sdk_func_source)
            # check
            if isinstance(target_sig_value, str) and target_sig_value.startswith('v_'):
                sdk_name_target = "assert_{target_bus_nameL}_{target_msg_nameL}_{target_sig_nameL}_is_{target_sig_value}".format(
                    target_bus_nameL=target_bus.lower()[:-4],
                    target_msg_nameL=target_bus_info.get('target_msg_name').lower(),
                    target_sig_nameL=target_bus_info.get('target_sig_name').lower(),
                    target_sig_value=target_sig_value.replace('v_', '').lower())
                outfile.write(test_bodycan_pcan_check_fixed_template_bgm.format(
                    target_sig_valueV=target_sig_value,
                    sdk_name=sdk_name_target))
                sdk_func_target = def_check_fixed_value_template.format(
                    sdk_name=sdk_name_target,
                    dbc_or_ldf="dbc" if "CAN" in target_bus else "ldf",
                    target_bus_nameL=target_bus.lower()[:-4],
                    target_msg_name=target_bus_info.get('target_msg_name'),
                    target_sig_name=target_bus_info.get('target_sig_name'),
                    target_sig_value=target_sig_value)
            elif isinstance(target_sig_value, int):
                sdk_name_target = "assert_{target_bus_nameL}_{target_msg_nameL}_{target_sig_nameL}_is".format(
                    target_bus_nameL=target_bus.lower()[:-4],
                    target_msg_nameL=target_bus_info.get('target_msg_name').lower(),
                    target_sig_nameL=target_bus_info.get('target_sig_name').lower())
                outfile.write(test_bodycan_pcan_check_value_template_bgm.format(
                    target_sig_value=target_sig_value,
                    sdk_name=sdk_name_target))
                sdk_func_target = def_check_unfixed_value_template.format(
                    sdk_name=sdk_name_target,
                    dbc_or_ldf="dbc" if "CAN" in target_bus else "ldf",
                    target_bus_nameL=target_bus.lower()[:-4],
                    target_msg_name=target_bus_info.get('target_msg_name'),
                    target_sig_name=target_bus_info.get('target_sig_name'))
            if sdk_name_target not in pcan_func_list:
                sdk_list.append(sdk_func_target)


def write_sdk_to_pcan_module(sdk_list, pcan_path):
    with open(pcan_path, "a") as f:
        for sdk_func in sdk_list:
            f.write(sdk_func)


def create_test_file_dir_if_absent(test_file_dir):
    if os.path.isfile(test_file_dir):
        raise RuntimeError('directory "{}" is a file, not a directory!'.format(test_file_dir))

    if not os.path.isdir(test_file_dir):
        # mkdir() is for one layer directory, so we use makedirs() for multi-layer directories
        os.makedirs(test_file_dir)


def get_source_and_target_bus_info(signal=None):
    source_bus_info = dict()
    target_bus_info = dict()

    if signal:
        for key, value in signal.items():
            if "Source CAN Bus" in key or "Source LIN Bus" in key:
                source_bus_info['source_bus'] = value.strip()
            elif "Source Signal Name" in key:
                source_bus_info['source_sig_name'] = value.strip()
            elif "Source Signal Description" in key:
                source_bus_info['source_sig_desp'] = value.strip()
            elif "Source Message Name" in key:
                source_bus_info['source_msg_name'] = value.strip()
            elif "Source Message ID" in key:
                source_bus_info['source_msg_id'] = value.strip()
            elif value.upper() == 'X':
                target_bus_info[key] = {}
                target_bus_name = key.split('_')[0]

                target_bus_info[key]['target_sig_name'] = \
                    signal.get("{} Signal name".format(key)).strip()
                target_bus_info[key]['target_msg_name'] = \
                    signal.get("{} Message name".format(key)).strip()
                target_bus_info[key]['target_msg_id'] = \
                    signal.get("{} Message ID".format(key)).strip()
            else:
                continue
    else:
        raise Exception("Not able to get the source and target bus info due to no signal input")

    return source_bus_info, target_bus_info


if __name__ == "__main__":
    current_dir_path = os.getcwd()
    assert current_dir_path.endswith("scripts_generator"), \
        """
        Please make sure you are under /tools/scripts_generator folder
        """
    argparser = argparse.ArgumentParser()
    argparser.add_argument('--project', choices=("CGW", "BGM"), default="BGM",
                           help='Choose the project that you would like to generate')

    args = argparser.parse_args()
    if args.project == 'CGW':
        can = CgwPcan
    elif args.project == 'BGM':
        can = BgwPcan
    dut_path = os.path.dirname(inspect.getfile(can))

    json_file_abs_dir = os.path.join(dut_path, 'data/routing_table')
    generate_can2lin_lin2can_case(json_file_dir=json_file_abs_dir)
