# -*- coding: utf-8 -*-
"""
@File        : can_protection_signals_generator.py
@Description : Generate the CAN protection signals test cases
@Examples    : python3 can_protection_signals_generator.py --pcan_type=BgwPcan
 
"""

import os
import sys
import argparse
import inspect


from pathlib import Path
from xat_ecu.legacy.sdk.dut.cgw.cgw_pcan import CgwPcan
from xat_ecu.legacy.sdk.dut.bgm.bgm_pcan import BgwPcan
from xat_ecu.legacy.sdk.can_lin.pcan_const import PcanConst
from xat_ecu.legacy.tools.scripts_generator.bus_type_files_parser import BusTypeFilesParser

test_file_header = '''# -*- coding: utf-8 -*-

# Module for {vehverU} {bustypenameU} Routing testing
# Based on {dbcpath} {fileext} files as input
# Generated by the tools/scripts_generator/can_protection_signals_generator.py  DO NOT EDIT!

import os
from sdk.dut.bgm.bgm_app import BgwApp
from sdk.interface.pcan_const import PcanConst
from sdk.driver.can_lib.can_listener import CanListener
from project.bgm.case_helper.test_base import TestBase
from project.bgm.fixture.bgm import *
from project.bgm.case_helper.nm_helper import NMHelper


app = BgwApp()
if os.getenv("VEH_TYPE").upper() == "{vehverU}" and os.getenv("{fileext}_VER") == "{busfilever}":
    @pytest.mark.full
    @pytest.mark.nvos_validation
    @pytest.mark.{bustypenameL}_protections
    class Test{bustypenameC}Protections{vehver}(TestBase):
        def before_class(self, bgm):
            super().before_class(self, bgm)

            global pcan
            pcan = self.app.pcan
            
            self.nm_helper = NMHelper()

            #pcan.vehstate(PcanConst.VehState.PARKED_COMFENA_COMFORT_ENABLED)

        def after_class(self, bgm):
            super().after_class(self, bgm)
'''

test_bodycan_canlistener_template = \
    '''            time_range = pcan.{fileext}.{bustypenameL}.{msgname}.msg_cyc * 20
            {busname}_listener = CanListener(bus_name="{busname}", channel=pcan.{busname}.channel, can_id={msgid})
            {busname}_msgs = {busname}_listener.get_all_messages_in_time_range(time_range=time_range)
'''

cgw_only_test_header_template = \
    '''\n        def test_{bustypename}_protections_{msgid}_{test_id}(self):
            """{bustypename} Message ID: {msgid}
            {ecu_under_test} generated message CRC/Message Counter check
            Destination: {destbuses}
            """
'''

listener_assert_template = \
    '''            logger.info("Checking {busname} bus CRC data")
            assert self.nm_helper.check_crc({busname}_msgs), "{bustypenameL}.{msgname}({msgid}) CRC check FAILED"
            logger.info("Checking {busname} bus Message Counter data")
            assert self.nm_helper.check_msg_counter({busname}_msgs), "{bustypenameL}.{msgname}({msgid}) Message Counter check FAILED"
'''


def generate_can_protections_test_file_helper(car_platform, dut_ver, bus_type_enum, partial_paths, parent_dir):
    # skip LIN protection signals generation due to no requirement
    if bus_type_enum.value == 'lin':
        return
    bus_type_name = bus_type_enum.name.lower()

    bus_dir, car_model, file_version = partial_paths["bus"].split(os.path.sep)[-3:]
    file_ext = bus_dir.split("_")[0]

    if "bgm" in parent_dir:
        test_file_dir = "{root}/test/diag_nm/{bus}_protections".format(root=parent_dir.replace('sdk/dut', 'project'),
                                                                       bus=bus_type_name)
    else:
        raise Exception("PCAN type is not supported in this way")

    bus_file_dir = os.path.join(parent_dir, partial_paths["bus"])

    test_file_path = "{dir}/test_{bus}_protections_{model}_{version}.py".format(
        dir=test_file_dir, bus=bus_type_name, model=car_platform, version=file_version)

    print("Writing to: {}".format(test_file_path))

    bus_type_msgs_obj = BusTypeFilesParser(car_platform, bus_type_enum, bus_file_dir, None)

    all_msgs_for_bus_type_dict = bus_type_msgs_obj.get_all_messages_for_bus_type()
    # print(all_msgs_for_bus_type_dict)

    msg_source = {}
    msg_dest = {}
    msg_cycle_rate = {}
    msg_name = {}
    msg_cgw_only = []
    unwanted_dest_ecus = ("CGW", "Vector__XXX", "BGM")

    for msg_id, msg_obj in all_msgs_for_bus_type_dict.items():
        for k, v in msg_obj.items():
            msg_id = v["Id"]
            dest_bus = v["TxBus"]

            if any(x in v["RxNode"] for x in ['CGW', 'BGM']) and not any(
                    x in v["Originator"] for x in unwanted_dest_ecus):
                msg_source[msg_id] = dest_bus.lower()
                msg_cycle_rate[msg_id] = v["Cycle"]

            if any(x in v["Originator"] for x in ['CGW', 'BGM']):
                if dest_bus not in msg_name:
                    msg_name[dest_bus] = {}

                msg_name[dest_bus][msg_id] = v["Name"]

                if "OBD" not in v['RxNode']:
                    if msg_id not in msg_dest:
                        msg_dest[msg_id] = [dest_bus]
                    else:
                        msg_dest[msg_id].append(dest_bus)

    # Make second pass to find CGW or BGM generated messages
    for msg_id, msg_obj in all_msgs_for_bus_type_dict.items():
        for k, v in msg_obj.items():
            if any(x in v["Originator"] for x in ['CGW', 'BGM']) and v["Id"] not in msg_source and \
                    v["SendType"] == "Cyclic" and v["Id"] not in msg_cgw_only:

                # Check CRC and MsgCntr key word in signal name string
                if all(x in ''.join(list(v['cls_msg_obj_supplement'].keys())) for x in ['CRC', 'MsgCntr']):
                    msg_cgw_only.append(v["Id"])

    # Filter the messages that have BGM as final receiver and with CRC/Msg Counter
    for msg_id, msg_obj in all_msgs_for_bus_type_dict.items():
        for k, v in msg_obj.items():
            if any(x in v["Originator"] for x in ['CGW', 'BGM']) and v["Id"] not in msg_source and \
                    v["SendType"] == "Cyclic" and v["Id"] not in msg_cgw_only:

                # Check CRC and MsgCntr key word in signal name string
                if all(x in ''.join(list(v['cls_msg_obj_supplement'].keys())) for x in ['CRC', 'MsgCntr']):
                    msg_cgw_only.append(v["Id"])


    # Create routing_test_cases.txt file for output

    CgwPcan.create_test_file_dir_if_absent(test_file_dir)

    with open(test_file_path, "w") as outfile:
        # print test case
        outfile.write(test_file_header.format(
            vehver=car_platform.capitalize(),
            vehverU=car_platform.upper(),
            bustypenameU=bus_type_name.upper(),
            bustypenameC=bus_type_name.capitalize(),
            bustypenameL=bus_type_name.lower(),
            dbcpath=bus_file_dir, fileext=file_ext.upper(), busfilever=file_version))

        # Generate test cases for BGM generated messages
        test_id = 1
        for msg_id in sorted(msg_cgw_only):
            # Assign a MessageId for each line
            msg_id_string = str(hex(msg_id))

            # Save the destination buses
            dest_buses = sorted([bus.lower() for bus in msg_dest[msg_id]])
            dest_buses_str = " ".join(dest_buses)

            # print test case
            outfile.write(cgw_only_test_header_template.format(
                bustypename=bus_type_name, msgid=msg_id_string, destbuses=dest_buses_str,
                ecu_under_test=partial_paths['ecu_under_test'], test_id=str(test_id).zfill(3)))

            test_id += 1

            for dest_bus in dest_buses:
                # Use canlistener to capture all msgs in ranged time
                if dest_buses.index(dest_bus) != 0:
                    outfile.write("\n")
                outfile.write(test_bodycan_canlistener_template.format(
                    busname=dest_bus, msgid=msg_id_string, fileext=file_ext, bustypenameL=dest_bus,
                    msgname=msg_name[dest_bus.upper()][msg_id]))

                # check CRC and message counter in defined function
                outfile.write(listener_assert_template.format(
                    bustypenameL=dest_bus, msgid=msg_id_string, busname=dest_bus,
                    msgname=msg_name[dest_bus.upper()][msg_id]))


if __name__ == "__main__":
    path_tail = "compass/tools/scripts_generator"
    scripts_path = Path(os.getcwd()).as_posix()
    assert scripts_path.endswith(path_tail), "Before running this script:\ncd {}".format(path_tail)
    argparser = argparse.ArgumentParser()
    argparser.add_argument(
        '--pcan_type', choices=('BgwPcan', "Default"), help='pcan_type will be used, BgwPcan or other types',
        default="Default")
    args = argparser.parse_args()
    if args.pcan_type == 'Default':
        can = BgwPcan
        dut_path = os.path.dirname(inspect.getfile(can))
    elif args.pcan_type == 'BgwPcan':
        can = BgwPcan
        dut_path = os.path.dirname(inspect.getfile(can))
    can.call_car_platform_dut_ver_bus_type_partial_paths_parent_dir_handler(generate_can_protections_test_file_helper,
                                                                            dut_path)
