# -*- coding: utf-8 -*-
"""
@File        : can_routing_case_generator.py
@Description : This is to auto-generate the oncar CAN routing test cases from DBC files.
@Examples    :

cd tools/scripts_generator
python can_routing_case_generator.py --casepath=project/cgw_oncar/test/can_routing --vehicle_version=ES6 --dbcpath=../../sdk/data/dbc_file/es6/v3_0_4
python can_routing_case_generator.py --casepath=project/cgw_oncar/test/can_routing --vehicle_version=ES6 --dbcpath=../../sdk/data/dbc_file/es6/v3_0_6
python can_routing_case_generator.py --casepath=project/cgw_oncar/test/can_routing --vehicle_version=ES6 --dbcpath=../../sdk/data/dbc_file/es6/v3_0_7

python can_routing_case_generator.py --casepath=project/cgw_oncar/test/can_routing --vehicle_version=ES8 --dbcpath=../../sdk/data/dbc_file/es8/v7_5_4
python can_routing_case_generator.py --casepath=project/cgw_oncar/test/can_routing --vehicle_version=ES8 --dbcpath=../../sdk/data/dbc_file/es8/v7_5_6
python can_routing_case_generator.py --casepath=project/cgw_oncar/test/can_routing --vehicle_version=ES8 --dbcpath=../../sdk/data/dbc_file/es8/v7_5_7

"""

import os
import sys
import glob
import argparse


from xat_ecu.legacy.sdk.can_lin.pcan_const import PcanConst
from xat_ecu.legacy.tools.scripts_generator.bus_type_files_parser import BusTypeFilesParser

test_header = """# -*- coding: utf-8 -*-

# Module for {vehver} CAN Routing testing
# Based on {dbcpath} DBC files as input
# Generated by the tools/scripts_generator/can_routing_case_generator.py  DO NOT EDIT!

import os
import inspect
self.cgw.
from sdk.driver.can_lib.can_listener import CanListener
from project.cgw_oncar.case_helper.parse_tb_config import ParseTBConfig

from project.cgw_oncar.fixture.oncar import *


cgw = CgwApp()
if os.getenv('VEH_TYPE').upper() == '{vehver}' and os.getenv('DBC_VER') == '{dbcver}':
    @pytest.mark.smoke
    class TestCanRouting{vehver}:
        def before_class(self, oncar):
            logger.info(inspect.stack()[0].function + ' start!')

            self.tbcfg = ParseTBConfig(oncar['tbcfg']).get_yaml()
            can_lin_channels_info = {{"can": self.tbcfg["can_bus"], "lin": self.tbcfg["lin_bus"]}}

            self.cgw_app = CgwApp(can_lin_channels_info=can_lin_channels_info, veh_type=oncar['vehtype'])
            self.cgw_app.can.start_all_cyclic_msg()
            self.cmd = self.cgw_app.cmd

            cmd.start_parked()

        def after_class(self, oncar):
            logger.info(inspect.stack()[0].function + ' start!')
            self.cgw_app.can.stop_all_cyclic_msgs()

"""


def generate_router_test_case(dbcpath, vehicle_version, case_file_path):
    full_dbcpath = os.path.join(dbcpath, '*_{}*.dbc'.format(vehicle_version))

    try:
        print('full_dbcpath:{}'.format(full_dbcpath))
        dbc_files = glob.glob(full_dbcpath)
        print('Loading below DBC files to generate CAN routing test cases...')

        for file in dbc_files:
            print(file)
    except FileNotFoundError:
        print('Error, path does not exist: {}'.format(full_dbcpath))
        sys.exit(1)

    dbc_ver = dbcpath.split('/')[-1]
    base_dir = os.path.abspath(os.path.join(os.getcwd(), "../.."))
    base_path = os.path.join(base_dir, case_file_path)

    if not os.path.exists(base_path):
        os.mkdir(base_path)

    msg_source = {}
    msg_destination = {}
    msg_cycle_rate = {}
    msg_cgw_only = []

    # Make first pass thru all DBC files
    bus_type_msgs_obj = BusTypeFilesParser(PcanConst.BusType.CAN, bus_file_ext_dir=dbcpath)

    all_bus_msgs_for_bus_type = bus_type_msgs_obj.get_all_messages_for_bus_type()

    for msg_id, msg_obj in all_bus_msgs_for_bus_type.items():
        if 'CGW' not in msg_obj['Originator'] and \
                'Vector__XXX' not in msg_obj['Originator'] and 'CGW' in msg_obj['RxNode']:
            msg_source[msg_obj['Id']] = msg_obj['TxBus'].lower()
            msg_cycle_rate[msg_obj['Id']] = msg_obj['Cycle']

        if 'CGW' in msg_obj['Originator']:
            if "OBD" not in msg_obj['RxNode']:
                if msg_obj['Id'] not in msg_destination:
                    msg_destination[msg_obj['Id']] = [msg_obj['TxBus']]
                else:
                    msg_destination[msg_obj['Id']].append(msg_obj['TxBus'])

    # Make second pass to find CGW generated messages
    for msg_id, msg_obj in all_bus_msgs_for_bus_type.items():
        if 'CGW' in msg_obj['Originator'] and msg_obj['Id'] not in msg_source and msg_obj['SendType'] == 'Cyclic' and \
                msg_obj['Id'] not in msg_cgw_only:
            msg_cgw_only.append(msg_obj['Id'])

    # Create routing_test_cases.txt file for output
    out = open(os.path.join(base_path, "test_can_routing_{}_{}.py".format(
        vehicle_version.lower(), dbc_ver)), "w")

    out.write(test_header.format(vehver=vehicle_version, dbcpath=dbcpath, dbcver=dbc_ver))

    # Generate test cases for all messages in msg_source
    for msg_id, source_bus in sorted(msg_source.items()):
        if msg_id in msg_destination:
            # Assign a MessageId for each line
            msg_id_string = str(hex(msg_id))

            # Save the destination buses
            destination_buses = [bus.lower() for bus in msg_destination[msg_id]]

            # print test case
            out.write('        def test_can_' + msg_id_string + '(self):\n')
            out.write('            """CAN Message ID: {}\n'.format(msg_id_string))
            out.write('            Source: {}\n'.format(source_bus))
            out.write('            Destination: ')

            for destination_bus in destination_buses:
                out.write('{} '.format(destination_bus))
            out.write('\n            """\n')

            if msg_cycle_rate[msg_id] == 0:
                for destination_bus in destination_buses:
                    out.write(
                        '            {}_listener = CanListener(bus_name=\'{}\', '
                        'channel=self.cgw_app.can.{}.channel, can_id={})\n'.format(
                            destination_bus, destination_bus, destination_bus, msg_id_string))
                out.write(
                    '            self.cgw_app.can.{}.write_single_msg(can_id={}, '
                    'data=[0, 0, 0, 0, 0, 0, 0, 0])\n'.format(source_bus, msg_id_string))
                for destination_bus in destination_buses:
                    out.write('            {}_msg = {}_listener.get_msg_with_can_id(can_id={}, timeout=2)\n'.format(
                        destination_bus, destination_bus, msg_id_string))
                for destination_bus in destination_buses:
                    out.write('            {}_listener.close()\n'.format(destination_bus))
            else:
                for destination_bus in destination_buses:
                    out.write(
                        '            {}_msg = self.cgw_app.can.{}.read_single_msg(can_id={}, '
                        'wait=self.cgw_app.can.const.BUS_DELAY_NODELAY, timeout=5)\n'.format(
                            destination_bus, destination_bus, msg_id_string))
            for destination_bus in destination_buses:
                out.write('            assert {}_msg.arbitration_id == {}\n'.format(destination_bus, msg_id_string))
            out.write('\n')
    
    # Generate test cases for CGW generated messages
    for msg_id in sorted(msg_cgw_only):
        # Assign a MessageId for each line
        msg_id_string = str(hex(msg_id))

        # Save the destination buses
        destination_buses = [bus.lower() for bus in msg_destination[msg_id]]

        # print test case
        out.write('        def test_can_' + msg_id_string + '(self):\n')
        out.write('            """CAN Message ID: {}\n'.format(msg_id_string))
        out.write('            CGW generated message\n')
        out.write('            Destination: ')

        for destination_bus in destination_buses:
            out.write('{} '.format(destination_bus))
        out.write('\n            """\n')

        for destination_bus in destination_buses:
            out.write(
                '            {}_msg = self.cgw_app.can.{}.read_single_msg(can_id={}, '
                'wait=self.cgw_app.can.const.BUS_DELAY_NODELAY, timeout=5)\n'.format(
                    destination_bus, destination_bus, msg_id_string))
        for destination_bus in destination_buses:
            out.write('            assert {}_msg.arbitration_id == {}\n'.format(destination_bus, msg_id_string))
        out.write('\n')

    out.close()


if __name__ == "__main__":
    argparser = argparse.ArgumentParser()
    argparser.add_argument('--dbcpath', help='Path to DBC files')
    argparser.add_argument(
        '--vehicle_version', choices=('ES8', 'ES6', 'ES8+6'), help='Vehicle version of DBC files use.')
    argparser.add_argument('--casepath', help='Path for generated test case file')
    args = argparser.parse_args()
    generate_router_test_case(args.dbcpath, args.vehicle_version, args.casepath)
