#
# This script relies upon changes made in class SocketCan and in class Lin,
# so if back-porting this script to Alpha2, those changes will need to be brought along as well.
#
import os
import sys
import argparse
import inspect


from pathlib import Path
from xat_ecu.legacy.sdk.dut.cgw.cgw_pcan import CgwPcan
from xat_ecu.legacy.sdk.dut.bgm.bgm_pcan import BgwPcan
from xat_ecu.legacy.sdk.can_lin.pcan_const import PcanConst
from xat_ecu.legacy.tools.scripts_generator.bus_type_files_parser import BusTypeFilesParser

test_file_header = '''# -*- coding: utf-8 -*-

# Module for {vehverU} {bustypenameU} Routing testing
# Based on {dbcpath} {fileext} files as input
# Generated by the tools/scripts_generator/can_routing_case_generator.py  DO NOT EDIT!

import os
from sdk.dut.cgw.cgw_app import CgwApp
from sdk.interface.pcan_const import PcanConst
from sdk.driver.can_lib.can_listener import CanListener
from project.cgw_oncar.case_helper.test_base import TestBase
from project.cgw_oncar.fixture.oncar import *


cgw = CgwApp()
if os.getenv("VEH_TYPE").upper() == "{vehverU}" and os.getenv("{fileext}_VER") == "{busfilever}":
    @pytest.mark.smoke
    @pytest.mark.full
    @pytest.mark.codecheck
    @pytest.mark.{bustypenameL}_routing
    class Test{bustypenameC}Routing{vehver}(TestBase):
        def before_class(self, oncar):
            super().before_class(self, oncar)

            global pcan
            pcan = self.app.pcan

            self.app.start_parked()

        def after_class(self, oncar):

            self.app.vehstate(PcanConst.VehState.PARKED_COMFENA_COMFORT_ENABLED)
            super().after_class(self, oncar)
'''

test_def_template = \
    '''\n        def test_{bustypenameL}_{msgid}_{test_id}(self):
            """{bustypenameU} Message ID: {msgid}
            Source: {srcbus}
            Destination: {destbuses}
            """
'''

test_bodycan_canlistener_template = \
    '''            {busname}_listener = CanListener(bus_name="{busname}", channel=pcan.{busname}.channel, can_id={msgid})
'''

test_bodycan_msg_template = \
    '''            msg_{bustypenameL}_{msgid} = pcan.get_captured_msg_using_msg_signals_obj(pcan.{fileext}.{bustypenameL}.{msgname})
            assert msg_{bustypenameL}_{msgid}.arbitration_id == {msgid}, "{bustypenameL}.{msgname}({msgid}) not present on {busname} bus FAIL"
'''

cgw_only_test_header_template = \
    '''\n        def test_{bustypename}_{msgid}_{test_id}(self):
            """{bustypename} Message ID: {msgid}
            {ecu_under_test} generated message
            Destination: {destbuses}
            """
'''

listener_assert_template = \
    '''            assert msg_{bustypenameL}_{msgid}.arbitration_id == {msgid}, "{bustypenameL}.{msgname}({msgid}) not present on {busname} bus FAIL"
'''


def generate_bus_routing_test_file_helper(car_platform, cgw_ver, bus_type_enum, partial_paths, parent_dir):
    bus_type_name = bus_type_enum.name.lower()

    bus_dir, car_model, file_version = partial_paths["bus"].split(os.path.sep)[-3:]

    file_ext = bus_dir.split("_")[0]

    # it just adapt old/new framework here.
    # In the feature, test_file_dir need to concern different ecus.
    if "bgm" in parent_dir:
        test_file_dir = "{root}/test/diag_nm/{bus}_routing".format(root=parent_dir.replace('sdk/dut', 'project'),
                                                                   bus=bus_type_name)
    elif "cgw" in parent_dir:
        test_file_dir = "{root}/project/cgw_oncar/test/{bus}_routing".format(
            root=parent_dir.replace('/sdk/dut/cgw', ''), bus=bus_type_name)
    bus_file_dir = os.path.join(parent_dir, partial_paths["bus"])

    # if bus_type_enum.value == PcanConst.BusType.CAN.value:
    #     test_file_path = "{dir}/test_{bus}_routing_{model}_{version}.py".format(
    #         dir=test_file_dir, bus=bus_type_name, model=car_platform, version=file_version)
    # elif bus_type_enum.value == PcanConst.BusType.LIN.value:
    test_file_path = "{dir}/test_{bus}_routing_{model}_{version}.py".format(
        dir=test_file_dir, bus=bus_type_name, model=car_platform, version=file_version)
    # else:
    #     test_file_path = None

    print("Writing to: {}".format(test_file_path))

    bus_type_msgs_obj = BusTypeFilesParser(car_platform, bus_type_enum, bus_file_dir, None)

    all_msgs_for_bus_type_dict = bus_type_msgs_obj.get_all_messages_for_bus_type()
    # print(all_msgs_for_bus_type_dict)

    msg_source = {}
    msg_dest = {}
    msg_cycle_rate = {}
    msg_name = {}
    msg_cgw_only = []
    unwanted_dest_ecus = ("CGW", "Vector__XXX", "BGM")

    for msg_id, msg_obj in all_msgs_for_bus_type_dict.items():
        for k, v in msg_obj.items():
            msg_id = v["Id"]
            dest_bus = v["TxBus"]

            if any(x in v["RxNode"] for x in ['CGW', 'BGM']) and not any(
                    x in v["Originator"] for x in unwanted_dest_ecus):
                msg_source[msg_id] = dest_bus.lower()
                msg_cycle_rate[msg_id] = v["Cycle"]

            if any(x in v["Originator"] for x in ['CGW', 'BGM']):
                if dest_bus not in msg_name:
                    msg_name[dest_bus] = {}

                msg_name[dest_bus][msg_id] = v["Name"]

                # if "OBD" not in v['RxNode']:
                if msg_id not in msg_dest:
                    msg_dest[msg_id] = [dest_bus]
                else:
                    msg_dest[msg_id].append(dest_bus)

    # Make second pass to find CGW or BGM generated messages
    for msg_id, msg_obj in all_msgs_for_bus_type_dict.items():
        for k, v in msg_obj.items():
            if any(x in v["Originator"] for x in ['CGW', 'BGM']) and v["Id"] not in msg_source and \
                    v["SendType"] == "Cyclic" and v["Id"] not in msg_cgw_only:
                msg_cgw_only.append(v["Id"])

    # Create routing_test_cases.txt file for output
    indent = "        "

    CgwPcan.create_test_file_dir_if_absent(test_file_dir)

    with open(test_file_path, "w") as outfile:
        test_id = 0
        # print test case
        outfile.write(test_file_header.format(
            vehver=car_platform.capitalize(),
            vehverU=car_platform.upper(),
            bustypenameU=bus_type_name.upper(),
            bustypenameC=bus_type_name.capitalize(),
            bustypenameL=bus_type_name.lower(),
            dbcpath=bus_file_dir, fileext=file_ext.upper(), busfilever=file_version))

        # Generate test cases for all messages in msg_source
        for msg_id, source_bus in sorted(msg_source.items()):
            if msg_id in msg_dest:
                # Assign a MessageId for each line
                msg_id_string = str(hex(msg_id))

                # Save the destination buses
                dest_buses = sorted([bus.lower() for bus in msg_dest[msg_id]])
                dest_buses_str = " ".join(dest_buses)

                test_id += 1
                outfile.write(test_def_template.format(
                    bustypenameU=bus_type_name.upper(), bustypenameL=bus_type_name,
                    msgid=msg_id_string,
                    test_id=str(test_id).zfill(3),
                    srcbus=source_bus, destbuses=dest_buses_str))

                if msg_cycle_rate[msg_id] == 0:  # CanListener() is needed in this case.
                    for dest_bus in dest_buses:
                        outfile.write(test_bodycan_canlistener_template.format(
                            busname=dest_bus, msgid=msg_id_string))

                    outfile.write(
                        "    {}pcan.{}.write_single_msg(can_id={}, data=[0, 0, 0, 0, 0, 0, 0, 0])\n".format(
                            indent, source_bus, msg_id_string))

                    for dest_bus in dest_buses:
                        outfile.write("    {}msg_{}_{} = {}_listener.get_msg_with_can_id({}, timeout=2)\n".format(
                            indent, dest_bus, msg_id_string, dest_bus, msg_id_string))

                        outfile.write("    {}{}_listener.close()\n".format(indent, dest_bus))

                        outfile.write(listener_assert_template.format(
                            bustypenameL=dest_bus, msgid=msg_id_string,
                            msgname=msg_name[dest_bus.upper()][msg_id], busname=dest_bus.capitalize()))
                else:
                    for dest_bus in dest_buses:
                        outfile.write(test_bodycan_msg_template.format(
                            bustypenameL=dest_bus, msgid=msg_id_string, fileext=file_ext,
                            msgname=msg_name[dest_bus.upper()][msg_id], busname=dest_bus.capitalize()))

        # Generate test cases for CGW generated messages
        for msg_id in sorted(msg_cgw_only):
            # Assign a MessageId for each line
            msg_id_string = str(hex(msg_id))

            # Save the destination buses
            dest_buses = sorted([bus.lower() for bus in msg_dest[msg_id]])
            dest_buses_str = " ".join(dest_buses)

            # print test case
            test_id += 1
            outfile.write(cgw_only_test_header_template.format(
                bustypename=bus_type_name, msgid=msg_id_string, destbuses=dest_buses_str,
                test_id=str(test_id).zfill(3),
                ecu_under_test=partial_paths['ecu_under_test']))

            for dest_bus in dest_buses:
                outfile.write(test_bodycan_msg_template.format(
                    bustypenameL=dest_bus, msgid=msg_id_string, fileext=file_ext,
                    msgname=msg_name[dest_bus.upper()][msg_id], busname=dest_bus.capitalize()))


if __name__ == "__main__":
    path_tail = "compass/tools/scripts_generator"
    scripts_path = Path(os.getcwd()).as_posix()
    assert scripts_path.endswith(path_tail), "Before running this script:\ncd {}".format(path_tail)
    argparser = argparse.ArgumentParser()
    argparser.add_argument(
        '--pcan_type', choices=('CgwPcan', 'BgwPcan', 'NvosPcan', "Default"), help='pcan_type will be used.',
        default="Default")
    args = argparser.parse_args()
    if args.pcan_type == 'Default':
        can = CgwPcan
        dut_path = os.path.dirname(inspect.getfile(can))
    elif args.pcan_type == 'BgwPcan':
        can = BgwPcan
        dut_path = os.path.dirname(inspect.getfile(can))
    can.call_car_platform_dut_ver_bus_type_partial_paths_parent_dir_handler(generate_bus_routing_test_file_helper,
                                                                            dut_path)
