# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block_head.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62lock_head.proto\x12\rvehiclestatus\"\xa0\x01\n\tBlockHead\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x04\x12\x34\n\x06\x65rrors\x18\x03 \x03(\x0b\x32$.vehiclestatus.BlockHead.ErrorsEntry\x12\x0f\n\x07\x62lockID\x18\x04 \x01(\x05\x1a-\n\x0b\x45rrorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xe5\x02\n\x0bVIDBBlockID\x12\x0e\n\nBlockStart\x10\x00\x12\r\n\x08\x42lockEcu\x10\xf5N\x12\x15\n\x10\x42lockVehicleMode\x10\xf6N\x12\x15\n\x10\x42lockVehicleBody\x10\xf7N\x12\x15\n\x10\x42lockCabinStatus\x10\xf8N\x12\x16\n\x11\x42lockGISAndTravel\x10\xf9N\x12\x17\n\x12\x42lockDrivingStatus\x10\xfaN\x12\x15\n\x10\x42lockEicCharging\x10\xfbN\x12\r\n\x08\x42lockWTI\x10\xfcN\x12\x13\n\x0e\x42lockBusStatus\x10\xfdN\x12\x14\n\x0f\x42lockDeviceInfo\x10\xfeN\x12\x11\n\x0c\x42lockEolData\x10\xffN\x12\x0f\n\nBlockLight\x10\x80O\x12\x0e\n\tBlockGnss\x10\x81O\x12\x0e\n\x08\x42lockAVP\x10\xb9\x94\x01\x12\x14\n\x0f\x42lockGeneralWTI\x10\xcdS\x12\x16\n\x11\x42lockAutoDriveWTI\x10\xceSb\x06proto3')

_VIDBBLOCKID = DESCRIPTOR.enum_types_by_name['VIDBBlockID']
VIDBBlockID = enum_type_wrapper.EnumTypeWrapper(_VIDBBLOCKID)
BlockStart = 0
BlockEcu = 10101
BlockVehicleMode = 10102
BlockVehicleBody = 10103
BlockCabinStatus = 10104
BlockGISAndTravel = 10105
BlockDrivingStatus = 10106
BlockEicCharging = 10107
BlockWTI = 10108
BlockBusStatus = 10109
BlockDeviceInfo = 10110
BlockEolData = 10111
BlockLight = 10112
BlockGnss = 10113
BlockAVP = 19001
BlockGeneralWTI = 10701
BlockAutoDriveWTI = 10702


_BLOCKHEAD = DESCRIPTOR.message_types_by_name['BlockHead']
_BLOCKHEAD_ERRORSENTRY = _BLOCKHEAD.nested_types_by_name['ErrorsEntry']
BlockHead = _reflection.GeneratedProtocolMessageType('BlockHead', (_message.Message,), {

  'ErrorsEntry' : _reflection.GeneratedProtocolMessageType('ErrorsEntry', (_message.Message,), {
    'DESCRIPTOR' : _BLOCKHEAD_ERRORSENTRY,
    '__module__' : 'block_head_pb2'
    # @@protoc_insertion_point(class_scope:vehiclestatus.BlockHead.ErrorsEntry)
    })
  ,
  'DESCRIPTOR' : _BLOCKHEAD,
  '__module__' : 'block_head_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.BlockHead)
  })
_sym_db.RegisterMessage(BlockHead)
_sym_db.RegisterMessage(BlockHead.ErrorsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOCKHEAD_ERRORSENTRY._options = None
  _BLOCKHEAD_ERRORSENTRY._serialized_options = b'8\001'
  _VIDBBLOCKID._serialized_start=199
  _VIDBBLOCKID._serialized_end=556
  _BLOCKHEAD._serialized_start=36
  _BLOCKHEAD._serialized_end=196
  _BLOCKHEAD_ERRORSENTRY._serialized_start=151
  _BLOCKHEAD_ERRORSENTRY._serialized_end=196
# @@protoc_insertion_point(module_scope)
