# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: charging_bluetooth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xat_ecu.legacy.tsp.data.proto.rvs.block_head_pb2 as block__head__pb2
import xat_ecu.legacy.tsp.data.proto.rvs.eic_charging_pb2 as eic__charging__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63harging_bluetooth.proto\x12\rvehiclestatus\x1a\x10\x62lock_head.proto\x1a\x12\x65ic_charging.proto\"\xb9\x01\n\x16\x43hargingBlueToothBlock\x12&\n\x04head\x18\x01 \x01(\x0b\x32\x18.vehiclestatus.BlockHead\x12\x33\n\rpluggerStatus\x18\x02 \x01(\x0e\x32\x1c.vehiclestatus.PluggerStatus\x12\x16\n\x0e\x63hargingLidPos\x18\x03 \x01(\r\x12\x17\n\x0f\x63hargeTargetSoc\x18\x04 \x01(\x02\x12\x11\n\tisConnect\x18\x05 \x01(\x08\x62\x06proto3')



_CHARGINGBLUETOOTHBLOCK = DESCRIPTOR.message_types_by_name['ChargingBlueToothBlock']
ChargingBlueToothBlock = _reflection.GeneratedProtocolMessageType('ChargingBlueToothBlock', (_message.Message,), {
  'DESCRIPTOR' : _CHARGINGBLUETOOTHBLOCK,
  '__module__' : 'charging_bluetooth_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.ChargingBlueToothBlock)
  })
_sym_db.RegisterMessage(ChargingBlueToothBlock)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHARGINGBLUETOOTHBLOCK._serialized_start=82
  _CHARGINGBLUETOOTHBLOCK._serialized_end=267
# @@protoc_insertion_point(module_scope)
