# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xat_ecu.legacy.tsp.data.proto.rvs.common_pb2 as common__pb2
import xat_ecu.legacy.tsp.data.proto.rvs.block_head_pb2 as block__head__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x65vice_info.proto\x12\rvehiclestatus\x1a\x0c\x63ommon.proto\x1a\x10\x62lock_head.proto\"Z\n\x0f\x44\x65viceInfoBlock\x12&\n\x04head\x18\x01 \x01(\x0b\x32\x18.vehiclestatus.BlockHead\x12\x1f\n\x03key\x18\x02 \x01(\x0b\x32\x12.vehiclestatus.Key\"@\n\x03Key\x12\x39\n\x0b\x63onnectInfo\x18\x01 \x03(\x0b\x32$.vehiclestatus.DigitalKeyConnectInfo\"\xa5\x01\n\x15\x44igitalKeyConnectInfo\x12\r\n\x05keyId\x18\x01 \x01(\x0c\x12\'\n\x07keyType\x18\x02 \x01(\x0e\x32\x16.vehiclestatus.KeyType\x12(\n\x0bisConnected\x18\x03 \x01(\x0e\x32\x13.vehiclestatus.Bool\x12*\n\x04zone\x18\x04 \x01(\x0e\x32\x1c.vehiclestatus.ConnectedZone*\xce\x01\n\x07KeyType\x12\r\n\tKtUnknown\x10\x00\x12\r\n\tKtNfcCard\x10\x01\x12\x0c\n\x08KtBleKey\x10\x02\x12\x0f\n\x0bKtBleUwbKey\x10\x03\x12\x10\n\x0cKtTempBleKey\x10\x04\x12\x10\n\x0cKtIcceBleKey\x10\x05\x12\x10\n\x0cKtIcceNfcKey\x10\x06\x12\x15\n\x11KtCccNfcBleUwbKey\x10\x07\x12\x0f\n\x0bKtCccNfcKey\x10\x08\x12\x12\n\x0eKtCccNfcBleKey\x10\t\x12\x14\n\x07KtEmpty\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*\x8e\x02\n\rConnectedZone\x12\x0b\n\x07\x43zZone0\x10\x00\x12\x0b\n\x07\x43zZone1\x10\x01\x12\x0b\n\x07\x43zZone2\x10\x02\x12\x0b\n\x07\x43zZone3\x10\x03\x12\x0b\n\x07\x43zZone4\x10\x04\x12\x0b\n\x07\x43zZone5\x10\x05\x12\x0b\n\x07\x43zZone6\x10\x06\x12\x0b\n\x07\x43zZone7\x10\x07\x12\x0b\n\x07\x43zZone8\x10\x08\x12\x0b\n\x07\x43zZone9\x10\t\x12\x0c\n\x08\x43zZone10\x10\n\x12\x0c\n\x08\x43zZone11\x10\x0b\x12\x0c\n\x08\x43zZone12\x10\x0c\x12\x0c\n\x08\x43zZone13\x10\r\x12\x0c\n\x08\x43zZone14\x10\x0e\x12\x0c\n\x08\x43zZone15\x10\x0f\x12\x11\n\rCzZoneInvalid\x10\x10\x12\x14\n\x07\x43zEmpty\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x62\x06proto3')

_KEYTYPE = DESCRIPTOR.enum_types_by_name['KeyType']
KeyType = enum_type_wrapper.EnumTypeWrapper(_KEYTYPE)
_CONNECTEDZONE = DESCRIPTOR.enum_types_by_name['ConnectedZone']
ConnectedZone = enum_type_wrapper.EnumTypeWrapper(_CONNECTEDZONE)
KtUnknown = 0
KtNfcCard = 1
KtBleKey = 2
KtBleUwbKey = 3
KtTempBleKey = 4
KtIcceBleKey = 5
KtIcceNfcKey = 6
KtCccNfcBleUwbKey = 7
KtCccNfcKey = 8
KtCccNfcBleKey = 9
KtEmpty = -1
CzZone0 = 0
CzZone1 = 1
CzZone2 = 2
CzZone3 = 3
CzZone4 = 4
CzZone5 = 5
CzZone6 = 6
CzZone7 = 7
CzZone8 = 8
CzZone9 = 9
CzZone10 = 10
CzZone11 = 11
CzZone12 = 12
CzZone13 = 13
CzZone14 = 14
CzZone15 = 15
CzZoneInvalid = 16
CzEmpty = -1


_DEVICEINFOBLOCK = DESCRIPTOR.message_types_by_name['DeviceInfoBlock']
_KEY = DESCRIPTOR.message_types_by_name['Key']
_DIGITALKEYCONNECTINFO = DESCRIPTOR.message_types_by_name['DigitalKeyConnectInfo']
DeviceInfoBlock = _reflection.GeneratedProtocolMessageType('DeviceInfoBlock', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINFOBLOCK,
  '__module__' : 'device_info_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.DeviceInfoBlock)
  })
_sym_db.RegisterMessage(DeviceInfoBlock)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'device_info_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.Key)
  })
_sym_db.RegisterMessage(Key)

DigitalKeyConnectInfo = _reflection.GeneratedProtocolMessageType('DigitalKeyConnectInfo', (_message.Message,), {
  'DESCRIPTOR' : _DIGITALKEYCONNECTINFO,
  '__module__' : 'device_info_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.DigitalKeyConnectInfo)
  })
_sym_db.RegisterMessage(DigitalKeyConnectInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYTYPE._serialized_start=395
  _KEYTYPE._serialized_end=601
  _CONNECTEDZONE._serialized_start=604
  _CONNECTEDZONE._serialized_end=874
  _DEVICEINFOBLOCK._serialized_start=68
  _DEVICEINFOBLOCK._serialized_end=158
  _KEY._serialized_start=160
  _KEY._serialized_end=224
  _DIGITALKEYCONNECTINFO._serialized_start=227
  _DIGITALKEYCONNECTINFO._serialized_end=392
# @@protoc_insertion_point(module_scope)
