# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xat_ecu.legacy.tsp.data.proto.rvs.block_head_pb2 as block__head__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tecu.proto\x12\rvehiclestatus\x1a\x10\x62lock_head.proto\"\x86\x01\n\x08\x45\x63uBlock\x12&\n\x04head\x18\x01 \x01(\x0b\x32\x18.vehiclestatus.BlockHead\x12-\n\necuVersion\x18\x02 \x03(\x0b\x32\x19.vehiclestatus.EcuVersion\x12\x10\n\x08\x62\x61seline\x18\x03 \x01(\t\x12\x11\n\tcdcModule\x18\x04 \x01(\t\"H\n\nEcuVersion\x12\x0f\n\x07\x65\x63uName\x18\x01 \x01(\t\x12\x0c\n\x04hwPn\x18\x02 \x01(\t\x12\x0c\n\x04swPn\x18\x03 \x01(\t\x12\r\n\x05\x65\x63uId\x18\x04 \x01(\tb\x06proto3')



_ECUBLOCK = DESCRIPTOR.message_types_by_name['EcuBlock']
_ECUVERSION = DESCRIPTOR.message_types_by_name['EcuVersion']
EcuBlock = _reflection.GeneratedProtocolMessageType('EcuBlock', (_message.Message,), {
  'DESCRIPTOR' : _ECUBLOCK,
  '__module__' : 'ecu_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.EcuBlock)
  })
_sym_db.RegisterMessage(EcuBlock)

EcuVersion = _reflection.GeneratedProtocolMessageType('EcuVersion', (_message.Message,), {
  'DESCRIPTOR' : _ECUVERSION,
  '__module__' : 'ecu_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.EcuVersion)
  })
_sym_db.RegisterMessage(EcuVersion)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ECUBLOCK._serialized_start=47
  _ECUBLOCK._serialized_end=181
  _ECUVERSION._serialized_start=183
  _ECUVERSION._serialized_end=255
# @@protoc_insertion_point(module_scope)
