# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xat_ecu.legacy.tsp.data.proto.rvs.block_head_pb2 as block__head__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\teol.proto\x12\rvehiclestatus\x1a\x10\x62lock_head.proto\"\xaa\x01\n\x0c\x45OLDataBlock\x12&\n\x04head\x18\x01 \x01(\x0b\x32\x18.vehiclestatus.BlockHead\x12%\n\x04\x62ncm\x18\x02 \x01(\x0b\x32\x17.vehiclestatus.BNCMInfo\x12%\n\x04tcam\x18\x03 \x01(\x0b\x32\x17.vehiclestatus.TCAMInfo\x12$\n\x03\x65tc\x18\x04 \x01(\x0b\x32\x17.vehiclestatus.ETCMInfo\"E\n\x08\x42NCMInfo\x12\n\n\x02sn\x18\x01 \x01(\t\x12\x0c\n\x04seId\x18\x02 \x01(\t\x12\x0b\n\x03mac\x18\x03 \x01(\t\x12\x12\n\nwhiteLists\x18\x04 \x01(\t\"Q\n\x08TCAMInfo\x12\n\n\x02sn\x18\x01 \x01(\t\x12\r\n\x05iccId\x18\x02 \x01(\t\x12\x0c\n\x04imsi\x18\x03 \x01(\t\x12\x0c\n\x04imei\x18\x04 \x01(\t\x12\x0e\n\x06msisdn\x18\x05 \x01(\t\"\x16\n\x08\x45TCMInfo\x12\n\n\x02sn\x18\x01 \x01(\tb\x06proto3')



_EOLDATABLOCK = DESCRIPTOR.message_types_by_name['EOLDataBlock']
_BNCMINFO = DESCRIPTOR.message_types_by_name['BNCMInfo']
_TCAMINFO = DESCRIPTOR.message_types_by_name['TCAMInfo']
_ETCMINFO = DESCRIPTOR.message_types_by_name['ETCMInfo']
EOLDataBlock = _reflection.GeneratedProtocolMessageType('EOLDataBlock', (_message.Message,), {
  'DESCRIPTOR' : _EOLDATABLOCK,
  '__module__' : 'eol_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.EOLDataBlock)
  })
_sym_db.RegisterMessage(EOLDataBlock)

BNCMInfo = _reflection.GeneratedProtocolMessageType('BNCMInfo', (_message.Message,), {
  'DESCRIPTOR' : _BNCMINFO,
  '__module__' : 'eol_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.BNCMInfo)
  })
_sym_db.RegisterMessage(BNCMInfo)

TCAMInfo = _reflection.GeneratedProtocolMessageType('TCAMInfo', (_message.Message,), {
  'DESCRIPTOR' : _TCAMINFO,
  '__module__' : 'eol_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.TCAMInfo)
  })
_sym_db.RegisterMessage(TCAMInfo)

ETCMInfo = _reflection.GeneratedProtocolMessageType('ETCMInfo', (_message.Message,), {
  'DESCRIPTOR' : _ETCMINFO,
  '__module__' : 'eol_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.ETCMInfo)
  })
_sym_db.RegisterMessage(ETCMInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EOLDATABLOCK._serialized_start=47
  _EOLDATABLOCK._serialized_end=217
  _BNCMINFO._serialized_start=219
  _BNCMINFO._serialized_end=288
  _TCAMINFO._serialized_start=290
  _TCAMINFO._serialized_end=371
  _ETCMINFO._serialized_start=373
  _ETCMINFO._serialized_end=395
# @@protoc_insertion_point(module_scope)
