# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnss.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xat_ecu.legacy.tsp.data.proto.rvs.block_head_pb2 as block__head__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngnss.proto\x12\rvehiclestatus\x1a\x10\x62lock_head.proto\"\xda\x01\n\tGNSSBlock\x12&\n\x04head\x18\x01 \x01(\x0b\x32\x18.vehiclestatus.BlockHead\x12(\n\x08position\x18\x02 \x01(\x0b\x32\x16.vehiclestatus.Point3D\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\r\n\x05\x61ngle\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x13\n\x0bprobability\x18\x06 \x01(\x05\x12\x11\n\tlongitude\x18\x07 \x01(\x01\x12\x10\n\x08latitude\x18\x08 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\t \x01(\x01\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x62\x06proto3')



_GNSSBLOCK = DESCRIPTOR.message_types_by_name['GNSSBlock']
_POINT3D = DESCRIPTOR.message_types_by_name['Point3D']
GNSSBlock = _reflection.GeneratedProtocolMessageType('GNSSBlock', (_message.Message,), {
  'DESCRIPTOR' : _GNSSBLOCK,
  '__module__' : 'gnss_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.GNSSBlock)
  })
_sym_db.RegisterMessage(GNSSBlock)

Point3D = _reflection.GeneratedProtocolMessageType('Point3D', (_message.Message,), {
  'DESCRIPTOR' : _POINT3D,
  '__module__' : 'gnss_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.Point3D)
  })
_sym_db.RegisterMessage(Point3D)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GNSSBLOCK._serialized_start=48
  _GNSSBLOCK._serialized_end=266
  _POINT3D._serialized_start=268
  _POINT3D._serialized_end=310
# @@protoc_insertion_point(module_scope)
