# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: light.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import xat_ecu.legacy.tsp.data.proto.rvs.common_pb2 as common__pb2
import xat_ecu.legacy.tsp.data.proto.rvs.block_head_pb2 as block__head__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blight.proto\x12\rvehiclestatus\x1a\x0c\x63ommon.proto\x1a\x10\x62lock_head.proto\"\xfb\x01\n\nLightBlock\x12&\n\x04head\x18\x01 \x01(\x0b\x32\x18.vehiclestatus.BlockHead\x12\'\n\x05light\x18\x02 \x03(\x0b\x32\x18.vehiclestatus.LightInfo\x12\x32\n\nshowActive\x18\x03 \x01(\x0e\x32\x1e.vehiclestatus.LightShowActive\x12\x35\n\x0ehighBeamStatus\x18\x04 \x01(\x0e\x32\x1d.vehiclestatus.HighBeamStatus\x12\x31\n\x0cturnLampMode\x18\x05 \x01(\x0e\x32\x1b.vehiclestatus.TurnLampMode\"\x8b\x01\n\tLightInfo\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.vehiclestatus.LightType\x12*\n\x06zoneId\x18\x02 \x01(\x0e\x32\x1a.vehiclestatus.LightZoneId\x12*\n\x06status\x18\x04 \x01(\x0e\x32\x1a.vehiclestatus.LightStatus*Y\n\x0fLightShowActive\x12\r\n\tLsaEnable\x10\x00\x12\x10\n\x0cLsaActivated\x10\x01\x12\x0e\n\nLsaDisable\x10\x02\x12\x15\n\x08LsaEmpty\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*i\n\x0bLightStatus\x12\x12\n\x0eLightStatusOff\x10\x00\x12\x11\n\rLightStatusOn\x10\x01\x12\x14\n\x10LightStatusFault\x10\x02\x12\x1d\n\x10LightStatusEmpty\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*\x9d\x01\n\x0eHighBeamStatus\x12\x12\n\x0eHighBeamAllOff\x10\x00\x12\x16\n\x12HighBeamHighBeamOn\x10\x01\x12\x10\n\x0cHighBeamAHBC\x10\x02\x12\x1e\n\x1aHighBeamAHBCTemporarilyOff\x10\x03\x12\x11\n\rHighBeamError\x10\x04\x12\x1a\n\rHighBeamEmpty\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*u\n\x0cTurnLampMode\x12\x10\n\x0cTurnLampStop\x10\x00\x12\x10\n\x0cTurnLampLeft\x10\x01\x12\x11\n\rTurnLampRight\x10\x02\x12\x12\n\x0eTurnLampHazard\x10\x03\x12\x1a\n\rTurnLampEmpty\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x62\x06proto3')

_LIGHTSHOWACTIVE = DESCRIPTOR.enum_types_by_name['LightShowActive']
LightShowActive = enum_type_wrapper.EnumTypeWrapper(_LIGHTSHOWACTIVE)
_LIGHTSTATUS = DESCRIPTOR.enum_types_by_name['LightStatus']
LightStatus = enum_type_wrapper.EnumTypeWrapper(_LIGHTSTATUS)
_HIGHBEAMSTATUS = DESCRIPTOR.enum_types_by_name['HighBeamStatus']
HighBeamStatus = enum_type_wrapper.EnumTypeWrapper(_HIGHBEAMSTATUS)
_TURNLAMPMODE = DESCRIPTOR.enum_types_by_name['TurnLampMode']
TurnLampMode = enum_type_wrapper.EnumTypeWrapper(_TURNLAMPMODE)
LsaEnable = 0
LsaActivated = 1
LsaDisable = 2
LsaEmpty = -1
LightStatusOff = 0
LightStatusOn = 1
LightStatusFault = 2
LightStatusEmpty = -1
HighBeamAllOff = 0
HighBeamHighBeamOn = 1
HighBeamAHBC = 2
HighBeamAHBCTemporarilyOff = 3
HighBeamError = 4
HighBeamEmpty = -1
TurnLampStop = 0
TurnLampLeft = 1
TurnLampRight = 2
TurnLampHazard = 3
TurnLampEmpty = -1


_LIGHTBLOCK = DESCRIPTOR.message_types_by_name['LightBlock']
_LIGHTINFO = DESCRIPTOR.message_types_by_name['LightInfo']
LightBlock = _reflection.GeneratedProtocolMessageType('LightBlock', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTBLOCK,
  '__module__' : 'light_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.LightBlock)
  })
_sym_db.RegisterMessage(LightBlock)

LightInfo = _reflection.GeneratedProtocolMessageType('LightInfo', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTINFO,
  '__module__' : 'light_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.LightInfo)
  })
_sym_db.RegisterMessage(LightInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIGHTSHOWACTIVE._serialized_start=458
  _LIGHTSHOWACTIVE._serialized_end=547
  _LIGHTSTATUS._serialized_start=549
  _LIGHTSTATUS._serialized_end=654
  _HIGHBEAMSTATUS._serialized_start=657
  _HIGHBEAMSTATUS._serialized_end=814
  _TURNLAMPMODE._serialized_start=816
  _TURNLAMPMODE._serialized_end=933
  _LIGHTBLOCK._serialized_start=63
  _LIGHTBLOCK._serialized_end=314
  _LIGHTINFO._serialized_start=317
  _LIGHTINFO._serialized_end=456
# @@protoc_insertion_point(module_scope)
