# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsp_rvs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtsp_rvs.proto\x12\rvehiclestatus\"%\n\x13VersionReportCmdReq\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\"S\n\x14VersionReportCmdResp\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x10\n\x08\x62\x61seline\x18\x04 \x01(\t\"M\n\x11TspEcuVersionsReq\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x17\n\x0fvehicleBaseline\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rType\x18\x03 \x01(\x05\"\x81\x01\n\x12TspEcuVersionsResp\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\'\n\x07\x65\x63uInfo\x18\x04 \x03(\x0b\x32\x16.vehiclestatus.EcuInfo\x12\x17\n\x0fvehicleBaseline\x18\x05 \x01(\t\"?\n\x07\x45\x63uInfo\x12\r\n\x05\x65\x63uId\x18\x01 \x01(\t\x12%\n\x06hwSwPn\x18\x02 \x03(\x0b\x32\x15.vehiclestatus.HwSwPn\"$\n\x06HwSwPn\x12\x0c\n\x04hwPn\x18\x01 \x03(\t\x12\x0c\n\x04swPn\x18\x02 \x03(\t\"\x8d\x01\n\x14\x45\x63uVersionCompareSts\x12\x33\n\x0f\x62\x61selineStsInst\x18\x01 \x01(\x0e\x32\x1a.vehiclestatus.Baselinests\x12.\n\recuHwSwPNList\x18\x02 \x03(\x0b\x32\x17.vehiclestatus.ecuPNExt\x12\x10\n\x08\x62\x61seline\x18\x03 \x01(\t\"z\n\x08\x65\x63uPNExt\x12\r\n\x05\x65\x63uId\x18\x01 \x01(\t\x12+\n\x04type\x18\x02 \x01(\x0e\x32\x1d.vehiclestatus.EcuVersionType\x12\x18\n\x10\x61\x63tualPartNumber\x18\x03 \x03(\t\x12\x18\n\x10targetPartNumber\x18\x04 \x03(\t*4\n\x0b\x42\x61selinests\x12\x0b\n\x07uniform\x10\x00\x12\n\n\x06varied\x10\x01\x12\x0c\n\x07unKnown\x10\xff\x01*A\n\x0e\x45\x63uVersionType\x12\x0f\n\x0bkHardwarePN\x10\x00\x12\x0f\n\x0bkSoftwarePN\x10\x01\x12\r\n\x08kUnknown\x10\xff\x01\x62\x06proto3')

_BASELINESTS = DESCRIPTOR.enum_types_by_name['Baselinests']
Baselinests = enum_type_wrapper.EnumTypeWrapper(_BASELINESTS)
_ECUVERSIONTYPE = DESCRIPTOR.enum_types_by_name['EcuVersionType']
EcuVersionType = enum_type_wrapper.EnumTypeWrapper(_ECUVERSIONTYPE)
uniform = 0
varied = 1
unKnown = 255
kHardwarePN = 0
kSoftwarePN = 1
kUnknown = 255


_VERSIONREPORTCMDREQ = DESCRIPTOR.message_types_by_name['VersionReportCmdReq']
_VERSIONREPORTCMDRESP = DESCRIPTOR.message_types_by_name['VersionReportCmdResp']
_TSPECUVERSIONSREQ = DESCRIPTOR.message_types_by_name['TspEcuVersionsReq']
_TSPECUVERSIONSRESP = DESCRIPTOR.message_types_by_name['TspEcuVersionsResp']
_ECUINFO = DESCRIPTOR.message_types_by_name['EcuInfo']
_HWSWPN = DESCRIPTOR.message_types_by_name['HwSwPn']
_ECUVERSIONCOMPARESTS = DESCRIPTOR.message_types_by_name['EcuVersionCompareSts']
_ECUPNEXT = DESCRIPTOR.message_types_by_name['ecuPNExt']
VersionReportCmdReq = _reflection.GeneratedProtocolMessageType('VersionReportCmdReq', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREPORTCMDREQ,
  '__module__' : 'tsp_rvs_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.VersionReportCmdReq)
  })
_sym_db.RegisterMessage(VersionReportCmdReq)

VersionReportCmdResp = _reflection.GeneratedProtocolMessageType('VersionReportCmdResp', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREPORTCMDRESP,
  '__module__' : 'tsp_rvs_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.VersionReportCmdResp)
  })
_sym_db.RegisterMessage(VersionReportCmdResp)

TspEcuVersionsReq = _reflection.GeneratedProtocolMessageType('TspEcuVersionsReq', (_message.Message,), {
  'DESCRIPTOR' : _TSPECUVERSIONSREQ,
  '__module__' : 'tsp_rvs_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.TspEcuVersionsReq)
  })
_sym_db.RegisterMessage(TspEcuVersionsReq)

TspEcuVersionsResp = _reflection.GeneratedProtocolMessageType('TspEcuVersionsResp', (_message.Message,), {
  'DESCRIPTOR' : _TSPECUVERSIONSRESP,
  '__module__' : 'tsp_rvs_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.TspEcuVersionsResp)
  })
_sym_db.RegisterMessage(TspEcuVersionsResp)

EcuInfo = _reflection.GeneratedProtocolMessageType('EcuInfo', (_message.Message,), {
  'DESCRIPTOR' : _ECUINFO,
  '__module__' : 'tsp_rvs_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.EcuInfo)
  })
_sym_db.RegisterMessage(EcuInfo)

HwSwPn = _reflection.GeneratedProtocolMessageType('HwSwPn', (_message.Message,), {
  'DESCRIPTOR' : _HWSWPN,
  '__module__' : 'tsp_rvs_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.HwSwPn)
  })
_sym_db.RegisterMessage(HwSwPn)

EcuVersionCompareSts = _reflection.GeneratedProtocolMessageType('EcuVersionCompareSts', (_message.Message,), {
  'DESCRIPTOR' : _ECUVERSIONCOMPARESTS,
  '__module__' : 'tsp_rvs_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.EcuVersionCompareSts)
  })
_sym_db.RegisterMessage(EcuVersionCompareSts)

ecuPNExt = _reflection.GeneratedProtocolMessageType('ecuPNExt', (_message.Message,), {
  'DESCRIPTOR' : _ECUPNEXT,
  '__module__' : 'tsp_rvs_pb2'
  # @@protoc_insertion_point(class_scope:vehiclestatus.ecuPNExt)
  })
_sym_db.RegisterMessage(ecuPNExt)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASELINESTS._serialized_start=738
  _BASELINESTS._serialized_end=790
  _ECUVERSIONTYPE._serialized_start=792
  _ECUVERSIONTYPE._serialized_end=857
  _VERSIONREPORTCMDREQ._serialized_start=32
  _VERSIONREPORTCMDREQ._serialized_end=69
  _VERSIONREPORTCMDRESP._serialized_start=71
  _VERSIONREPORTCMDRESP._serialized_end=154
  _TSPECUVERSIONSREQ._serialized_start=156
  _TSPECUVERSIONSREQ._serialized_end=233
  _TSPECUVERSIONSRESP._serialized_start=236
  _TSPECUVERSIONSRESP._serialized_end=365
  _ECUINFO._serialized_start=367
  _ECUINFO._serialized_end=430
  _HWSWPN._serialized_start=432
  _HWSWPN._serialized_end=468
  _ECUVERSIONCOMPARESTS._serialized_start=471
  _ECUVERSIONCOMPARESTS._serialized_end=612
  _ECUPNEXT._serialized_start=614
  _ECUPNEXT._serialized_end=736
# @@protoc_insertion_point(module_scope)
