"""迁入的原框架 pytest 选项声明，不导入设备或外部服务。"""
from pytest import Parser
def pytest_addoption(parser: Parser):
    parser.addoption('--tbcfg', action='store', default='', help='testbed config YAML file')
    parser.addoption('--tccfg', action='store', default='config/latest_config.yaml', help='testcase config YAML file')
    parser.addoption('--logpath', action='store', default='./logs', help='path of log folder')
    parser.addoption('--loglevel', action='store', default='INFO', choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'], help='Default log level, pcan be DEBUG/INFO/WARNING/ERROR/CRITICAL')
    parser.addoption('--file_loglevel', action='store', default='DEBUG', choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'], help='Default file log level, pcan be DEBUG/INFO/WARNING/ERROR/CRITICAL')
    parser.addoption('--sdb_ver', action='store', default='default', help='arxml version')
    parser.addoption('--soa_ver', action='store', default='default', help='soa version')
    parser.addoption('--veh_type', action='store', default='', help='车型参数，设定时会覆盖配置文件中的车型参数信息，一般配合--bl_ver使用，实现自定义车型的数据库版本，详见ecu_simulator/config下')
    parser.addoption('--bl_ver', action='store', default='', help='数据库版本，例如v_2_0_0，详见ecu_simulator/config下，指定时会加载对应版本的数据库')
    parser.addoption('--testplan', action='store', default='', help='test plan ID on MS')
    parser.addoption('--sec_planId', action='store', default='', help='test plan ID on MS')
    parser.addoption('--onlypass', choices=['true', 'false'], default=False, help="前提需要有testplan才生效, 为 'true' 时, test plan 只更新pass结果")
    parser.addoption('--disable_partner', action='store', choices=['true', 'false'], default=False, help='默认不禁用soa partner更新检查，用户可以设置true禁用soa partner更新')
    parser.addoption('--disable_env', action='store', choices=['true', 'false'], default=False, help='默认不禁用获取环境信息，用户可以设置true禁用获取环境信息')
    parser.addoption('--execute_type', action='store', choices=['fn', 'n'], default='', help='fn ---- test plan 只收集执行失败的和没有测试的用例，需要配合testplan一起使用n  ---- test plan 只收集执行没有测试的用例，需要配合testplan一起使用')
    parser.addoption('--record_log', action='store', choices=['true', 'false'], default=True, help='为true时，自动录制jetlog日志，为false不录制，默认为录制')
    parser.addoption('--trace_log', action='store', choices=['true', 'false'], default=True, help='为true时,自动录制总线报文，为false不录制，默认为录制')
    parser.addoption('--version_info', action='store', default='', help='被测版本')
    parser.addoption('--result_description', action='store', default='', help='结果说明')
    parser.addoption('--sdb_version', action='store', default='', help='数据库版本例如v1.3.0，主要是应用在升级上，需要跟--release_version配套使用')
    parser.addoption('--release_version', action='store', default='', help='释放版本例如AQ,AH等，主要是应用在升级上，需要跟--sdb_version配套使用')
    parser.addoption('--task_id', action='store', default='', help='FOTA task id')
    parser.addoption('--soft_id', action='store', default='', help='FOTA soft id, for bridge')
    parser.addoption('--e2e_info', action='store', default='', help='FOTA e2e info')
    parser.addoption('--fota_tcam_version', action='store', default='', help='FOTA TCAM被测版本')
    parser.addoption('--report_to_willow', choices=['BGM', 'TCAM', 'CDC', 'ACU'], action='store', help='上传报告到willow平台，当前字段只能在willow上执行，参数类型是BGM,TCAM,CDC,ACU')
    parser.addoption('--distributed', action='store', choices=['true', 'false', 'None'], default=None, help='是否分布式执行case，为True时表示master端，为False表示slave端，不填则是非分布式执行')
    parser.addoption('--plan_id', action='store', default='', help='计划ID，该id与测试计划有差别，不进行回填，可与-m一起使用，参数为ms标签，由于目前ms上的标签部分是有空格字符的，例如Mars One，如果使用-m指定了，需要加下划线，否则会出问题，也就是Mars One改成Mars_One，中间多个空格只加一个下划线')
    parser.addoption('--bench_count', action='store', type=int, default=None, help='分布式申请的任务数量，默认为3个')
    parser.addoption('--ip', action='store', type=str, default=None, help='非分布式运行时，可指定台架ip运行')
    parser.addoption('--disable_lock', action='store_true', help='是否跳过台架分布式锁')
    parser.addoption('--is_flash', choices=['true', 'false'], default=True, help='分布式是否跳过台架升级')
    parser.addoption('--by_platform', choices=['true', 'false'], default=True, help='分布式的通讯方式，默认true数据平台，可选false实时双端通讯')
    parser.addoption('--dist_id', type=str, default=None, help='分布式运行的唯一id')
