# -*- coding: utf-8 -*-
"""
@File        : can2lin_lin2can_sdk_generator.py
@Description : description about this file
@Examples    :

cd tools/scripts_generator
python can2lin_lin2can_sdk_generator.py --project_type=cgw --refactor_path=project/cgw_oncar/test/can_lin_routing
currently project_type support bgm,cgw, the refactor_path means which path you want to scan
Pay Attention:
This script need to match below structure:
        def test_from_chassis_can_crashdetd_to_lin5_vehcrashind(self):
        '''
            Source Bus: Chassis CAN
            Target Bus: LIN5
            Source Message Name: ACM_01
            Target Message Name: CGW_SCU_DP_01
            Source Message ID: 0x3c
            Target Message ID: 0x11
            Source Signal Name: CrashDetd
            Target Signal Name: VehCrashInd
        '''
            # Set source signal value: v_Crash_not_detected
            pcan.crashdetd_crash_not_detected()
            # Check target signal value: v_No_crash
            pcan.assert_vehcrashind_is_no_crash()
            # Set source signal value: v_Crash_detected
            pcan.crashdetd_crash_detected()
            # Check target signal value: v_crashed
            pcan.assert_vehcrashind_is_crashed()

it depends on Source bus, target bus, target message and so on, also need to tell it which signal value you want check, e.g Set source signal value: v_Crash_not_detected

"""
import importlib
import sys
import os
import re
import argparse
from pathlib import Path



def read_can_lin_file(project_type, path):
    def_set_fixed_value_template = \
        '''\n    def {sdk_name}(self):
        """
        Generated by script automatic.
        DO NOT modify!
        """
        self.set(self.{dbc_or_ldf}.{source_busL}.{source_msg_name}, "{source_sig_name}", "{sig_value}")
        '''

    def_set_unfixed_value_template = \
        '''\n    def {sdk_name}(self, value):
        """
        Generated by script automatic.
        DO NOT modify!
        """
        self.set(self.{dbc_or_ldf}.{source_busL}.{source_msg_name}, "{source_sig_name}", value)
        '''

    def_check_fixed_value_template = \
        '''\n    def {sdk_name}(self):
        """
        Generated by script automatic.
        DO NOT modify!
        """
        self.check(self.{dbc_or_ldf}.{target_busL}.{target_msg_name}, "{target_sig_name}", "{sig_value}")
        '''
    def_check_unfixed_value_template = \
        '''\n    def {sdk_name}(self, value):
        """
        Generated by script automatic.
        DO NOT modify!
        """
        self.check(self.{dbc_or_ldf}.{target_busL}.{target_msg_name}, "{target_sig_name}", value)
        '''
    if project_type == 'cgw':
        handle_moudle = importlib.import_module("sdk.dut.cgw.cgw_pcan")
        pcan = handle_moudle.CgwPcan
    elif project_type == 'bgm':
        handle_moudle = importlib.import_module("sdk.dut.bgm.bgm_pcan")
        pcan = handle_moudle.BgwPcan
    else:
        raise ValueError('project_type only support cgw and bgm, please help check')
    pcan_func_list = [func for func in dir(pcan) if not func.startswith('_')]

    pcan_path = str(handle_moudle).split("from")[-1].replace("'", "").replace(">", "").lstrip()
    curdir = os.getcwd()
    wanted_path = os.path.join(curdir, '../../' + path)
    wanted_list = os.listdir(wanted_path)
    re_func = re.compile("pcan\.(.*)\((.*)\)")
    result = []
    for wanted in wanted_list:
        file_path = os.path.join(wanted_path, wanted)
        if not os.path.isfile(file_path):
            continue
        with open(file_path) as f:
            file_content_dict = {}
            func_list = []
            payload = f.readlines()
            payload = [line.replace('  ', '').replace('\n', '') for line in payload]
            flag_value = None
            for line in payload:
                if line.startswith("def test_") and line not in func_list:
                    func_list.append(line)
                    file_content_dict[func_list[-1]] = {}
                    file_content_dict[func_list[-1]]["sdk_dict"] = {}
                elif len(func_list) > 0:
                    if ":" in line:
                        line.replace(" ", "")
                        new_line = line.split(":")
                        if "Set source signal value" in new_line[0] or "Check target signal value" in new_line[0]:
                            if new_line[1] not in file_content_dict[func_list[-1]]["sdk_dict"].keys():
                                file_content_dict[func_list[-1]]["sdk_dict"][new_line[1]] = []
                                flag_value = new_line[1]
                        else:
                            file_content_dict[func_list[-1]][new_line[0]] = new_line[1]
                    elif re.search(re_func, line) and flag_value:
                        func_name = re.search(re_func, line)
                        file_content_dict[func_list[-1]]["sdk_dict"][flag_value].append(func_name.group())
            # Verify if sdk existed, if yes append it to pcan

            for v in file_content_dict.values():
                for singal, sdk_name_list in v.get("sdk_dict").items():
                    if represents_int(singal):
                        set_template = def_set_unfixed_value_template
                        check_template = def_check_unfixed_value_template
                        is_fixed = False
                    else:
                        set_template = def_set_fixed_value_template
                        check_template = def_check_fixed_value_template
                        is_fixed = True
                    for sdk_name in sdk_name_list:
                        sdk_name = sdk_name.split("(")[0]
                        if sdk_name.split('.')[-1] not in pcan_func_list:
                            if "assert" in sdk_name:
                                dbc_or_ldf = "dbc" if "CAN" in v.get('Target Bus') else "ldf"
                                target_bus_l = v.get('Target Bus').lstrip(" ").split(" ")[
                                    0].lower() if dbc_or_ldf == "dbc" else v.get('Target Bus').strip().lower()
                                target_msg_name = v.get("Target Message Name").strip()
                                target_sig_name = v.get("Target Signal Name").strip()
                                sdk_name_v = sdk_name.split("pcan.")[-1]
                                sdk_func = check_template.format(sdk_name=sdk_name_v, dbc_or_ldf=dbc_or_ldf,
                                                                 target_busL=target_bus_l,
                                                                 target_msg_name=target_msg_name,
                                                                 target_sig_name=target_sig_name,
                                                                 sig_value=singal.strip())
                                result.append(sdk_func)

                            else:
                                dbc_or_ldf = "dbc" if "CAN" in v.get('Source Bus') else "ldf"
                                source_bus_l = v.get('Source Bus').lstrip(" ").split(" ")[
                                    0].lower() if dbc_or_ldf == "dbc" else \
                                v.get('Source Bus').strip().lower().split('_')[-1]
                                source_msg_name = v.get("Source Message Name").strip()
                                source_sig_name = v.get("Source Signal Name").strip()
                                sdk_name_v = sdk_name.split("pcan.")[-1]
                                sdk_func = set_template.format(sdk_name=sdk_name_v, dbc_or_ldf=dbc_or_ldf,
                                                               source_busL=source_bus_l,
                                                               source_msg_name=source_msg_name,
                                                               source_sig_name=source_sig_name,
                                                               sig_value=singal.strip())
                                result.append(sdk_func)
    return list(set(result)), pcan_path


def represents_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False


def append_to_file(result):
    sdk_content, path = result
    with open(path, "a") as f:
        for sdk_func in sdk_content:
            f.write(sdk_func)


if __name__ == '__main__':
    path_tail = "compass/tools/scripts_generator"
    scripts_path = Path(os.getcwd()).as_posix()
    argparser = argparse.ArgumentParser()
    argparser.add_argument(
        '--project_type', choices=('cgw', 'bgm'), help='pcan_type will be used.', default="cgw")
    argparser.add_argument(
        '--refactor_path', default="project/cgw_oncar/test/can_lin_routing")
    args = argparser.parse_args()
    assert scripts_path.endswith(path_tail), "Before running this script:\ncd {}".format(path_tail)
    append_to_file(read_can_lin_file(args.project_type, args.refactor_path))
