# -*- coding: utf-8 -*-
"""
@File        : can_lin_cyc_and_dlc_test_generator.py
@Description : This script will auto-generate the network of can, lin cyc and dlc test case.
@Examples    :

cd tools/scripts_generator
# TODO modify usage     Status:Done
# Usage:
e.g.1:  hw_type=BGM, veh_type=FORCE, dbc_ver=v0_0_1, ldf_ver=v0_0_1
python3 can_lin_cyc_and_dlc_test_generator.py --hw_type=BGM --dbc_ver=v0_0_1 --ldf_ver=v0_0_1 --case_path=project/bgm/test/diag_nm/cycle_and_dlc --veh_type=FORCE

e.g.2:  hw_type=CGW, veh_type=ES6, dbc_ver=v3_0_8, ldf_ver=v3_0_6
python3 can_lin_cyc_and_dlc_test_generator.py --hw_type=CGW --dbc_ver=v3_0_8 --ldf_ver=v3_0_6 --case_path=project/cgw_oncar/test/cycle_and_dlc --veh_type=ES6

e.g.3:  hw_type=CGW, veh_type=ES8, dbc_ver=v7_5_8, ldf_ver=v3_4
python3 can_lin_cyc_and_dlc_test_generator.py --hw_type=CGW --dbc_ver=v7_5_8 --ldf_ver=v3_4 --case_path=project/cgw_oncar/test/cycle_and_dlc --veh_type=ES8

e.g.4   hw_type=CGW, veh_type=ES8, dbc_ver=map_v0_1_0, ldf_ver=v3_4
# This used for Marco Polo
python3 can_lin_cyc_and_dlc_test_generator.py --hw_type=CGW --dbc_ver=map_v0_1_0 --ldf_ver=v3_0_6 --case_path=project/cgw_oncar/test/cycle_and_dlc --veh_type=ES8

e.g.5   hw_type=BGM, veh_type=FORCE, dbc_ver=v0_1_0, ldf_ver=v0_1_0, --case_type=NVOS
# This used for NVOS Test case
python3 can_lin_cyc_and_dlc_test_generator.py --hw_type=BGM --dbc_ver=v0_0_1 --ldf_ver=v0_0_1 --case_path=project/cgw_oncar/test/cycle_and_dlc/nvos --veh_type=FORCE --case_type=NVOS

Env Requirement:
                    1) Pls make sure :DBC Files(.py) must cover KEYWORDS: msg_id =,msg_cyc =,dlc =,tx_node =
                    2) Pls make sure :LDF Files(.py) must cover KEYWORDS: msg_id =,msg_length =,originator =,msg_cyc =
                    3) Script develop env: Python 3.7.8, Python3.8.2
                    !!! If any of above items of file changed, Pls accordingly change this generator script if necessary
"""

import os
import sys
import argparse
import time



"""
Structure of this generator want to generate:

            1) test_header
            2) notice_information
            3) test_def
            4) test_bodycan
            
Veh_type = ['ES6', 'ES8', 'FURY']
Veh_gen = ['G1.1', 'G1.2', 'G1.3', 'G1.F']
"""

test_header = """# -*- coding: utf-8 -*-

# Module for Network of CAN LIN Cyc,DLC testing, hw_type is must: {hw_type} . vehicle type is must: {veh_type}
# Expected dbc version is DBC: {dbcver}, LDF: {ldfver}
# Based on '.py' files as input
# Generated by the tools/scripts_generator/can_lin_cyc_and_dlc_test_generator.py  DO NOT EDIT!

import time
from sdk.interface.pcan_const import PcanConst
from project.cgw_oncar.fixture.oncar import *
from project.cgw_oncar.case_helper.test_base import TestBase
from project.cgw_offcar.case_helper.parse_tb_config import ParseTBConfig
from sdk.dut.cgw.cgw_app import CgwApp
import os
cgw = CgwApp()


veh_type = os.getenv("VEH_TYPE")
veh_gen = os.getenv("VEH_GEN")
dbc_ver = os.getenv("DBC_VER")
ldf_ver = os.getenv("LDF_VER")


{if_judge_lines}
    @pytest.mark.full
    @pytest.mark.dlc_and_cyc
    class TestBusCycDlc{veh_type}(TestBase):
        def before_class(self, oncar):
            super().before_class(self, oncar)

            global pcan
            pcan = self.app.pcan

            global cli
            cli = self.app.cli
            
            # Get yaml info, add can_bus and lin_bus to bus_dict
            self.tbcfg = ParseTBConfig(oncar['tbcfg']).get_yaml()
            self.pcan_bus = self.tbcfg["pcan_bus"]

            self.bus_dict = dict()
            for k, v in self.pcan_bus.items():
                self.bus_dict[k] = v

            cli.mpc_wake_up()
            
        def before_each_func(self, oncar):
            super().before_each_func(self)

        def after_class(self, oncar):
            super().after_class(self, oncar)
            
        def after_each_func(self, oncar):
            super().after_each_func(self)
"""
notice_information_template = \
    '''\n        """
        ##########################################################
        #    BUS_NAME = {bus_name} | Case Amount of this Bus = {total_case}    #
        ##########################################################
        """
'''

test_def_template = \
    '''\n        def test_{bus_name}_{msg_id}_{case_number}(self):
            """
            BUS Name        : {bus_name}
            Message ID      : {msg_id}
            Message Cycle   : {msg_cyc} Seconds
            Message DLC     : {msg_dlc} Bytes
            """
'''

test_bodycan_template = \
    '''            {bus_type}
            logger.info('-------->>>>>>>> case START: Test on {bus_name} Bus')
            assert pcan.bus_cyc_and_dlc_is_values(msg_id='{msg_id}', msg_cyc={msg_cyc}, msg_dlc={msg_dlc}, bus_name={bus_name})
            logger.info('--------<<<<<<<< case PASS: Bus:{bus_name}, Msg_id:{msg_id}, Msg_cyc={msg_cyc}')
'''


def get_canid_msgid_cyc_dlc(hw_type=None, dbc_ver=None, ldf_ver=None, veh_type=None):
    """
    This function used to get data from, e.g. bodycan.py
    Data clean up: find all the signal sent from bgm & msg_cyc != 0
    'veh_type',     e.g. 'es6', Default: None
    'dbc_ver',  e.g. 'v3_0_8'
    'ldf_ver',  e.g. 'v3_0_6'
    Return dict,    e.g.  {'bodycan':[['0x2c3', 0.02, 2], ['0x2c4', 0.02, 4], ...],
                           'cdc':[['0x2c5', 0.02, 2], ['0x2c6', 0.02, 4]], ...],
                           ...
                           }
    """
    if not hw_type:
        raise Exception('Args: hw_type is Empty. hw_type must assign by user')

    if not veh_type:
        raise Exception('Args: veh_type is Empty. veh_type must assign by user')

    veh_type = str(veh_type).lower()        # Make sure the same form with our test structure

    print("Start Analyze dbc and ldf Files, then save data to return_dict")
    return_dict = {}

    # Part 1: ------------------------------------------------------------------------------------ Analyze DBC
    print('# Analyze DBC :START --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')

    if hw_type == 'CGW':
        can_source_path = 'sdk/dut/cgw/dbc_cls/{vehType}/{dbcVersion}'.format(vehType=veh_type,
                                                                              dbcVersion=dbc_ver)
    elif hw_type == 'BGM':
        can_source_path = 'sdk/dut/bgm/dbc_cls/{vehType}/{dbcVersion}'.format(vehType=veh_type,
                                                                              dbcVersion=dbc_ver)
    else:
        raise Exception('Fatal: error hw_type, pls check input args or update this script')

    tmp = os.getcwd().split('/')[:-2]
    tmp_path = os.path.join('/'.join(tmp), can_source_path)
    print('tmp_path:', tmp_path)
    can_file_list_temp = sorted(os.listdir(tmp_path))       # Get all names of files from tmp_path. e.g. "bodycan.py"
    # print('can_file_list_temp=', can_file_list_temp)      # Usage: Debug
    can_file_list = [file for file in can_file_list_temp if '__' not in file and 'dbc_cls' not in file]     # Clean
    print('can_file_list:', can_file_list)                  # Usage: Notice & Debug
    
    # Get every file's absolute path
    can_file_list_path = [os.path.join(tmp_path, can_file_list[i]) for i in range(len(can_file_list))]
    # print('can_file_list_path[0]=', can_file_list_path[0])  # Usage: Notice & Debug

    for bus in can_file_list_path:
        can_id = bus.split('/')[-1].replace('.py', '')      # Get can_id(name of can). e.g. 'bodycan'
        # Analyze .py，get useful data: msg_id, msg_cyc, msg_dlc
        print('->>> start Analyze {can_id}:'.format(can_id=can_id))
        time.sleep(.1)
        with open(bus, "r") as code_lines:
            return_dict[can_id] = list()
            # tmp_can items must in order like : ['msg_id', 'msg_cyc', 'dlc']
            tmp_can = []
            msg_cyc = 0.0
            count_can = 4   # Cause useful keyword's number is 4 in every reading line cycle
            tx_list = []

            for line in code_lines:
                if 'msg_id =' in line:
                    tmp_can.append(line.split('=')[-1].replace(' ', '').replace('\n', ''))
                    count_can -= 1
                elif 'msg_cyc =' in line:
                    msg_cyc = float(line.split('=')[-1].replace(' ', '').replace('\n', ''))
                    tmp_can.append(str(msg_cyc))
                    count_can -= 1
                elif 'dlc =' in line:
                    tmp_can.append(line.split('=')[-1].replace(' ', '').replace('\n', ''))
                    count_can -= 1
                elif 'tx_node =' in line:
                    tx_list.extend(line.split('=')[-1].replace(' ', '').replace('\n', '').split("'"))
                    count_can -= 1

                if count_can == 0:
                    # Pls confirm keyword at next line: 'BGM' or 'CGW' in DBC or LDF Files
                    # Only store the signal which msg_cyc != 0.0 & from BGM or CGW
                    if ('CGW' in tx_list or 'BGM' in tx_list) and msg_cyc != 0.0:
                        return_dict[can_id].append(tmp_can)
                    tmp_can = []                                # Reset temp variable: tmp, msg_cyc, count
                    msg_cyc = 0.0
                    count_can = 4
                    tx_list = []

    print('# Analyze DBC :END <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<---')

    """
    # Part 2: ------------------------------------------------------------------------------------ Analyze LDF
    print('# Analyze LDF :START --->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
    # Notice: Pls keep the same signal order , e.g. ['msg_id', 'msg_cyc', 'dlc']   Status:Done

    if hw_type == 'CGW':
        if str(veh_type).upper() == 'ES8' and 'map' in dbc_ver:
            tmp_veh_type = 'es6'    # Reason: cause Macro Polo use the LDF of ES6, but vehType is 'ES8'
            lin_source_path = 'sdk/dut/cgw/ldf_cls/{vehType}/{ldfVersion}'.format(vehType=tmp_veh_type,
                                                                                  ldfVersion=ldf_ver)
        else:
            lin_source_path = 'sdk/dut/cgw/ldf_cls/{vehType}/{ldfVersion}'.format(vehType=veh_type,
                                                                                  ldfVersion=ldf_ver)
    elif hw_type == 'BGM':
        lin_source_path = 'sdk/dut/bgm/ldf_cls/{vehType}/{ldfVersion}'.format(vehType=veh_type,
                                                                              ldfVersion=ldf_ver)
    else:
        # lin_source_path = 'sdk/dut/bgm/ldf_cls/{ldfVersion}'.format(ldfVersion=ldf_ver)
        raise Exception('Fatal: error hw_type, pls check input args or update this script')

    tmp = os.getcwd().split('/')[:-2]
    tmp_path = os.path.join('/'.join(tmp), lin_source_path)
    print('tmp_path:', tmp_path)
    lin_file_list_temp = sorted(os.listdir(tmp_path))
    lin_file_list = [file for file in lin_file_list_temp if '__' not in file]
    print('lin_file_list:', lin_file_list)

    lin_file_list_path = [os.path.join(tmp_path, lin_file_list[i]) for i in range(len(lin_file_list))]
    # print('can_file_list_path[0]=', lin_file_list_path[0])

    for bus in lin_file_list_path:
        lin_id = bus.split('/')[-1].replace('.py', '')
        print('->>> start Analyze {lin_id}:'.format(lin_id=lin_id))
        time.sleep(.1)
        with open(bus, "r") as code_lines:
            return_dict[lin_id] = []
            # tmp_lin items must in order like : ['msg_id', 'dlc', 'msg_cyc']
            tmp_lin = []
            origin = 'Init'
            count_lin = 4   # Cause useful keyword's number is 4 in every reading line cycle
            for line in code_lines:
                if 'msg_id =' in line:
                    decimal_value = line.split('=')[-1].replace(' ', '').replace('\n', '')
                    count_lin -= 1
                    tmp_lin.append(hex(int(decimal_value)))         # Decimal -> Hex
                elif 'msg_length =' in line:
                    tmp_lin.append(line.split('=')[-1].replace(' ', '').replace('\n', ''))
                    count_lin -= 1
                elif 'originator =' in line:
                    origin = (line.split('=')[-1].replace(' ', '').replace('\n', ''))
                    count_lin -= 1
                elif 'msg_cyc =' in line:
                    tmp_lin.append(line.split('=')[-1].replace(' ', '').replace('\n', ''))
                    count_lin -= 1

                # Only store the signal which msg_cyc != 0.0 & from BGM or CGW
                if count_lin == 0:
                    # TODO : confirm keyword at next line: 'BGM' or 'CGW'   Status:TODO, wait for latest DBC Files
                    if (origin == '"BGM"' or origin == '"CGW"') and float(tmp_lin[-1]) != 0.0:  # TODO: used to test
                        tmp_lin[-1], tmp_lin[-2] = tmp_lin[-2], tmp_lin[-1]     # Make sure the same order as DBC
                        return_dict[lin_id].append(tmp_lin)
                    tmp_lin = []                                        # Clean temp variable: tmp, msg_cyc, count
                    origin = 'Init'
                    count_lin = 4

    print('# Analyze LDF :END <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<---')
    """

    if len(return_dict) == 0:
        raise FileNotFoundError('Error (: The return_dict is empty, Please check script or args you assigned')
    else:
        return return_dict


def generate_cyc_and_dlc_test_case(hw_type=None, bus_info_dict=None, dbc_ver=None, ldf_ver=None,
                                   case_path=None, veh_type=None, case_type=None):
    """
    'hw_type',    hw_type is must assign by user
    'bus_info_dict',    data generate from Func: get_canid_msgid_cyc_dlc(), form like below
                            {'bodycan':[['0x2c3', 0.02, 2], ['0x2c4', 0.02, 4], ...],
                             'cdc':[['0x2c5', 0.02, 2], ['0x2c6', 0.02, 4]], ...],
                              ...
                                }
    'dbc_ver',      e.g.:v3_0_4
    'ldf_ver',      e.g.:v3_0_6
    'case_path',        e.g. /project/cgw_oncar/test/cyc_and_dlc
    'veh_type',     e.g.:es6    Notice: this arg is must assign by user
    """

    # arg hw_type must be 'CGW' or 'BGM', this may need update later

    # Env setup: judge, if the case_path assigned by user is existed
    if os.path.exists(case_path):
        print('-->>> The case_path you assign already existed')
        time.sleep(.1)
    else:
        print('-->>> The case_path you assign not existed, will use os.makedirs to create{path}'.format(path=case_path))
        time.sleep(.1)
        os.makedirs(case_path, exist_ok=True)

    bus_type = ""
    if case_type:
        case_type = case_type
    else:
        case_type = 'Testbench'
    if case_type.lower() == 'nvos':
        bus_type = "vcan_bus = 'vcan_{bus_name}'\n            {bus_name} = vcan_bus"
    else:
        bus_type = "{bus_name} = self.bus_dict['{bus_name}']"

    # 'if_judge_lines' used to judge veh_type, veh_gen, dbc_ver and ldf_ver in test script
    if_judge_lines_es6 = 'if (veh_type == "ES6" or veh_type == "FURY" or "G1.F" in veh_gen) and dbc_ver == "{dbcver}"' \
                         ' and ldf_ver == "{ldfver}":'
    if_judge_lines_es8 = 'if veh_type == "ES8" and "G1.F" not in veh_gen and dbc_ver == "{dbcver}" and ' \
                         'ldf_ver == "{ldfver}":'
    if_judge_lines_es8_marco_polo = 'if veh_type == "ES8" and "G1.F.E" in veh_gen and dbc_ver == "{dbcver}" and ' \
                         'ldf_ver == "{ldfver}":'
    # TODO: if_judge_lines_force may need update later. 2020-11-17
    if_judge_lines_force = 'if veh_type == "FORCE" and dbc_ver == "{dbcver}" and ldf_ver == "{ldfver}":'

    # For more stable, if the args inputted by user, we will use 'str.upper()' although I know it's not necessary
    hw_type_lower = str(hw_type).lower()
    if str(hw_type).upper() == "CGW":
        if str(veh_type).upper() == "ES6":
            if_judge_lines = if_judge_lines_es6.format(dbcver=dbc_ver, ldfver=ldf_ver)
        elif str(veh_type).upper() == "ES8":
            if 'map' not in dbc_ver:
                if_judge_lines = if_judge_lines_es8.format(dbcver=dbc_ver, ldfver=ldf_ver)
            else:
                if_judge_lines = if_judge_lines_es8_marco_polo.format(dbcver=dbc_ver, ldfver=ldf_ver)
        else:
            raise Exception('Fatal: error veh_type, pls check input args or update this script')
    elif str(hw_type).upper() == "BGM":
        if str(veh_type).upper() == "FORCE":
            if_judge_lines = if_judge_lines_force.format(dbcver=dbc_ver, ldfver=ldf_ver)
        else:
            raise Exception('Fatal: error veh_type, pls check input args or update this script')
    else:
        raise Exception('Fatal: error hw_type, pls check input args or update this script')

    # number = 11         # number : how many 'candump' msgs do we want to Analyze

    out_file_name = 'test_{hw_type}_{veh_type}_cyc_and_dlc_dbc_is_{dbcver}.py'.format(
        hw_type=hw_type_lower, veh_type=veh_type.lower(), dbcver=dbc_ver)
    out_file_path = os.path.join(case_path, out_file_name)

    # start write case file here [I/O]:

    print('-->>> Write test header NOW')
    with open(out_file_path, "w+") as out:          # write mode ['w+'] make sure that will cover the name file same
        out.write(test_header.format(veh_type=veh_type, dbcver=dbc_ver, ldfver=ldf_ver,
                                     if_judge_lines=if_judge_lines, hw_type=hw_type))

    num = 1             # num used to record how many case will generate
    tmp_bus_type = ''
    for bus_name, msg_info in bus_info_dict.items():
        if len(msg_info) != 0:
            msg_number = len(msg_info)
            print('-->>> Write notice information for {bus_name}'.format(bus_name=bus_name))
            time.sleep(.1)
            with open(out_file_path, "a+") as out:      # write mode ['w+'] make sure that file will gradually added
                out.write(notice_information_template.format(bus_name=bus_name, total_case=msg_number))

            print('-->>> Start to generate test case for {bus_name}'.format(bus_name=bus_name))
            for info in msg_info:
                with open(out_file_path, "a+") as out:  # write mode ['w+'] make sure that file will gradually added
                    tmp_num = num
                    tmp_num =str(tmp_num).zfill(3)      # let number like 1 or 11 will change to '001' or '011'
                    num += 1
                    out.write(test_def_template.format(
                        bus_name=bus_name, msg_id=info[0], msg_cyc=info[1], msg_dlc=info[-1], case_number=tmp_num))
                    tmp_bus_type = bus_type.format(bus_name=bus_name)
                    out.write(test_bodycan_template.format(
                        bus_type=tmp_bus_type, bus_name=bus_name, msg_id=info[0], msg_cyc=info[1], msg_dlc=info[-1]))
        else:
            print('--->>> ): Bus:{bus_name} have no expected signal, will check next bus'.format(bus_name=bus_name))
    print('--->>>    Success!!! {num} cases has been generated! case_path:{path}'.format(num=num-1, path=case_path))


if __name__ == '__main__':
    # <- Below code is main function, which is used to generate cases
    # Define some useful args: hw_type, dbc_ver, ldf_ver, case_path, veh_type
    argparser = argparse.ArgumentParser()
    argparser.add_argument('--hw_type', choices=('CGW', 'BGM'),
                           help='Hardware type, e.g. CGW, or BGM')
    argparser.add_argument('--dbc_ver', help='Version of DBC files. e.g.:v3_0_4')
    argparser.add_argument('--ldf_ver', help='Version of LDF files. e.g.:v3_0_6')
    """
    # Notice: arg: case_path , must define yourself, e.g. project/cgw_oncar/test/cycle_and_dlc
    #       :                                        e.g. project/cgw_oncar/test/cycle_and_dlc
    """
    argparser.add_argument('--case_path',
                           help='Path for generated test case file. e.g.: project/cgw_oncar/test/cycle_and_dlc')
    argparser.add_argument('--veh_type', help='Must arg: Vehicle Type of DBC files use. e.g.: ES6, FORCE')
    argparser.add_argument('--case_type', help='Optional arg:Testbench or NVOS, Default is Testbench')
    args = argparser.parse_args()

    # Analyze ".py" and get data from it
    can_lin_info_dict = get_canid_msgid_cyc_dlc(hw_type=args.hw_type, dbc_ver=args.dbc_ver,
                                                ldf_ver=args.ldf_ver, veh_type=args.veh_type)
    # Run function of generation
    tmp = os.getcwd().split('/')[:-2]
    tmp_path = args.case_path
    case_path = os.path.join('/'.join(tmp), tmp_path)
    generate_cyc_and_dlc_test_case(hw_type=args.hw_type, bus_info_dict=can_lin_info_dict,
                                   dbc_ver=args.dbc_ver, ldf_ver=args.ldf_ver, case_path=case_path,
                                   veh_type=args.veh_type, case_type=args.case_type)
