# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: source/remote_vehicle_control/cmd/realtime_cmd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()





DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4source/remote_vehicle_control/cmd/realtime_cmd.proto\x12\x03\x63md\x1a.source/remote_vehicle_control/cmd/common.proto\"\xca\x01\n\x0eRealtimeCmdReq\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x0b\n\x03vid\x18\x02 \x01(\t\x12+\n\x0cvehicleModel\x18\x03 \x01(\x0e\x32\x15.cmd.EnumVehicleModel\x12!\n\x07\x63mdCode\x18\x04 \x01(\x0e\x32\x10.cmd.EnumCmdCode\x12!\n\tcmdDetail\x18\x05 \x01(\x0b\x32\x0e.cmd.CmdDetail\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x15\n\roperateUserId\x18\x07 \x01(\x03\"\xa9\x01\n\x0fRealtimeCmdResp\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12,\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x1e.cmd.RealtimeCmdResp.DataEntry\x12\x10\n\x08\x65xecType\x18\x05 \x01(\x05\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1fZ\x1dgo/remote_vehicle_control/cmdb\x06proto3')



_REALTIMECMDREQ = DESCRIPTOR.message_types_by_name['RealtimeCmdReq']
_REALTIMECMDRESP = DESCRIPTOR.message_types_by_name['RealtimeCmdResp']
_REALTIMECMDRESP_DATAENTRY = _REALTIMECMDRESP.nested_types_by_name['DataEntry']
RealtimeCmdReq = _reflection.GeneratedProtocolMessageType('RealtimeCmdReq', (_message.Message,), {
  'DESCRIPTOR' : _REALTIMECMDREQ,
  '__module__' : 'source.remote_vehicle_control.cmd.realtime_cmd_pb2'
  # @@protoc_insertion_point(class_scope:cmd.RealtimeCmdReq)
  })
_sym_db.RegisterMessage(RealtimeCmdReq)

RealtimeCmdResp = _reflection.GeneratedProtocolMessageType('RealtimeCmdResp', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _REALTIMECMDRESP_DATAENTRY,
    '__module__' : 'source.remote_vehicle_control.cmd.realtime_cmd_pb2'
    # @@protoc_insertion_point(class_scope:cmd.RealtimeCmdResp.DataEntry)
    })
  ,
  'DESCRIPTOR' : _REALTIMECMDRESP,
  '__module__' : 'source.remote_vehicle_control.cmd.realtime_cmd_pb2'
  # @@protoc_insertion_point(class_scope:cmd.RealtimeCmdResp)
  })
_sym_db.RegisterMessage(RealtimeCmdResp)
_sym_db.RegisterMessage(RealtimeCmdResp.DataEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035go/remote_vehicle_control/cmd'
  _REALTIMECMDRESP_DATAENTRY._options = None
  _REALTIMECMDRESP_DATAENTRY._serialized_options = b'8\001'
  _REALTIMECMDREQ._serialized_start=110
  _REALTIMECMDREQ._serialized_end=312
  _REALTIMECMDRESP._serialized_start=315
  _REALTIMECMDRESP._serialized_end=484
  _REALTIMECMDRESP_DATAENTRY._serialized_start=441
  _REALTIMECMDRESP_DATAENTRY._serialized_end=484
# @@protoc_insertion_point(module_scope)
