# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: source/remote_vehicle_control/cmd/renewal_cmd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3source/remote_vehicle_control/cmd/renewal_cmd.proto\x12\x03\x63md\x1a.source/remote_vehicle_control/cmd/common.proto\"\xe9\x01\n\x10RenewalCmdNotify\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x13\n\x0bsubscribeId\x18\x02 \x01(\t\x12\x15\n\roperateUserId\x18\x03 \x01(\x03\x12+\n\x0cvehicleModel\x18\x04 \x01(\x0e\x32\x15.cmd.EnumVehicleModel\x12\"\n\x06opType\x18\x05 \x01(\x0e\x32\x12.cmd.RenewalOpType\x12)\n\rtaskCmdDetail\x18\x06 \x03(\x0b\x32\x12.cmd.TaskCmdDetail\x12\x1d\n\x15vehicleReportDatetime\x18\x07 \x01(\x04\"K\n\x14RenewalCmdNotifyResp\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12#\n\nexecDetail\x18\x02 \x03(\x0b\x32\x0f.cmd.ExecDetail*R\n\rRenewalOpType\x12\x0f\n\x0brnotUnknown\x10\x00\x12\x0f\n\x0brnotRequest\x10\x01\x12\x0f\n\x0brnotConfirm\x10\x02\x12\x0e\n\nrnotCancel\x10\x03\x42\x1fZ\x1dgo/remote_vehicle_control/cmdb\x06proto3')

_RENEWALOPTYPE = DESCRIPTOR.enum_types_by_name['RenewalOpType']
RenewalOpType = enum_type_wrapper.EnumTypeWrapper(_RENEWALOPTYPE)
rnotUnknown = 0
rnotRequest = 1
rnotConfirm = 2
rnotCancel = 3


_RENEWALCMDNOTIFY = DESCRIPTOR.message_types_by_name['RenewalCmdNotify']
_RENEWALCMDNOTIFYRESP = DESCRIPTOR.message_types_by_name['RenewalCmdNotifyResp']
RenewalCmdNotify = _reflection.GeneratedProtocolMessageType('RenewalCmdNotify', (_message.Message,), {
  'DESCRIPTOR' : _RENEWALCMDNOTIFY,
  '__module__' : 'source.remote_vehicle_control.cmd.renewal_cmd_pb2'
  # @@protoc_insertion_point(class_scope:cmd.RenewalCmdNotify)
  })
_sym_db.RegisterMessage(RenewalCmdNotify)

RenewalCmdNotifyResp = _reflection.GeneratedProtocolMessageType('RenewalCmdNotifyResp', (_message.Message,), {
  'DESCRIPTOR' : _RENEWALCMDNOTIFYRESP,
  '__module__' : 'source.remote_vehicle_control.cmd.renewal_cmd_pb2'
  # @@protoc_insertion_point(class_scope:cmd.RenewalCmdNotifyResp)
  })
_sym_db.RegisterMessage(RenewalCmdNotifyResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035go/remote_vehicle_control/cmd'
  _RENEWALOPTYPE._serialized_start=421
  _RENEWALOPTYPE._serialized_end=503
  _RENEWALCMDNOTIFY._serialized_start=109
  _RENEWALCMDNOTIFY._serialized_end=342
  _RENEWALCMDNOTIFYRESP._serialized_start=344
  _RENEWALCMDNOTIFYRESP._serialized_end=419
# @@protoc_insertion_point(module_scope)
