# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: source/remote_vehicle_control/cmd/subscribe_cmd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5source/remote_vehicle_control/cmd/subscribe_cmd.proto\x12\x03\x63md\x1a.source/remote_vehicle_control/cmd/common.proto\"\xb2\x01\n\x10SubscribeTaskReq\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x10\n\x08\x65xecTime\x18\x02 \x01(\x04\x12\x13\n\x0bsubscribeId\x18\x03 \x01(\t\x12\x15\n\roperateUserId\x18\x04 \x01(\x03\x12+\n\x0cvehicleModel\x18\x05 \x01(\x0e\x32\x15.cmd.EnumVehicleModel\x12#\n\ntaskDetail\x18\x06 \x03(\x0b\x32\x0f.cmd.TaskDetail\"\x99\x01\n\nTaskDetail\x12\x30\n\ncyclesType\x18\x01 \x01(\x0e\x32\x1c.cmd.EnumSubscribeCyclesType\x12\x16\n\x0e\x61ppointWeekday\x18\x02 \x01(\t\x12\x16\n\x0euseVehicleTime\x18\x03 \x01(\x04\x12)\n\rtaskCmdDetail\x18\x04 \x03(\x0b\x32\x12.cmd.TaskCmdDetail\"S\n\x11SubscribeTaskResp\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x13\n\x0bsubscribeId\x18\x04 \x01(\t\"o\n\x11SubscribeTaskExec\x12\x0e\n\x06\x65xecId\x18\x01 \x01(\t\x12\x13\n\x0bsubscribeId\x18\x02 \x01(\t\x12#\n\nexecDetail\x18\x03 \x03(\x0b\x32\x0f.cmd.ExecDetail\x12\x10\n\x08\x65xecTime\x18\x04 \x01(\x04*d\n\x17\x45numSubscribeCyclesType\x12\x0e\n\nSctUnknown\x10\x00\x12\x0b\n\x07SctOnce\x10\x01\x12\x0c\n\x08SctDaily\x10\x02\x12\x0e\n\nSctWorkDay\x10\x03\x12\x0e\n\nSctWeekDay\x10\x04\x42\x1fZ\x1dgo/remote_vehicle_control/cmdb\x06proto3')

_ENUMSUBSCRIBECYCLESTYPE = DESCRIPTOR.enum_types_by_name['EnumSubscribeCyclesType']
EnumSubscribeCyclesType = enum_type_wrapper.EnumTypeWrapper(_ENUMSUBSCRIBECYCLESTYPE)
SctUnknown = 0
SctOnce = 1
SctDaily = 2
SctWorkDay = 3
SctWeekDay = 4


_SUBSCRIBETASKREQ = DESCRIPTOR.message_types_by_name['SubscribeTaskReq']
_TASKDETAIL = DESCRIPTOR.message_types_by_name['TaskDetail']
_SUBSCRIBETASKRESP = DESCRIPTOR.message_types_by_name['SubscribeTaskResp']
_SUBSCRIBETASKEXEC = DESCRIPTOR.message_types_by_name['SubscribeTaskExec']
SubscribeTaskReq = _reflection.GeneratedProtocolMessageType('SubscribeTaskReq', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBETASKREQ,
  '__module__' : 'source.remote_vehicle_control.cmd.subscribe_cmd_pb2'
  # @@protoc_insertion_point(class_scope:cmd.SubscribeTaskReq)
  })
_sym_db.RegisterMessage(SubscribeTaskReq)

TaskDetail = _reflection.GeneratedProtocolMessageType('TaskDetail', (_message.Message,), {
  'DESCRIPTOR' : _TASKDETAIL,
  '__module__' : 'source.remote_vehicle_control.cmd.subscribe_cmd_pb2'
  # @@protoc_insertion_point(class_scope:cmd.TaskDetail)
  })
_sym_db.RegisterMessage(TaskDetail)

SubscribeTaskResp = _reflection.GeneratedProtocolMessageType('SubscribeTaskResp', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBETASKRESP,
  '__module__' : 'source.remote_vehicle_control.cmd.subscribe_cmd_pb2'
  # @@protoc_insertion_point(class_scope:cmd.SubscribeTaskResp)
  })
_sym_db.RegisterMessage(SubscribeTaskResp)

SubscribeTaskExec = _reflection.GeneratedProtocolMessageType('SubscribeTaskExec', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBETASKEXEC,
  '__module__' : 'source.remote_vehicle_control.cmd.subscribe_cmd_pb2'
  # @@protoc_insertion_point(class_scope:cmd.SubscribeTaskExec)
  })
_sym_db.RegisterMessage(SubscribeTaskExec)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035go/remote_vehicle_control/cmd'
  _ENUMSUBSCRIBECYCLESTYPE._serialized_start=645
  _ENUMSUBSCRIBECYCLESTYPE._serialized_end=745
  _SUBSCRIBETASKREQ._serialized_start=111
  _SUBSCRIBETASKREQ._serialized_end=289
  _TASKDETAIL._serialized_start=292
  _TASKDETAIL._serialized_end=445
  _SUBSCRIBETASKRESP._serialized_start=447
  _SUBSCRIBETASKRESP._serialized_end=530
  _SUBSCRIBETASKEXEC._serialized_start=532
  _SUBSCRIBETASKEXEC._serialized_end=643
# @@protoc_insertion_point(module_scope)
