dut_ecu: ["BGM"]
gateway_ip: "169.254.1.1"

bus:
  eth_obd: "enx000ec64a8e4c"
  eth_vlan5: "eth0.5"
  eth_vlan9: "eth0.9"
  bodycan: "can0"

veh_type: "mars1"
veh_gen: "G1.1"
bl_ver: "v_1_4_0"
mars1:
  bl_010:
    dbc_path: "data/dbc_file/force/v0_7_0"
    dbc_cyc_json_path: "dbc_cyc_json/force/bl070"
    dbc_cls_path: "dbc_cls/force/bl070"
    ldf_path: "data/ldf_file/force/v0_7_0"
    ldf_cls_path: "ldf_cls/force/bl070"

ecu_mock_cfg:
  ecu_name: "ALL"
  p_n_res: True
  nrc_code: 0x22
  diag_mode: "doip"
  server_doip_id: 0x1001
  server_ip: "127.0.0.1"

sd_tester_cfg:
  diag_mode: "doip"
  is_via_gateway: False
  ecu_name: "TCAM"
  dig_bus: "bodycan"
  server_ip: "127.0.0.1"
