# Examples
# cgw_ver: '04.05' or '04.03_04.04' or '04.07' or '00.01'
# gen_ver:  'g1.1_g1.2_g1.3' or 'g1.f' or 'g1.f.e'
# if there is no matched dut_ver, 'default' configuration will be used

# dbc_ldf_config.yaml  file name is permanent

force:
  - dut_ver: '00.01'
    veh_ver: 'bl0.0.1'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/v0_0_1'
        dbc_cyc_json_path: 'dbc_cyc_json/force/v0_0_1'
        dbc_cyc_json_ecu: 'SA'
        dbc_cls_path: 'dbc_cls/force/v0_0_1'
        ldf_path: 'data/ldf_file/force/v0_1_0'
        ldf_cls_path: 'ldf_cls/force/v0_1_0'
  - dut_ver: '00.10'
    veh_ver: 'bl0.1.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/v0_1_0'
        dbc_cyc_json_path: 'dbc_cyc_json/force/v0_1_0'
        dbc_cyc_json_ecu: 'SA'
        dbc_cls_path: 'dbc_cls/force/v0_1_0'
        ldf_path: 'data/ldf_file/force/v0_1_0'
        ldf_cls_path: 'ldf_cls/force/v0_1_0'
  - dut_ver: '1.0.0'
    veh_ver: 'bl0.2.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/v1_0_0'
        dbc_cyc_json_path: 'dbc_cyc_json/force/v1_0_0'
        dbc_cyc_json_ecu: 'SA'
        dbc_cls_path: 'dbc_cls/force/v1_0_0'
        ldf_path: 'data/ldf_file/force/v0_1_0'
        ldf_cls_path: 'ldf_cls/force/v0_1_0'
  - dut_ver: 'bl030.1.0.0'
    veh_ver: 'bl0.3.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/bl030_v1_0_0'
        dbc_cyc_json_path: 'dbc_cyc_json/force/bl030_v1_0_0'
        dbc_cyc_json_ecu: 'SA'
        dbc_cls_path: 'dbc_cls/force/bl030_v1_0_0'
        ldf_path: 'data/ldf_file/force/v0_1_0'
        ldf_cls_path: 'ldf_cls/force/v0_1_0'
  - dut_ver: 'bl040.1.0.3'
    veh_ver: 'bl0.4.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/bl040_v1_0_3'
        dbc_cyc_json_path: 'dbc_cyc_json/force/bl040_v1_0_3'
        dbc_cyc_json_ecu: 'SA'
        dbc_cls_path: 'dbc_cls/force/bl040_v1_0_3'
        ldf_path: 'data/ldf_file/force/v0_1_0'
        ldf_cls_path: 'ldf_cls/force/v0_1_0'
  - dut_ver: 'bl050.1.0.0'
    veh_ver: 'bl0.5.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/bl050_v1_0_0'
        dbc_cyc_json_path: 'dbc_cyc_json/force/bl050_v1_0_0'
        dbc_cyc_json_ecu: 'SA'
        dbc_cls_path: 'dbc_cls/force/bl050_v1_0_0'
        ldf_path: 'data/ldf_file/force/v0_1_0'
        ldf_cls_path: 'ldf_cls/force/v0_1_0'
  - dut_ver: 'bl_010'
    veh_ver: 'bl0.5.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/bl050'
        dbc_cyc_json_path: 'dbc_cyc_json/force/bl050'
        dbc_cyc_json_ecu: 'SA'
        dbc_cls_path: 'dbc_cls/force/bl050'
        ldf_path: 'data/ldf_file/force/v0_1_0'
        ldf_cls_path: 'ldf_cls/force/v0_1_0'
  - dut_ver: 'bl050'
    veh_ver: 'bl0.5.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/bl050'
        dbc_cyc_json_path: 'dbc_cyc_json/force/bl050'
        dbc_cyc_json_ecu: 'BGM'
        dbc_cls_path: 'dbc_cls/force/bl050'
        ldf_path: 'data/ldf_file/force/bl050'
        ldf_cls_path: 'ldf_cls/force/bl050'
  - dut_ver: 'bl070'
    veh_ver: 'bl0.7.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/v0_7_0'
        dbc_cyc_json_path: 'dbc_cyc_json/force/bl070'
        dbc_cyc_json_ecu: 'BGM'
        dbc_cls_path: 'dbc_cls/force/bl070'
        ldf_path: 'data/ldf_file/force/v0_7_0'
        ldf_cls_path: 'ldf_cls/force/bl070'
  - dut_ver: 'default'
    veh_ver: 'bl0.7.0'
    veh_gen:
      - gen_ver: 'g1.1_g1.2_g1.3'
        dbc_path: 'data/dbc_file/force/v0_7_0'
        dbc_cyc_json_path: 'dbc_cyc_json/force/bl070'
        dbc_cyc_json_ecu: 'SA'
        dbc_cls_path: 'dbc_cls/force/bl070'
        ldf_path: 'data/ldf_file/force/v0_7_0'
        ldf_cls_path: 'ldf_cls/force/bl070'