"""Export the ATS model schema as deterministic, offline PostgreSQL DDL.

This fresh-initialization artifact targets only the fixed, dedicated ats schema.
It never imports application settings, creates a database engine, or connects.
"""

import argparse
import importlib
import sys
from pathlib import Path
from types import ModuleType

from sqlalchemy import Index, MetaData
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import declarative_base
from sqlalchemy.schema import (
    AddConstraint, CreateIndex, CreateSchema, CreateTable,
    SetColumnComment, SetTableComment,
)

from init_postgres import validate_schema_name

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = "ats"
EXPECTED_TABLE_COUNT = 92
DEFAULT_OUTPUT = ROOT / "deploy" / "postgres_schema.sql"


def load_metadata():
    """Load models in this dedicated CLI process without application config.

    All ATS models import only Base from database. A local module containing that
    Base avoids importing database.py, its engine, settings, or any .env file.
    Refuse reuse in an already initialized application process.
    """
    if "database" in sys.modules or "models" in sys.modules:
        raise RuntimeError("Run the exporter in a fresh, dedicated Python process.")
    database = ModuleType("database")
    database.Base = declarative_base()
    sys.modules["database"] = database
    sys.path.insert(0, str(ROOT / "backend"))
    importlib.import_module("models")
    return database.Base.metadata


def render_schema(metadata):
    """Compile a single atomic statement; never alter the source metadata."""
    validate_schema_name(SCHEMA)
    if len(metadata.tables) != EXPECTED_TABLE_COUNT:
        raise ValueError("ATS model count changed; review the export contract before regenerating.")
    if any(table.schema is not None for table in metadata.tables.values()):
        raise ValueError("ATS metadata must not target another schema.")

    dialect = postgresql.dialect()
    target = MetaData()
    for table in sorted(metadata.tables.values(), key=lambda value: value.name):
        copied = table.to_metadata(target, schema=SCHEMA)
        # Column(index=True) names are regenerated with the destination schema
        # by to_metadata. Preserve the original names, including unique indexes.
        copied.indexes.clear()
        for index in table.indexes:
            if any(expression is not table.c.get(expression.name)
                   for expression in index.expressions):
                raise ValueError("Review support for expression indexes before exporting.")
            Index(index.name, *(copied.c[column.name] for column in index.columns),
                  unique=index.unique, **dict(index.dialect_kwargs))
    tables = sorted(target.tables.values(), key=lambda value: value.name)

    def compile_sql(element):
        return str(element.compile(dialect=dialect)).strip() + ";"

    # Emit non-primary constraints separately. Sorting rendered statements avoids
    # Python set iteration order and also handles cyclic foreign keys safely.
    constraints = []
    for table in tables:
        for constraint in list(table.constraints):
            if constraint is not table.primary_key:
                table.constraints.remove(constraint)
                constraints.append(compile_sql(AddConstraint(constraint)))

    statements = [compile_sql(CreateSchema(SCHEMA))]
    statements.extend(compile_sql(CreateTable(table)) for table in tables)
    statements.extend(sorted(constraints))
    statements.extend(sorted(
        compile_sql(CreateIndex(index)) for table in tables for index in table.indexes
    ))
    for table in tables:
        if table.comment is not None:
            statements.append(compile_sql(SetTableComment(table)))
        for column in table.columns:
            if column.comment is not None:
                statements.append(compile_sql(SetColumnComment(column)))

    body = "\n\n".join(statements)
    delimiter = "$ats_fresh_schema$"
    if delimiter in body:
        raise ValueError("DDL contains the reserved export block delimiter.")
    return (
        "-- Generated by scripts/export_postgres_schema.py; do not edit by hand.\n"
        "-- Fixed schema: ats. Expected ATS tables: 92. Fresh initialization only.\n"
        "-- One atomic DO statement; no transaction BEGIN/COMMIT commands.\n"
        "-- Safe inside an admin migration transaction or as one autocommit statement.\n"
        "-- An existing ats schema raises duplicate_schema before creating any object.\n"
        "-- No rows, roles, passwords, grants, extensions, or destructive DDL.\n"
        "-- Python-side defaults remain application-side; only server defaults are DDL.\n"
        "-- SERIAL/BIGSERIAL create owned sequences in the table's ats schema.\n\n"
        f"DO {delimiter}\n"
        "BEGIN\n"
        "    PERFORM pg_catalog.set_config('search_path', 'pg_catalog', true);\n"
        "    PERFORM pg_catalog.set_config('lock_timeout', '10s', true);\n\n"
        + "\n".join("    " + line.expandtabs(4).rstrip() if line.strip() else "" for line in body.splitlines())
        + f"\nEND\n{delimiter};\n"
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail if the artifact differs; write nothing.")
    args = parser.parse_args(argv)
    ddl = render_schema(load_metadata())
    if args.check:
        if not args.output.is_file() or args.output.read_bytes() != ddl.encode("utf-8"):
            parser.exit(1, "PostgreSQL DDL artifact is missing or differs; regenerate and review.\n")
    else:
        args.output.write_bytes(ddl.encode("utf-8"))
    print(f"Verified {EXPECTED_TABLE_COUNT} model tables for schema {SCHEMA}: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
