"""将已核对的扫描发现改为凭证注入，只输出路径与数量。"""
import argparse
import ast
import hashlib
import json
import logging
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
logger = logging.getLogger('xat.credentials')


def classification(item, source):
    path = item['File'].replace('\\', '/')
    secret = item['Secret']
    line = source.splitlines()[item['StartLine'] - 1]
    if '/sdk/auto/' in path or '/sdk/data/' in path:
        return '生成的信号名称和描述符，不是凭证'
    if path.endswith('_pb2.py') and ('AddSerializedFile' in source or 'Generated by the protocol buffer compiler' in source):
        return 'protobuf 静态协议描述符，不是凭证'
    if ('/ms/ms_lib.py' in path or '/window_canoe/' in path or 'ms_lib_match_ID_swrs_jama.py' in path) and re.fullmatch(r'[a-fA-F0-9]{8}(?:-[a-fA-F0-9]{4}){3}-[a-fA-F0-9]{12}', secret):
        return '测试管理字段标识 UUID，不是凭证'
    if path.endswith('/config_data.py') and re.fullmatch(r'[a-zA-Z_.]+', secret):
        return '车型配置属性名称，不是凭证'
    if path.endswith('/can_lin/pcan.py') and ('f_clock' in line or 'nom_brp' in line):
        return 'CAN 波特率参数，不是凭证'
    if 'no_opera_signal=' in line:
        return '信号名称列表，不是凭证'
    return None


def main(report):
    findings = json.loads(report.read_text())
    groups = defaultdict(list)
    for item in findings:
        groups[item['File']].append(item)
    audit, changed = [], 0
    for filename, items in groups.items():
        path = Path(filename)
        source = path.read_text(encoding='utf-8-sig')
        is_python = path.suffix == '.py'
        try:
            tree = ast.parse(source) if is_python else None
        except SyntaxError:
            logger.exception('凭证处理遇到原语法错误，使用文本替换：%s', path)
            tree = None
        lines = source.splitlines(keepends=True)
        offsets = [0]
        for line in lines:
            offsets.append(offsets[-1] + len(line))
        edits, textual = {}, {}
        for item in items:
            reason = classification(item, source)
            info = {'路径': filename, '行': item['StartLine'], '规则': item['RuleID']}
            if reason:
                info['状态'] = reason
                audit.append(info)
                continue
            secret = item['Secret']
            key = 'XAT_CREDENTIAL_SCAN_' + hashlib.sha256((filename + ':' + str(item['StartLine']) + ':' + item['RuleID']).encode()).hexdigest()[:20].upper()
            info.update({'状态':'改为环境变量注入', '环境变量':key})
            audit.append(info)
            # 使用 AST 位置替换整个字符串常量，保留表达式其余部分。
            found = False
            if tree:
                for node in ast.walk(tree):
                    if not isinstance(node, ast.Constant) or not isinstance(node.value, (str, bytes)):
                        continue
                    value = node.value.decode(errors='replace') if isinstance(node.value, bytes) else node.value
                    if secret not in value or not (node.lineno <= item['StartLine'] <= node.end_lineno):
                        continue
                    start = offsets[node.lineno-1] + len(lines[node.lineno-1].encode()[:node.col_offset].decode())
                    end = offsets[node.end_lineno-1] + len(lines[node.end_lineno-1].encode()[:node.end_col_offset].decode())
                    # f-string 常量位置覆盖整个 JoinedStr，改为由使用方提供整个命令/URL。
                    expression = '__import__("os").environ[' + repr(key) + ']'
                    if isinstance(node.value, bytes):
                        expression += '.encode()'
                    edits[(start,end)] = expression
                    found = True
                    break
            if not found:
                textual[secret] = '${' + key + '}'
        for (start,end), value in sorted(edits.items(), reverse=True):
            source = source[:start] + value + source[end:]
        for secret, value in textual.items():
            source = source.replace(secret, value)
        if edits or textual:
            path.write_text(source, encoding='utf-8')
            changed += 1
    (ROOT/'docs/migration/凭证扫描处理.json').write_text(json.dumps(audit,ensure_ascii=False,indent=2))
    logger.info('凭证扫描处理完成：匹配=%s，修改文件=%s，已核对非凭证=%s', len(audit),changed,sum('不是凭证' in item['状态'] for item in audit))


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO,format='%(asctime)s | %(levelname)s | %(message)s')
    parser=argparse.ArgumentParser();parser.add_argument('report',type=Path)
    main(parser.parse_args().report)
