# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 获取Salt.json
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 751, 81))
        self.groupBox.setObjectName("groupBox")
        self.getNetlist = QtWidgets.QPushButton(self.groupBox)
        self.getNetlist.setGeometry(QtCore.QRect(10, 40, 81, 31))
        self.getNetlist.setObjectName("getNetlist")
        self.comboBox_netlist = QtWidgets.QTextEdit(self.groupBox)
        self.comboBox_netlist.setGeometry(QtCore.QRect(110, 40, 171, 31))
        self.comboBox_netlist.setReadOnly(True)
        self.comboBox_netlist.setObjectName("comboBox_netlist")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(300, 40, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(400, 40, 231, 31))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        # 连接BGM
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(10, 131, 751, 81))
        self.groupBox1.setObjectName("groupBox1")
        self.getNetlist1 = QtWidgets.QPushButton(self.groupBox1)
        self.getNetlist1.setGeometry(QtCore.QRect(10, 40, 81, 31))
        self.getNetlist1.setObjectName("getNetlist1")
        self.comboBox_netlist1 = QtWidgets.QTextEdit(self.groupBox1)
        self.comboBox_netlist1.setGeometry(QtCore.QRect(110, 40, 171, 31))
        self.comboBox_netlist1.setReadOnly(True)
        self.comboBox_netlist1.setObjectName("comboBox_netlist1")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton1.setGeometry(QtCore.QRect(300, 40, 81, 31))
        self.pushButton1.setObjectName("pushButton1")
        self.textEdit1 = QtWidgets.QTextEdit(self.groupBox1)
        self.textEdit1.setGeometry(QtCore.QRect(400, 40, 231, 31))
        self.textEdit1.setReadOnly(True)
        self.textEdit1.setObjectName("textEdit1")
        self.pushButton11 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton11.setGeometry(QtCore.QRect(650, 40, 81, 31))
        self.pushButton11.setObjectName("pushButton11")

        # 连接TCAM
        self.groupBox2= QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(10, 242, 751, 81))
        self.groupBox2.setObjectName("groupBox2")
        self.getNetlist2 = QtWidgets.QPushButton(self.groupBox2)
        self.getNetlist2.setGeometry(QtCore.QRect(10, 40, 81, 31))
        self.getNetlist2.setObjectName("getNetlist2")
        self.comboBox_netlist2 = QtWidgets.QTextEdit(self.groupBox2)
        self.comboBox_netlist2.setGeometry(QtCore.QRect(110, 40, 171, 31))
        self.comboBox_netlist2.setReadOnly(True)
        self.comboBox_netlist2.setObjectName("comboBox_netlist2")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox2)
        self.pushButton2.setGeometry(QtCore.QRect(300, 40, 81, 31))
        self.pushButton2.setObjectName("pushButton2")
        self.textEdit2 = QtWidgets.QTextEdit(self.groupBox2)
        self.textEdit2.setGeometry(QtCore.QRect(400, 40, 231, 31))
        self.textEdit2.setReadOnly(True)
        self.textEdit2.setObjectName("textEdit2")
        self.pushButton22 = QtWidgets.QPushButton(self.groupBox2)
        self.pushButton22.setGeometry(QtCore.QRect(650, 40, 81, 31))
        self.pushButton22.setObjectName("pushButton22")

        # OBD防火墙
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox3.setGeometry(QtCore.QRect(10, 353, 751, 81))
        self.groupBox3.setObjectName("groupBox3")
        self.getNetlist3 = QtWidgets.QPushButton(self.groupBox3)
        self.getNetlist3.setGeometry(QtCore.QRect(10, 40, 130, 31))
        self.getNetlist3.setObjectName("getNetlist3")
        self.pushButton3 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton3.setGeometry(QtCore.QRect(159, 40, 130, 31))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton31 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton31.setGeometry(QtCore.QRect(308, 40, 130, 31))
        self.pushButton31.setObjectName("pushButton3")
        self.pushButton32 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton32.setGeometry(QtCore.QRect(457, 40, 130, 31))
        self.pushButton32.setObjectName("pushButton3")

        # self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_2.setGeometry(QtCore.QRect(70, 130, 75, 23))
        # self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 22))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.getNetlist.clicked.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GetSalt"))
        self.getNetlist.setText(_translate("MainWindow", "获取IP"))
        self.comboBox_netlist.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "获取slat"))
        # self.pushButton_2.setText(_translate("MainWindow", "PushButtonPushButton"))

        self.groupBox1.setTitle(_translate("MainWindow", "连接BGM"))
        self.getNetlist1.setText(_translate("MainWindow", "开始连接"))
        self.comboBox_netlist1.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton1.setText(_translate("MainWindow", "执行命令"))
        self.pushButton11.setText(_translate("MainWindow", "清除证书"))

        self.groupBox2.setTitle(_translate("MainWindow", "连接TCAM"))
        self.getNetlist2.setText(_translate("MainWindow", "开始连接"))
        self.comboBox_netlist2.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton2.setText(_translate("MainWindow", "执行命令"))
        self.pushButton22.setText(_translate("MainWindow", "清除证书"))

        self.groupBox3.setTitle(_translate("MainWindow", "OBD防火墙"))
        self.getNetlist3.setText(_translate("MainWindow", "打开OBD防火墙"))
        self.pushButton3.setText(_translate("MainWindow", "关闭OBD防火墙"))
        self.pushButton31.setText(_translate("MainWindow", " 绕行AESKey"))
        self.pushButton32.setText(_translate("MainWindow", "恢复AESKey"))
