# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: VehicleCloud.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'VehicleCloud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12VehicleCloud.proto\x12\x07jet.v2t\"L\n\x12VehicleCloudInvoke\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.jet.v2t.V2TInvokeHeader\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"\xbc\x01\n\x0fV2TInvokeHeader\x12\x0b\n\x03ver\x18\x01 \x01(\t\x12\x11\n\ttimeStamp\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\r\n\x05msgId\x18\x04 \x01(\x03\x12\x0f\n\x07traceId\x18\x05 \x01(\t\x12&\n\treqTarget\x18\x06 \x01(\x0b\x32\x13.jet.v2t.ServiceUri\x12\x1f\n\x03\x65rr\x18\x07 \x01(\x0b\x32\x12.jet.v2t.ErrorInfo\x12\x12\n\nreqTimeout\x18\x08 \x01(\x05\":\n\nServiceUri\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0b\n\x03\x61pi\x18\x02 \x01(\t\x12\x0e\n\x06wakeup\x18\x03 \x01(\x08\"%\n\tErrorInfo\x12\x0b\n\x03\x65rr\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VehicleCloud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLECLOUDINVOKE']._serialized_start=31
  _globals['_VEHICLECLOUDINVOKE']._serialized_end=107
  _globals['_V2TINVOKEHEADER']._serialized_start=110
  _globals['_V2TINVOKEHEADER']._serialized_end=298
  _globals['_SERVICEURI']._serialized_start=300
  _globals['_SERVICEURI']._serialized_end=358
  _globals['_ERRORINFO']._serialized_start=360
  _globals['_ERRORINFO']._serialized_end=397
# @@protoc_insertion_point(module_scope)
